// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IncomingTransaction struct {
	EncryptedTransaction string   `protobuf:"bytes,1,opt,name=encrypted_transaction,json=encryptedTransaction,proto3" json:"encrypted_transaction,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncomingTransaction) Reset()         { *m = IncomingTransaction{} }
func (m *IncomingTransaction) String() string { return proto.CompactTextString(m) }
func (*IncomingTransaction) ProtoMessage()    {}
func (*IncomingTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{0}
}
func (m *IncomingTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncomingTransaction.Unmarshal(m, b)
}
func (m *IncomingTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncomingTransaction.Marshal(b, m, deterministic)
}
func (dst *IncomingTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomingTransaction.Merge(dst, src)
}
func (m *IncomingTransaction) XXX_Size() int {
	return xxx_messageInfo_IncomingTransaction.Size(m)
}
func (m *IncomingTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomingTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_IncomingTransaction proto.InternalMessageInfo

func (m *IncomingTransaction) GetEncryptedTransaction() string {
	if m != nil {
		return m.EncryptedTransaction
	}
	return ""
}

func (m *IncomingTransaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type InternalTransactionStatusRequest struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	TransactionAddress   string   `protobuf:"bytes,2,opt,name=transaction_address,json=transactionAddress,proto3" json:"transaction_address,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalTransactionStatusRequest) Reset()         { *m = InternalTransactionStatusRequest{} }
func (m *InternalTransactionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*InternalTransactionStatusRequest) ProtoMessage()    {}
func (*InternalTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{1}
}
func (m *InternalTransactionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalTransactionStatusRequest.Unmarshal(m, b)
}
func (m *InternalTransactionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalTransactionStatusRequest.Marshal(b, m, deterministic)
}
func (dst *InternalTransactionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalTransactionStatusRequest.Merge(dst, src)
}
func (m *InternalTransactionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_InternalTransactionStatusRequest.Size(m)
}
func (m *InternalTransactionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalTransactionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalTransactionStatusRequest proto.InternalMessageInfo

func (m *InternalTransactionStatusRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *InternalTransactionStatusRequest) GetTransactionAddress() string {
	if m != nil {
		return m.TransactionAddress
	}
	return ""
}

func (m *InternalTransactionStatusRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TransactionResult struct {
	TransactionReceipt   string   `protobuf:"bytes,1,opt,name=transaction_receipt,json=transactionReceipt,proto3" json:"transaction_receipt,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResult) Reset()         { *m = TransactionResult{} }
func (m *TransactionResult) String() string { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()    {}
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{2}
}
func (m *TransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResult.Unmarshal(m, b)
}
func (m *TransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResult.Marshal(b, m, deterministic)
}
func (dst *TransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResult.Merge(dst, src)
}
func (m *TransactionResult) XXX_Size() int {
	return xxx_messageInfo_TransactionResult.Size(m)
}
func (m *TransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResult proto.InternalMessageInfo

func (m *TransactionResult) GetTransactionReceipt() string {
	if m != nil {
		return m.TransactionReceipt
	}
	return ""
}

func (m *TransactionResult) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionResult) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type GetAccountRequest struct {
	EncryptedIdAddress   string   `protobuf:"bytes,1,opt,name=encrypted_id_address,json=encryptedIdAddress,proto3" json:"encrypted_id_address,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{3}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetEncryptedIdAddress() string {
	if m != nil {
		return m.EncryptedIdAddress
	}
	return ""
}

func (m *GetAccountRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetAccountResponse struct {
	EncryptedWallet      string   `protobuf:"bytes,1,opt,name=encrypted_wallet,json=encryptedWallet,proto3" json:"encrypted_wallet,omitempty"`
	EncryptedAesKey      string   `protobuf:"bytes,2,opt,name=encrypted_aes_key,json=encryptedAesKey,proto3" json:"encrypted_aes_key,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    string   `protobuf:"bytes,4,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{4}
}
func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(dst, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetEncryptedWallet() string {
	if m != nil {
		return m.EncryptedWallet
	}
	return ""
}

func (m *GetAccountResponse) GetEncryptedAesKey() string {
	if m != nil {
		return m.EncryptedAesKey
	}
	return ""
}

func (m *GetAccountResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetAccountResponse) GetSignatureResponse() string {
	if m != nil {
		return m.SignatureResponse
	}
	return ""
}

type LastSharedKeysRequest struct {
	EmitterPublicKey     string   `protobuf:"bytes,1,opt,name=emitter_public_key,json=emitterPublicKey,proto3" json:"emitter_public_key,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastSharedKeysRequest) Reset()         { *m = LastSharedKeysRequest{} }
func (m *LastSharedKeysRequest) String() string { return proto.CompactTextString(m) }
func (*LastSharedKeysRequest) ProtoMessage()    {}
func (*LastSharedKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{5}
}
func (m *LastSharedKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastSharedKeysRequest.Unmarshal(m, b)
}
func (m *LastSharedKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastSharedKeysRequest.Marshal(b, m, deterministic)
}
func (dst *LastSharedKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastSharedKeysRequest.Merge(dst, src)
}
func (m *LastSharedKeysRequest) XXX_Size() int {
	return xxx_messageInfo_LastSharedKeysRequest.Size(m)
}
func (m *LastSharedKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastSharedKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastSharedKeysRequest proto.InternalMessageInfo

func (m *LastSharedKeysRequest) GetEmitterPublicKey() string {
	if m != nil {
		return m.EmitterPublicKey
	}
	return ""
}

func (m *LastSharedKeysRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type LastSharedKeys struct {
	EmitterKeys          []*SharedKeyPair `protobuf:"bytes,1,rep,name=emitter_keys,json=emitterKeys,proto3" json:"emitter_keys,omitempty"`
	NodePublicKey        string           `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	Timestamp            int64            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LastSharedKeys) Reset()         { *m = LastSharedKeys{} }
func (m *LastSharedKeys) String() string { return proto.CompactTextString(m) }
func (*LastSharedKeys) ProtoMessage()    {}
func (*LastSharedKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_eedb2a82cad8975d, []int{6}
}
func (m *LastSharedKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastSharedKeys.Unmarshal(m, b)
}
func (m *LastSharedKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastSharedKeys.Marshal(b, m, deterministic)
}
func (dst *LastSharedKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastSharedKeys.Merge(dst, src)
}
func (m *LastSharedKeys) XXX_Size() int {
	return xxx_messageInfo_LastSharedKeys.Size(m)
}
func (m *LastSharedKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_LastSharedKeys.DiscardUnknown(m)
}

var xxx_messageInfo_LastSharedKeys proto.InternalMessageInfo

func (m *LastSharedKeys) GetEmitterKeys() []*SharedKeyPair {
	if m != nil {
		return m.EmitterKeys
	}
	return nil
}

func (m *LastSharedKeys) GetNodePublicKey() string {
	if m != nil {
		return m.NodePublicKey
	}
	return ""
}

func (m *LastSharedKeys) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*IncomingTransaction)(nil), "api.IncomingTransaction")
	proto.RegisterType((*InternalTransactionStatusRequest)(nil), "api.InternalTransactionStatusRequest")
	proto.RegisterType((*TransactionResult)(nil), "api.TransactionResult")
	proto.RegisterType((*GetAccountRequest)(nil), "api.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "api.GetAccountResponse")
	proto.RegisterType((*LastSharedKeysRequest)(nil), "api.LastSharedKeysRequest")
	proto.RegisterType((*LastSharedKeys)(nil), "api.LastSharedKeys")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalServiceClient interface {
	HandleTransaction(ctx context.Context, in *IncomingTransaction, opts ...grpc.CallOption) (*TransactionResult, error)
	GetTransactionStatus(ctx context.Context, in *InternalTransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatusResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	GetLastSharedKeys(ctx context.Context, in *LastSharedKeysRequest, opts ...grpc.CallOption) (*LastSharedKeys, error)
}

type internalServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalServiceClient(cc *grpc.ClientConn) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) HandleTransaction(ctx context.Context, in *IncomingTransaction, opts ...grpc.CallOption) (*TransactionResult, error) {
	out := new(TransactionResult)
	err := c.cc.Invoke(ctx, "/api.InternalService/HandleTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetTransactionStatus(ctx context.Context, in *InternalTransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatusResponse, error) {
	out := new(TransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/api.InternalService/GetTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/api.InternalService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetLastSharedKeys(ctx context.Context, in *LastSharedKeysRequest, opts ...grpc.CallOption) (*LastSharedKeys, error) {
	out := new(LastSharedKeys)
	err := c.cc.Invoke(ctx, "/api.InternalService/GetLastSharedKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
type InternalServiceServer interface {
	HandleTransaction(context.Context, *IncomingTransaction) (*TransactionResult, error)
	GetTransactionStatus(context.Context, *InternalTransactionStatusRequest) (*TransactionStatusResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	GetLastSharedKeys(context.Context, *LastSharedKeysRequest) (*LastSharedKeys, error)
}

func RegisterInternalServiceServer(s *grpc.Server, srv InternalServiceServer) {
	s.RegisterService(&_InternalService_serviceDesc, srv)
}

func _InternalService_HandleTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).HandleTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.InternalService/HandleTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).HandleTransaction(ctx, req.(*IncomingTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.InternalService/GetTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetTransactionStatus(ctx, req.(*InternalTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.InternalService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetLastSharedKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastSharedKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetLastSharedKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.InternalService/GetLastSharedKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetLastSharedKeys(ctx, req.(*LastSharedKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleTransaction",
			Handler:    _InternalService_HandleTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _InternalService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _InternalService_GetAccount_Handler,
		},
		{
			MethodName: "GetLastSharedKeys",
			Handler:    _InternalService_GetLastSharedKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_internal_eedb2a82cad8975d) }

var fileDescriptor_internal_eedb2a82cad8975d = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x0d, 0x42, 0xea, 0xf4, 0x23, 0xcd, 0xa6, 0x85, 0xc8, 0x42, 0x28, 0x8a, 0x04, 0x0a,
	0x08, 0x02, 0x6a, 0xc5, 0x91, 0x43, 0x0e, 0xd0, 0x46, 0xe5, 0x50, 0x39, 0x48, 0x9c, 0x90, 0xb5,
	0x5d, 0x8f, 0x92, 0x55, 0xed, 0x5d, 0xb3, 0xbb, 0x06, 0xe5, 0xc6, 0x1f, 0xe0, 0x1f, 0xf0, 0x43,
	0x38, 0xf1, 0xdb, 0x50, 0xd6, 0x6b, 0x7b, 0x1b, 0x87, 0x72, 0xcc, 0x7b, 0xb3, 0xf3, 0xde, 0x3c,
	0xcf, 0x04, 0x0e, 0xb9, 0x30, 0xa8, 0x04, 0x4d, 0x27, 0xb9, 0x92, 0x46, 0x92, 0x0e, 0xcd, 0x79,
	0x78, 0xa0, 0x8d, 0x54, 0x74, 0x81, 0x25, 0x16, 0xee, 0x33, 0x99, 0x65, 0x52, 0x94, 0xbf, 0x46,
	0x4b, 0xe8, 0xcf, 0x04, 0x93, 0x19, 0x17, 0x8b, 0x4f, 0x8a, 0x0a, 0x4d, 0x99, 0xe1, 0x52, 0x90,
	0x33, 0x38, 0x41, 0xc1, 0xd4, 0x2a, 0x37, 0x98, 0xc4, 0xa6, 0x21, 0x06, 0xc1, 0x30, 0x18, 0xef,
	0x46, 0xc7, 0x35, 0xe9, 0x3f, 0x7a, 0x0c, 0xbb, 0x86, 0x67, 0xa8, 0x0d, 0xcd, 0xf2, 0xc1, 0xce,
	0x30, 0x18, 0x77, 0xa2, 0x06, 0x18, 0xfd, 0x0a, 0x60, 0x38, 0x73, 0xf6, 0xbc, 0x57, 0x73, 0x43,
	0x4d, 0xa1, 0x23, 0xfc, 0x5a, 0xa0, 0x36, 0xe4, 0x39, 0x1c, 0x79, 0x6a, 0xf1, 0x92, 0xea, 0xa5,
	0x93, 0xec, 0x7a, 0xf8, 0x05, 0xd5, 0x4b, 0xf2, 0x1a, 0xfa, 0x7e, 0x29, 0x4d, 0x12, 0x85, 0x5a,
	0x5b, 0xdd, 0xdd, 0x88, 0x78, 0xd4, 0xb4, 0x64, 0x6e, 0xdb, 0xeb, 0x6c, 0xda, 0xfb, 0x11, 0x40,
	0xcf, 0xb3, 0x15, 0xa1, 0x2e, 0x52, 0xb3, 0x29, 0xa2, 0x90, 0x21, 0xcf, 0x8d, 0xb3, 0xe4, 0x8b,
	0x44, 0x25, 0x73, 0xb7, 0xc8, 0x9a, 0xd5, 0x7c, 0x21, 0xa8, 0x29, 0x14, 0x0e, 0xee, 0xdb, 0x26,
	0x0d, 0x30, 0x62, 0xd0, 0x3b, 0x47, 0x33, 0x65, 0x4c, 0x16, 0xc2, 0x54, 0x89, 0xbc, 0x81, 0x26,
	0xec, 0x98, 0x27, 0xf5, 0x9c, 0xce, 0x42, 0xcd, 0xcd, 0x92, 0xad, 0x73, 0xb6, 0x3e, 0xc3, 0xef,
	0x00, 0x88, 0xaf, 0xa2, 0x73, 0x29, 0x34, 0xae, 0x83, 0x6f, 0x64, 0xbe, 0xd3, 0x34, 0xc5, 0x6a,
	0xca, 0x6e, 0x8d, 0x7f, 0xb6, 0x30, 0x79, 0x01, 0xbd, 0xa6, 0x94, 0xa2, 0x8e, 0x6f, 0x70, 0xe5,
	0x62, 0x6f, 0x6a, 0xa7, 0xa8, 0x2f, 0x71, 0xf5, 0x9f, 0x38, 0x5e, 0x01, 0xa9, 0xa7, 0x8f, 0x95,
	0xb3, 0xe2, 0x72, 0xe9, 0xd5, 0x4c, 0xe5, 0x71, 0xc4, 0xe0, 0xe4, 0x23, 0xd5, 0x66, 0xbe, 0xa4,
	0x0a, 0x93, 0x4b, 0x5c, 0xd5, 0x5b, 0xf3, 0x12, 0x08, 0x66, 0xdc, 0x18, 0x54, 0x71, 0x5e, 0x5c,
	0xa7, 0x9c, 0x59, 0x4b, 0xa5, 0xfd, 0x23, 0xc7, 0x5c, 0x59, 0xa2, 0xe5, 0xa9, 0x95, 0xcf, 0xcf,
	0x00, 0x0e, 0x6f, 0xab, 0x90, 0xb7, 0xb0, 0x5f, 0xb5, 0xbf, 0xc1, 0xd5, 0x3a, 0xfa, 0xce, 0x78,
	0xef, 0x94, 0x4c, 0x68, 0xce, 0x27, 0x75, 0xd9, 0x15, 0xe5, 0x2a, 0xda, 0x73, 0x75, 0xf6, 0xd9,
	0x33, 0xe8, 0x0a, 0x99, 0xa0, 0x6f, 0xa9, 0x4c, 0xe9, 0x60, 0x0d, 0xff, 0xc3, 0xcf, 0x66, 0x46,
	0xa7, 0x7f, 0x76, 0xa0, 0x5b, 0x9d, 0xcd, 0x1c, 0xd5, 0x37, 0xce, 0x90, 0xbc, 0x87, 0xde, 0x05,
	0x15, 0x49, 0x8a, 0xfe, 0xf5, 0x0d, 0xac, 0x9f, 0x2d, 0xc7, 0x1c, 0x3e, 0xb4, 0x4c, 0x7b, 0xb9,
	0xbf, 0xc0, 0xf1, 0x39, 0x9a, 0xd6, 0x2d, 0x92, 0xa7, 0xae, 0xd3, 0xdd, 0xb7, 0x1a, 0x3e, 0xd9,
	0x6c, 0x5b, 0xd1, 0x6e, 0xa5, 0xde, 0x01, 0x34, 0x8b, 0x46, 0x4a, 0x13, 0xad, 0xfd, 0x0e, 0x1f,
	0xb5, 0x70, 0xf7, 0xfc, 0x83, 0xbd, 0x86, 0x8d, 0x4f, 0x11, 0xda, 0xea, 0xad, 0x5b, 0x10, 0xf6,
	0xb7, 0x70, 0xa3, 0x7b, 0xd7, 0x0f, 0xec, 0x1f, 0xdd, 0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0x9c, 0x25, 0x65, 0x1c, 0x05, 0x00, 0x00,
}
