// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mining.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LeadMiningRequest struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MinimumValidations   int32        `protobuf:"varint,2,opt,name=minimum_validations,json=minimumValidations,proto3" json:"minimum_validations,omitempty"`
	Timestamp            int64        `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     string       `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LeadMiningRequest) Reset()         { *m = LeadMiningRequest{} }
func (m *LeadMiningRequest) String() string { return proto.CompactTextString(m) }
func (*LeadMiningRequest) ProtoMessage()    {}
func (*LeadMiningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mining_a8b90d702c7fbca7, []int{0}
}
func (m *LeadMiningRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadMiningRequest.Unmarshal(m, b)
}
func (m *LeadMiningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadMiningRequest.Marshal(b, m, deterministic)
}
func (dst *LeadMiningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadMiningRequest.Merge(dst, src)
}
func (m *LeadMiningRequest) XXX_Size() int {
	return xxx_messageInfo_LeadMiningRequest.Size(m)
}
func (m *LeadMiningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadMiningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeadMiningRequest proto.InternalMessageInfo

func (m *LeadMiningRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *LeadMiningRequest) GetMinimumValidations() int32 {
	if m != nil {
		return m.MinimumValidations
	}
	return 0
}

func (m *LeadMiningRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LeadMiningRequest) GetSignatureRequest() string {
	if m != nil {
		return m.SignatureRequest
	}
	return ""
}

type LeadMiningResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    string   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeadMiningResponse) Reset()         { *m = LeadMiningResponse{} }
func (m *LeadMiningResponse) String() string { return proto.CompactTextString(m) }
func (*LeadMiningResponse) ProtoMessage()    {}
func (*LeadMiningResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mining_a8b90d702c7fbca7, []int{1}
}
func (m *LeadMiningResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadMiningResponse.Unmarshal(m, b)
}
func (m *LeadMiningResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadMiningResponse.Marshal(b, m, deterministic)
}
func (dst *LeadMiningResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadMiningResponse.Merge(dst, src)
}
func (m *LeadMiningResponse) XXX_Size() int {
	return xxx_messageInfo_LeadMiningResponse.Size(m)
}
func (m *LeadMiningResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadMiningResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeadMiningResponse proto.InternalMessageInfo

func (m *LeadMiningResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LeadMiningResponse) GetSignatureResponse() string {
	if m != nil {
		return m.SignatureResponse
	}
	return ""
}

type ConfirmValidationRequest struct {
	Transaction          *Transaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MasterValidation     *MasterValidation `protobuf:"bytes,2,opt,name=master_validation,json=masterValidation,proto3" json:"master_validation,omitempty"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     string            `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfirmValidationRequest) Reset()         { *m = ConfirmValidationRequest{} }
func (m *ConfirmValidationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmValidationRequest) ProtoMessage()    {}
func (*ConfirmValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mining_a8b90d702c7fbca7, []int{2}
}
func (m *ConfirmValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmValidationRequest.Unmarshal(m, b)
}
func (m *ConfirmValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmValidationRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmValidationRequest.Merge(dst, src)
}
func (m *ConfirmValidationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmValidationRequest.Size(m)
}
func (m *ConfirmValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmValidationRequest proto.InternalMessageInfo

func (m *ConfirmValidationRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ConfirmValidationRequest) GetMasterValidation() *MasterValidation {
	if m != nil {
		return m.MasterValidation
	}
	return nil
}

func (m *ConfirmValidationRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConfirmValidationRequest) GetSignatureRequest() string {
	if m != nil {
		return m.SignatureRequest
	}
	return ""
}

type ConfirmValidationResponse struct {
	Validation           *Validation `protobuf:"bytes,1,opt,name=validation,proto3" json:"validation,omitempty"`
	Timestamp            int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    string      `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfirmValidationResponse) Reset()         { *m = ConfirmValidationResponse{} }
func (m *ConfirmValidationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmValidationResponse) ProtoMessage()    {}
func (*ConfirmValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mining_a8b90d702c7fbca7, []int{3}
}
func (m *ConfirmValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmValidationResponse.Unmarshal(m, b)
}
func (m *ConfirmValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmValidationResponse.Marshal(b, m, deterministic)
}
func (dst *ConfirmValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmValidationResponse.Merge(dst, src)
}
func (m *ConfirmValidationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmValidationResponse.Size(m)
}
func (m *ConfirmValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmValidationResponse proto.InternalMessageInfo

func (m *ConfirmValidationResponse) GetValidation() *Validation {
	if m != nil {
		return m.Validation
	}
	return nil
}

func (m *ConfirmValidationResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConfirmValidationResponse) GetSignatureResponse() string {
	if m != nil {
		return m.SignatureResponse
	}
	return ""
}

func init() {
	proto.RegisterType((*LeadMiningRequest)(nil), "api.LeadMiningRequest")
	proto.RegisterType((*LeadMiningResponse)(nil), "api.LeadMiningResponse")
	proto.RegisterType((*ConfirmValidationRequest)(nil), "api.ConfirmValidationRequest")
	proto.RegisterType((*ConfirmValidationResponse)(nil), "api.ConfirmValidationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiningServiceClient is the client API for MiningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiningServiceClient interface {
	LeadTransactionMining(ctx context.Context, in *LeadMiningRequest, opts ...grpc.CallOption) (*LeadMiningResponse, error)
	ConfirmTransactionValidation(ctx context.Context, in *ConfirmValidationRequest, opts ...grpc.CallOption) (*ConfirmValidationResponse, error)
}

type miningServiceClient struct {
	cc *grpc.ClientConn
}

func NewMiningServiceClient(cc *grpc.ClientConn) MiningServiceClient {
	return &miningServiceClient{cc}
}

func (c *miningServiceClient) LeadTransactionMining(ctx context.Context, in *LeadMiningRequest, opts ...grpc.CallOption) (*LeadMiningResponse, error) {
	out := new(LeadMiningResponse)
	err := c.cc.Invoke(ctx, "/api.MiningService/LeadTransactionMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miningServiceClient) ConfirmTransactionValidation(ctx context.Context, in *ConfirmValidationRequest, opts ...grpc.CallOption) (*ConfirmValidationResponse, error) {
	out := new(ConfirmValidationResponse)
	err := c.cc.Invoke(ctx, "/api.MiningService/ConfirmTransactionValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiningServiceServer is the server API for MiningService service.
type MiningServiceServer interface {
	LeadTransactionMining(context.Context, *LeadMiningRequest) (*LeadMiningResponse, error)
	ConfirmTransactionValidation(context.Context, *ConfirmValidationRequest) (*ConfirmValidationResponse, error)
}

func RegisterMiningServiceServer(s *grpc.Server, srv MiningServiceServer) {
	s.RegisterService(&_MiningService_serviceDesc, srv)
}

func _MiningService_LeadTransactionMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeadMiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiningServiceServer).LeadTransactionMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MiningService/LeadTransactionMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiningServiceServer).LeadTransactionMining(ctx, req.(*LeadMiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiningService_ConfirmTransactionValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiningServiceServer).ConfirmTransactionValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MiningService/ConfirmTransactionValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiningServiceServer).ConfirmTransactionValidation(ctx, req.(*ConfirmValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MiningService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MiningService",
	HandlerType: (*MiningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeadTransactionMining",
			Handler:    _MiningService_LeadTransactionMining_Handler,
		},
		{
			MethodName: "ConfirmTransactionValidation",
			Handler:    _MiningService_ConfirmTransactionValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mining.proto",
}

func init() { proto.RegisterFile("mining.proto", fileDescriptor_mining_a8b90d702c7fbca7) }

var fileDescriptor_mining_a8b90d702c7fbca7 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4a, 0x03, 0x31,
	0x14, 0x26, 0x1d, 0x15, 0xfa, 0x5a, 0xb1, 0x13, 0xa9, 0x8e, 0xa5, 0xca, 0xd0, 0xd5, 0x80, 0xd8,
	0xc2, 0x78, 0x03, 0xdd, 0xb8, 0xb0, 0x9b, 0x51, 0xdc, 0x49, 0x89, 0x6d, 0x2c, 0x01, 0x93, 0x8c,
	0x49, 0xda, 0xbb, 0x78, 0x13, 0xf7, 0x9e, 0xc3, 0xbb, 0x48, 0x93, 0xc1, 0xbe, 0xb6, 0x16, 0x04,
	0xdd, 0x7e, 0xdf, 0x7b, 0xf9, 0x7e, 0xde, 0x0c, 0x34, 0xa5, 0x50, 0x42, 0x4d, 0xfb, 0xa5, 0xd1,
	0x4e, 0xd3, 0x88, 0x95, 0xa2, 0xd3, 0x1c, 0x6b, 0x29, 0xb5, 0x0a, 0x50, 0xef, 0x83, 0x40, 0x7c,
	0xcb, 0xd9, 0x64, 0xe8, 0xe7, 0x0a, 0xfe, 0x3a, 0xe3, 0xd6, 0xd1, 0x1c, 0x1a, 0xce, 0x30, 0x65,
	0xd9, 0xd8, 0x09, 0xad, 0x12, 0x92, 0x92, 0xac, 0x91, 0xb7, 0xfa, 0xac, 0x14, 0xfd, 0xfb, 0x25,
	0x5e, 0xe0, 0x21, 0x3a, 0x80, 0xc3, 0x85, 0x98, 0x9c, 0xc9, 0xd1, 0x9c, 0xbd, 0x88, 0x09, 0x5b,
	0xa0, 0x36, 0xa9, 0xa5, 0x24, 0xdb, 0x2d, 0x68, 0x45, 0x3d, 0x2c, 0x19, 0xda, 0x85, 0xba, 0x13,
	0x92, 0x5b, 0xc7, 0x64, 0x99, 0x44, 0x29, 0xc9, 0xa2, 0x62, 0x09, 0xd0, 0x73, 0x88, 0xad, 0x98,
	0x2a, 0xe6, 0x66, 0x86, 0x8f, 0x4c, 0xf0, 0x95, 0xec, 0xa4, 0x24, 0xab, 0x17, 0xad, 0x6f, 0xa2,
	0xf2, 0xdb, 0x63, 0x40, 0x71, 0x08, 0x5b, 0x6a, 0x65, 0xf9, 0xaa, 0x00, 0x59, 0x17, 0xb8, 0x00,
	0x8a, 0x05, 0xc2, 0x8e, 0xb7, 0x5b, 0x2f, 0x62, 0xa4, 0x10, 0x88, 0xde, 0x27, 0x81, 0xe4, 0x5a,
	0xab, 0x67, 0x61, 0x50, 0x88, 0xbf, 0xf4, 0x75, 0x05, 0xb1, 0x64, 0xd6, 0x71, 0x83, 0xea, 0xf2,
	0xf2, 0x8d, 0xbc, 0xed, 0x37, 0x87, 0x9e, 0x45, 0x62, 0x2d, 0xb9, 0x86, 0xfc, 0x67, 0x85, 0x6f,
	0x04, 0x4e, 0x7e, 0xc8, 0x57, 0x55, 0x39, 0x00, 0x40, 0x2e, 0x43, 0xbe, 0x03, 0xef, 0x12, 0x0d,
	0xa3, 0x91, 0x55, 0x67, 0xb5, 0xdf, 0x75, 0x1f, 0x6d, 0xe9, 0x3e, 0x7f, 0x27, 0xb0, 0x1f, 0x6e,
	0x7b, 0xc7, 0xcd, 0x5c, 0x8c, 0x39, 0xbd, 0x81, 0xf6, 0xe2, 0xe0, 0xa8, 0xdc, 0xc0, 0xd3, 0x23,
	0x6f, 0x6a, 0xe3, 0x8b, 0xee, 0x1c, 0x6f, 0xe0, 0x55, 0xb2, 0x47, 0xe8, 0x56, 0xb1, 0xd1, 0x63,
	0xa8, 0xe2, 0x53, 0xbf, 0xb8, 0xed, 0xf2, 0x9d, 0xb3, 0x6d, 0x74, 0x78, 0xfe, 0x69, 0xcf, 0xff,
	0x66, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0xc9, 0xbd, 0xe1, 0x89, 0x03, 0x00, 0x00,
}
