// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_KEYCHAIN          TransactionType = 0
	TransactionType_ID                TransactionType = 1
	TransactionType_CONTRACT_CREATION TransactionType = 2
)

var TransactionType_name = map[int32]string{
	0: "KEYCHAIN",
	1: "ID",
	2: "CONTRACT_CREATION",
}
var TransactionType_value = map[string]int32{
	"KEYCHAIN":          0,
	"ID":                1,
	"CONTRACT_CREATION": 2,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{0}
}

type TransactionStatus int32

const (
	TransactionStatus_UNKNOWN     TransactionStatus = 0
	TransactionStatus_IN_PROGRESS TransactionStatus = 1
	TransactionStatus_SUCCESS     TransactionStatus = 2
	TransactionStatus_FAILURE     TransactionStatus = 3
)

var TransactionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "IN_PROGRESS",
	2: "SUCCESS",
	3: "FAILURE",
}
var TransactionStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"IN_PROGRESS": 1,
	"SUCCESS":     2,
	"FAILURE":     3,
}

func (x TransactionStatus) String() string {
	return proto.EnumName(TransactionStatus_name, int32(x))
}
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{1}
}

type ValidationStamp_ValidationStatus int32

const (
	ValidationStamp_NO ValidationStamp_ValidationStatus = 0
	ValidationStamp_OK ValidationStamp_ValidationStatus = 1
)

var ValidationStamp_ValidationStatus_name = map[int32]string{
	0: "NO",
	1: "OK",
}
var ValidationStamp_ValidationStatus_value = map[string]int32{
	"NO": 0,
	"OK": 1,
}

func (x ValidationStamp_ValidationStatus) String() string {
	return proto.EnumName(ValidationStamp_ValidationStatus_name, int32(x))
}
func (ValidationStamp_ValidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{17, 0}
}

type GetLastTransactionRequest struct {
	TransactionAddress   []byte          `protobuf:"bytes,1,opt,name=transaction_address,json=transactionAddress,proto3" json:"transaction_address,omitempty"`
	Type                 TransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=api.TransactionType" json:"type,omitempty"`
	Timestamp            int64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte          `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetLastTransactionRequest) Reset()         { *m = GetLastTransactionRequest{} }
func (m *GetLastTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionRequest) ProtoMessage()    {}
func (*GetLastTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{0}
}
func (m *GetLastTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionRequest.Unmarshal(m, b)
}
func (m *GetLastTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionRequest.Merge(dst, src)
}
func (m *GetLastTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionRequest.Size(m)
}
func (m *GetLastTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionRequest proto.InternalMessageInfo

func (m *GetLastTransactionRequest) GetTransactionAddress() []byte {
	if m != nil {
		return m.TransactionAddress
	}
	return nil
}

func (m *GetLastTransactionRequest) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_KEYCHAIN
}

func (m *GetLastTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetLastTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type GetLastTransactionResponse struct {
	Transaction          *MinedTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp            int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte            `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetLastTransactionResponse) Reset()         { *m = GetLastTransactionResponse{} }
func (m *GetLastTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionResponse) ProtoMessage()    {}
func (*GetLastTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{1}
}
func (m *GetLastTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionResponse.Unmarshal(m, b)
}
func (m *GetLastTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionResponse.Merge(dst, src)
}
func (m *GetLastTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionResponse.Size(m)
}
func (m *GetLastTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionResponse proto.InternalMessageInfo

func (m *GetLastTransactionResponse) GetTransaction() *MinedTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *GetLastTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetLastTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type GetTransactionStatusRequest struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte   `protobuf:"bytes,3,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionStatusRequest) Reset()         { *m = GetTransactionStatusRequest{} }
func (m *GetTransactionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusRequest) ProtoMessage()    {}
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{2}
}
func (m *GetTransactionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusRequest.Unmarshal(m, b)
}
func (m *GetTransactionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusRequest.Merge(dst, src)
}
func (m *GetTransactionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusRequest.Size(m)
}
func (m *GetTransactionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusRequest proto.InternalMessageInfo

func (m *GetTransactionStatusRequest) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *GetTransactionStatusRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTransactionStatusRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type GetTransactionStatusResponse struct {
	Status               TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.TransactionStatus" json:"status,omitempty"`
	Timestamp            int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte            `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetTransactionStatusResponse) Reset()         { *m = GetTransactionStatusResponse{} }
func (m *GetTransactionStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusResponse) ProtoMessage()    {}
func (*GetTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{3}
}
func (m *GetTransactionStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusResponse.Unmarshal(m, b)
}
func (m *GetTransactionStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetTransactionStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusResponse.Merge(dst, src)
}
func (m *GetTransactionStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusResponse.Size(m)
}
func (m *GetTransactionStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusResponse proto.InternalMessageInfo

func (m *GetTransactionStatusResponse) GetStatus() TransactionStatus {
	if m != nil {
		return m.Status
	}
	return TransactionStatus_UNKNOWN
}

func (m *GetTransactionStatusResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTransactionStatusResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type StoreTransactionRequest struct {
	MinedTransaction     *MinedTransaction `protobuf:"bytes,1,opt,name=mined_transaction,json=minedTransaction,proto3" json:"mined_transaction,omitempty"`
	MinimumValidations   int32             `protobuf:"varint,2,opt,name=minimum_validations,json=minimumValidations,proto3" json:"minimum_validations,omitempty"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte            `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StoreTransactionRequest) Reset()         { *m = StoreTransactionRequest{} }
func (m *StoreTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*StoreTransactionRequest) ProtoMessage()    {}
func (*StoreTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{4}
}
func (m *StoreTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreTransactionRequest.Unmarshal(m, b)
}
func (m *StoreTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *StoreTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreTransactionRequest.Merge(dst, src)
}
func (m *StoreTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_StoreTransactionRequest.Size(m)
}
func (m *StoreTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreTransactionRequest proto.InternalMessageInfo

func (m *StoreTransactionRequest) GetMinedTransaction() *MinedTransaction {
	if m != nil {
		return m.MinedTransaction
	}
	return nil
}

func (m *StoreTransactionRequest) GetMinimumValidations() int32 {
	if m != nil {
		return m.MinimumValidations
	}
	return 0
}

func (m *StoreTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StoreTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type StoreTransactionResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreTransactionResponse) Reset()         { *m = StoreTransactionResponse{} }
func (m *StoreTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*StoreTransactionResponse) ProtoMessage()    {}
func (*StoreTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{5}
}
func (m *StoreTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreTransactionResponse.Unmarshal(m, b)
}
func (m *StoreTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *StoreTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreTransactionResponse.Merge(dst, src)
}
func (m *StoreTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_StoreTransactionResponse.Size(m)
}
func (m *StoreTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreTransactionResponse proto.InternalMessageInfo

func (m *StoreTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StoreTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type TimeLockTransactionRequest struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MasterNodePublicKey  []byte   `protobuf:"bytes,3,opt,name=master_node_public_key,json=masterNodePublicKey,proto3" json:"master_node_public_key,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte   `protobuf:"bytes,5,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeLockTransactionRequest) Reset()         { *m = TimeLockTransactionRequest{} }
func (m *TimeLockTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TimeLockTransactionRequest) ProtoMessage()    {}
func (*TimeLockTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{6}
}
func (m *TimeLockTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeLockTransactionRequest.Unmarshal(m, b)
}
func (m *TimeLockTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeLockTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *TimeLockTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeLockTransactionRequest.Merge(dst, src)
}
func (m *TimeLockTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TimeLockTransactionRequest.Size(m)
}
func (m *TimeLockTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeLockTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeLockTransactionRequest proto.InternalMessageInfo

func (m *TimeLockTransactionRequest) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TimeLockTransactionRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *TimeLockTransactionRequest) GetMasterNodePublicKey() []byte {
	if m != nil {
		return m.MasterNodePublicKey
	}
	return nil
}

func (m *TimeLockTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TimeLockTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type TimeLockTransactionResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeLockTransactionResponse) Reset()         { *m = TimeLockTransactionResponse{} }
func (m *TimeLockTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TimeLockTransactionResponse) ProtoMessage()    {}
func (*TimeLockTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{7}
}
func (m *TimeLockTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeLockTransactionResponse.Unmarshal(m, b)
}
func (m *TimeLockTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeLockTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *TimeLockTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeLockTransactionResponse.Merge(dst, src)
}
func (m *TimeLockTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TimeLockTransactionResponse.Size(m)
}
func (m *TimeLockTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeLockTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeLockTransactionResponse proto.InternalMessageInfo

func (m *TimeLockTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TimeLockTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type CoordinateTransactionRequest struct {
	Transaction             *Transaction     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MinimumValidations      int32            `protobuf:"varint,2,opt,name=minimum_validations,json=minimumValidations,proto3" json:"minimum_validations,omitempty"`
	ElectedCoordinatorNodes *ElectedNodeList `protobuf:"bytes,3,opt,name=elected_coordinator_nodes,json=electedCoordinatorNodes,proto3" json:"elected_coordinator_nodes,omitempty"`
	Timestamp               int64            `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest        []byte           `protobuf:"bytes,5,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *CoordinateTransactionRequest) Reset()         { *m = CoordinateTransactionRequest{} }
func (m *CoordinateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CoordinateTransactionRequest) ProtoMessage()    {}
func (*CoordinateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{8}
}
func (m *CoordinateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinateTransactionRequest.Unmarshal(m, b)
}
func (m *CoordinateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinateTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *CoordinateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinateTransactionRequest.Merge(dst, src)
}
func (m *CoordinateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CoordinateTransactionRequest.Size(m)
}
func (m *CoordinateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinateTransactionRequest proto.InternalMessageInfo

func (m *CoordinateTransactionRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *CoordinateTransactionRequest) GetMinimumValidations() int32 {
	if m != nil {
		return m.MinimumValidations
	}
	return 0
}

func (m *CoordinateTransactionRequest) GetElectedCoordinatorNodes() *ElectedNodeList {
	if m != nil {
		return m.ElectedCoordinatorNodes
	}
	return nil
}

func (m *CoordinateTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CoordinateTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type CoordinateTransactionResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoordinateTransactionResponse) Reset()         { *m = CoordinateTransactionResponse{} }
func (m *CoordinateTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*CoordinateTransactionResponse) ProtoMessage()    {}
func (*CoordinateTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{9}
}
func (m *CoordinateTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinateTransactionResponse.Unmarshal(m, b)
}
func (m *CoordinateTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinateTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *CoordinateTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinateTransactionResponse.Merge(dst, src)
}
func (m *CoordinateTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_CoordinateTransactionResponse.Size(m)
}
func (m *CoordinateTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinateTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinateTransactionResponse proto.InternalMessageInfo

func (m *CoordinateTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CoordinateTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type CrossValidateTransactionRequest struct {
	Transaction          *Transaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	CoordinatorStamp     *CoordinatorStamp `protobuf:"bytes,2,opt,name=coordinator_stamp,json=coordinatorStamp,proto3" json:"coordinator_stamp,omitempty"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte            `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CrossValidateTransactionRequest) Reset()         { *m = CrossValidateTransactionRequest{} }
func (m *CrossValidateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CrossValidateTransactionRequest) ProtoMessage()    {}
func (*CrossValidateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{10}
}
func (m *CrossValidateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossValidateTransactionRequest.Unmarshal(m, b)
}
func (m *CrossValidateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossValidateTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *CrossValidateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossValidateTransactionRequest.Merge(dst, src)
}
func (m *CrossValidateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CrossValidateTransactionRequest.Size(m)
}
func (m *CrossValidateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossValidateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrossValidateTransactionRequest proto.InternalMessageInfo

func (m *CrossValidateTransactionRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *CrossValidateTransactionRequest) GetCoordinatorStamp() *CoordinatorStamp {
	if m != nil {
		return m.CoordinatorStamp
	}
	return nil
}

func (m *CrossValidateTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CrossValidateTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type CrossValidateTransactionResponse struct {
	Validation           *ValidationStamp `protobuf:"bytes,1,opt,name=validation,proto3" json:"validation,omitempty"`
	Timestamp            int64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte           `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CrossValidateTransactionResponse) Reset()         { *m = CrossValidateTransactionResponse{} }
func (m *CrossValidateTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*CrossValidateTransactionResponse) ProtoMessage()    {}
func (*CrossValidateTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{11}
}
func (m *CrossValidateTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossValidateTransactionResponse.Unmarshal(m, b)
}
func (m *CrossValidateTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossValidateTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *CrossValidateTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossValidateTransactionResponse.Merge(dst, src)
}
func (m *CrossValidateTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_CrossValidateTransactionResponse.Size(m)
}
func (m *CrossValidateTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossValidateTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrossValidateTransactionResponse proto.InternalMessageInfo

func (m *CrossValidateTransactionResponse) GetValidation() *ValidationStamp {
	if m != nil {
		return m.Validation
	}
	return nil
}

func (m *CrossValidateTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CrossValidateTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type SharedKeyPair struct {
	EncryptedPrivateKey  []byte   `protobuf:"bytes,1,opt,name=encrypted_private_key,json=encryptedPrivateKey,proto3" json:"encrypted_private_key,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedKeyPair) Reset()         { *m = SharedKeyPair{} }
func (m *SharedKeyPair) String() string { return proto.CompactTextString(m) }
func (*SharedKeyPair) ProtoMessage()    {}
func (*SharedKeyPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{12}
}
func (m *SharedKeyPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedKeyPair.Unmarshal(m, b)
}
func (m *SharedKeyPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedKeyPair.Marshal(b, m, deterministic)
}
func (dst *SharedKeyPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedKeyPair.Merge(dst, src)
}
func (m *SharedKeyPair) XXX_Size() int {
	return xxx_messageInfo_SharedKeyPair.Size(m)
}
func (m *SharedKeyPair) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedKeyPair.DiscardUnknown(m)
}

var xxx_messageInfo_SharedKeyPair proto.InternalMessageInfo

func (m *SharedKeyPair) GetEncryptedPrivateKey() []byte {
	if m != nil {
		return m.EncryptedPrivateKey
	}
	return nil
}

func (m *SharedKeyPair) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type Transaction struct {
	Address              []byte              `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Type                 TransactionType     `protobuf:"varint,2,opt,name=type,proto3,enum=api.TransactionType" json:"type,omitempty"`
	Data                 map[string]*any.Any `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            int64               `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PublicKey            []byte              `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature            []byte              `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	OriginSignature      []byte              `protobuf:"bytes,7,opt,name=origin_signature,json=originSignature,proto3" json:"origin_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{13}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_KEYCHAIN
}

func (m *Transaction) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetOriginSignature() []byte {
	if m != nil {
		return m.OriginSignature
	}
	return nil
}

type CoordinatorStamp struct {
	PreviousCrossValidators     [][]byte         `protobuf:"bytes,1,rep,name=previous_cross_validators,json=previousCrossValidators,proto3" json:"previous_cross_validators,omitempty"`
	ProofOfWork                 []byte           `protobuf:"bytes,2,opt,name=proof_of_work,json=proofOfWork,proto3" json:"proof_of_work,omitempty"`
	ValidationStamp             *ValidationStamp `protobuf:"bytes,3,opt,name=validation_stamp,json=validationStamp,proto3" json:"validation_stamp,omitempty"`
	TransactionHash             []byte           `protobuf:"bytes,4,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	ElectedCoordinatorNodes     *ElectedNodeList `protobuf:"bytes,5,opt,name=elected_coordinator_nodes,json=electedCoordinatorNodes,proto3" json:"elected_coordinator_nodes,omitempty"`
	ElectedCrossValidationNodes *ElectedNodeList `protobuf:"bytes,6,opt,name=elected_cross_validation_nodes,json=electedCrossValidationNodes,proto3" json:"elected_cross_validation_nodes,omitempty"`
	ElectedStorageNodes         *ElectedNodeList `protobuf:"bytes,7,opt,name=elected_storage_nodes,json=electedStorageNodes,proto3" json:"elected_storage_nodes,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}         `json:"-"`
	XXX_unrecognized            []byte           `json:"-"`
	XXX_sizecache               int32            `json:"-"`
}

func (m *CoordinatorStamp) Reset()         { *m = CoordinatorStamp{} }
func (m *CoordinatorStamp) String() string { return proto.CompactTextString(m) }
func (*CoordinatorStamp) ProtoMessage()    {}
func (*CoordinatorStamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{14}
}
func (m *CoordinatorStamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinatorStamp.Unmarshal(m, b)
}
func (m *CoordinatorStamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinatorStamp.Marshal(b, m, deterministic)
}
func (dst *CoordinatorStamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinatorStamp.Merge(dst, src)
}
func (m *CoordinatorStamp) XXX_Size() int {
	return xxx_messageInfo_CoordinatorStamp.Size(m)
}
func (m *CoordinatorStamp) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinatorStamp.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinatorStamp proto.InternalMessageInfo

func (m *CoordinatorStamp) GetPreviousCrossValidators() [][]byte {
	if m != nil {
		return m.PreviousCrossValidators
	}
	return nil
}

func (m *CoordinatorStamp) GetProofOfWork() []byte {
	if m != nil {
		return m.ProofOfWork
	}
	return nil
}

func (m *CoordinatorStamp) GetValidationStamp() *ValidationStamp {
	if m != nil {
		return m.ValidationStamp
	}
	return nil
}

func (m *CoordinatorStamp) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *CoordinatorStamp) GetElectedCoordinatorNodes() *ElectedNodeList {
	if m != nil {
		return m.ElectedCoordinatorNodes
	}
	return nil
}

func (m *CoordinatorStamp) GetElectedCrossValidationNodes() *ElectedNodeList {
	if m != nil {
		return m.ElectedCrossValidationNodes
	}
	return nil
}

func (m *CoordinatorStamp) GetElectedStorageNodes() *ElectedNodeList {
	if m != nil {
		return m.ElectedStorageNodes
	}
	return nil
}

type ElectedNodeList struct {
	PublicKey            []byte         `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Nodes                []*ElectedNode `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Signature            []byte         `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ElectedNodeList) Reset()         { *m = ElectedNodeList{} }
func (m *ElectedNodeList) String() string { return proto.CompactTextString(m) }
func (*ElectedNodeList) ProtoMessage()    {}
func (*ElectedNodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{15}
}
func (m *ElectedNodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectedNodeList.Unmarshal(m, b)
}
func (m *ElectedNodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectedNodeList.Marshal(b, m, deterministic)
}
func (dst *ElectedNodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectedNodeList.Merge(dst, src)
}
func (m *ElectedNodeList) XXX_Size() int {
	return xxx_messageInfo_ElectedNodeList.Size(m)
}
func (m *ElectedNodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectedNodeList.DiscardUnknown(m)
}

var xxx_messageInfo_ElectedNodeList proto.InternalMessageInfo

func (m *ElectedNodeList) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ElectedNodeList) GetNodes() []*ElectedNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ElectedNodeList) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ElectedNode struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	IsUnreachable        bool     `protobuf:"varint,2,opt,name=isUnreachable,proto3" json:"isUnreachable,omitempty"`
	IsMaster             bool     `protobuf:"varint,3,opt,name=isMaster,proto3" json:"isMaster,omitempty"`
	PatchNumber          int32    `protobuf:"varint,4,opt,name=patchNumber,proto3" json:"patchNumber,omitempty"`
	IsOK                 bool     `protobuf:"varint,5,opt,name=isOK,proto3" json:"isOK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElectedNode) Reset()         { *m = ElectedNode{} }
func (m *ElectedNode) String() string { return proto.CompactTextString(m) }
func (*ElectedNode) ProtoMessage()    {}
func (*ElectedNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{16}
}
func (m *ElectedNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectedNode.Unmarshal(m, b)
}
func (m *ElectedNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectedNode.Marshal(b, m, deterministic)
}
func (dst *ElectedNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectedNode.Merge(dst, src)
}
func (m *ElectedNode) XXX_Size() int {
	return xxx_messageInfo_ElectedNode.Size(m)
}
func (m *ElectedNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectedNode.DiscardUnknown(m)
}

var xxx_messageInfo_ElectedNode proto.InternalMessageInfo

func (m *ElectedNode) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ElectedNode) GetIsUnreachable() bool {
	if m != nil {
		return m.IsUnreachable
	}
	return false
}

func (m *ElectedNode) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *ElectedNode) GetPatchNumber() int32 {
	if m != nil {
		return m.PatchNumber
	}
	return 0
}

func (m *ElectedNode) GetIsOK() bool {
	if m != nil {
		return m.IsOK
	}
	return false
}

type ValidationStamp struct {
	PublicKey            []byte                           `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               ValidationStamp_ValidationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.ValidationStamp_ValidationStatus" json:"status,omitempty"`
	Timestamp            int64                            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            []byte                           `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ValidationStamp) Reset()         { *m = ValidationStamp{} }
func (m *ValidationStamp) String() string { return proto.CompactTextString(m) }
func (*ValidationStamp) ProtoMessage()    {}
func (*ValidationStamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{17}
}
func (m *ValidationStamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationStamp.Unmarshal(m, b)
}
func (m *ValidationStamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationStamp.Marshal(b, m, deterministic)
}
func (dst *ValidationStamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationStamp.Merge(dst, src)
}
func (m *ValidationStamp) XXX_Size() int {
	return xxx_messageInfo_ValidationStamp.Size(m)
}
func (m *ValidationStamp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationStamp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationStamp proto.InternalMessageInfo

func (m *ValidationStamp) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ValidationStamp) GetStatus() ValidationStamp_ValidationStatus {
	if m != nil {
		return m.Status
	}
	return ValidationStamp_NO
}

func (m *ValidationStamp) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ValidationStamp) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MinedTransaction struct {
	Transaction          *Transaction       `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	CoordinatorStamp     *CoordinatorStamp  `protobuf:"bytes,2,opt,name=coordinator_stamp,json=coordinatorStamp,proto3" json:"coordinator_stamp,omitempty"`
	CrossValidations     []*ValidationStamp `protobuf:"bytes,3,rep,name=cross_validations,json=crossValidations,proto3" json:"cross_validations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MinedTransaction) Reset()         { *m = MinedTransaction{} }
func (m *MinedTransaction) String() string { return proto.CompactTextString(m) }
func (*MinedTransaction) ProtoMessage()    {}
func (*MinedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_5db046b021944f95, []int{18}
}
func (m *MinedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedTransaction.Unmarshal(m, b)
}
func (m *MinedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedTransaction.Marshal(b, m, deterministic)
}
func (dst *MinedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedTransaction.Merge(dst, src)
}
func (m *MinedTransaction) XXX_Size() int {
	return xxx_messageInfo_MinedTransaction.Size(m)
}
func (m *MinedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MinedTransaction proto.InternalMessageInfo

func (m *MinedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *MinedTransaction) GetCoordinatorStamp() *CoordinatorStamp {
	if m != nil {
		return m.CoordinatorStamp
	}
	return nil
}

func (m *MinedTransaction) GetCrossValidations() []*ValidationStamp {
	if m != nil {
		return m.CrossValidations
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLastTransactionRequest)(nil), "api.GetLastTransactionRequest")
	proto.RegisterType((*GetLastTransactionResponse)(nil), "api.GetLastTransactionResponse")
	proto.RegisterType((*GetTransactionStatusRequest)(nil), "api.GetTransactionStatusRequest")
	proto.RegisterType((*GetTransactionStatusResponse)(nil), "api.GetTransactionStatusResponse")
	proto.RegisterType((*StoreTransactionRequest)(nil), "api.StoreTransactionRequest")
	proto.RegisterType((*StoreTransactionResponse)(nil), "api.StoreTransactionResponse")
	proto.RegisterType((*TimeLockTransactionRequest)(nil), "api.TimeLockTransactionRequest")
	proto.RegisterType((*TimeLockTransactionResponse)(nil), "api.TimeLockTransactionResponse")
	proto.RegisterType((*CoordinateTransactionRequest)(nil), "api.CoordinateTransactionRequest")
	proto.RegisterType((*CoordinateTransactionResponse)(nil), "api.CoordinateTransactionResponse")
	proto.RegisterType((*CrossValidateTransactionRequest)(nil), "api.CrossValidateTransactionRequest")
	proto.RegisterType((*CrossValidateTransactionResponse)(nil), "api.CrossValidateTransactionResponse")
	proto.RegisterType((*SharedKeyPair)(nil), "api.SharedKeyPair")
	proto.RegisterType((*Transaction)(nil), "api.Transaction")
	proto.RegisterMapType((map[string]*any.Any)(nil), "api.Transaction.DataEntry")
	proto.RegisterType((*CoordinatorStamp)(nil), "api.CoordinatorStamp")
	proto.RegisterType((*ElectedNodeList)(nil), "api.ElectedNodeList")
	proto.RegisterType((*ElectedNode)(nil), "api.ElectedNode")
	proto.RegisterType((*ValidationStamp)(nil), "api.ValidationStamp")
	proto.RegisterType((*MinedTransaction)(nil), "api.MinedTransaction")
	proto.RegisterEnum("api.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterEnum("api.TransactionStatus", TransactionStatus_name, TransactionStatus_value)
	proto.RegisterEnum("api.ValidationStamp_ValidationStatus", ValidationStamp_ValidationStatus_name, ValidationStamp_ValidationStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResponse, error)
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error)
	StoreTransaction(ctx context.Context, in *StoreTransactionRequest, opts ...grpc.CallOption) (*StoreTransactionResponse, error)
	TimeLockTransaction(ctx context.Context, in *TimeLockTransactionRequest, opts ...grpc.CallOption) (*TimeLockTransactionResponse, error)
	CoordinateTransaction(ctx context.Context, in *CoordinateTransactionRequest, opts ...grpc.CallOption) (*CoordinateTransactionResponse, error)
	CrossValidateTransaction(ctx context.Context, in *CrossValidateTransactionRequest, opts ...grpc.CallOption) (*CrossValidateTransactionResponse, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResponse, error) {
	out := new(GetLastTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/GetLastTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error) {
	out := new(GetTransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/GetTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) StoreTransaction(ctx context.Context, in *StoreTransactionRequest, opts ...grpc.CallOption) (*StoreTransactionResponse, error) {
	out := new(StoreTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/StoreTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) TimeLockTransaction(ctx context.Context, in *TimeLockTransactionRequest, opts ...grpc.CallOption) (*TimeLockTransactionResponse, error) {
	out := new(TimeLockTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/TimeLockTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CoordinateTransaction(ctx context.Context, in *CoordinateTransactionRequest, opts ...grpc.CallOption) (*CoordinateTransactionResponse, error) {
	out := new(CoordinateTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/CoordinateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CrossValidateTransaction(ctx context.Context, in *CrossValidateTransactionRequest, opts ...grpc.CallOption) (*CrossValidateTransactionResponse, error) {
	out := new(CrossValidateTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/CrossValidateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	GetLastTransaction(context.Context, *GetLastTransactionRequest) (*GetLastTransactionResponse, error)
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*GetTransactionStatusResponse, error)
	StoreTransaction(context.Context, *StoreTransactionRequest) (*StoreTransactionResponse, error)
	TimeLockTransaction(context.Context, *TimeLockTransactionRequest) (*TimeLockTransactionResponse, error)
	CoordinateTransaction(context.Context, *CoordinateTransactionRequest) (*CoordinateTransactionResponse, error)
	CrossValidateTransaction(context.Context, *CrossValidateTransactionRequest) (*CrossValidateTransactionResponse, error)
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_GetLastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetLastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/GetLastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetLastTransaction(ctx, req.(*GetLastTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/GetTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_StoreTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).StoreTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/StoreTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).StoreTransaction(ctx, req.(*StoreTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_TimeLockTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeLockTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).TimeLockTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/TimeLockTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).TimeLockTransaction(ctx, req.(*TimeLockTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CoordinateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CoordinateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/CoordinateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CoordinateTransaction(ctx, req.(*CoordinateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CrossValidateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossValidateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CrossValidateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/CrossValidateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CrossValidateTransaction(ctx, req.(*CrossValidateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastTransaction",
			Handler:    _TransactionService_GetLastTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _TransactionService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "StoreTransaction",
			Handler:    _TransactionService_StoreTransaction_Handler,
		},
		{
			MethodName: "TimeLockTransaction",
			Handler:    _TransactionService_TimeLockTransaction_Handler,
		},
		{
			MethodName: "CoordinateTransaction",
			Handler:    _TransactionService_CoordinateTransaction_Handler,
		},
		{
			MethodName: "CrossValidateTransaction",
			Handler:    _TransactionService_CrossValidateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_5db046b021944f95) }

var fileDescriptor_transaction_5db046b021944f95 = []byte{
	// 1308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdf, 0x6e, 0x1b, 0xc5,
	0x17, 0xfe, 0xad, 0xff, 0xe4, 0xcf, 0x71, 0xda, 0xac, 0x27, 0x4d, 0xeb, 0xb8, 0x69, 0xeb, 0xae,
	0xda, 0x9f, 0x42, 0x11, 0xae, 0xe4, 0x22, 0x81, 0x2a, 0x01, 0x72, 0xdd, 0xd0, 0x46, 0x4e, 0xec,
	0x68, 0x9d, 0x50, 0x2a, 0x24, 0x56, 0xe3, 0xf5, 0xc4, 0x5e, 0x62, 0xef, 0x2c, 0x33, 0x6b, 0x23,
	0x3f, 0x07, 0x97, 0xdc, 0x20, 0x04, 0x6f, 0xc1, 0x0d, 0x0f, 0x80, 0xb8, 0x02, 0x89, 0x4b, 0x24,
	0x1e, 0x04, 0xed, 0xcc, 0xae, 0xbd, 0xbb, 0xd9, 0x75, 0x52, 0xe4, 0x8a, 0x2b, 0x7b, 0xcf, 0x39,
	0x73, 0xe6, 0x9c, 0x6f, 0xbe, 0xf9, 0x66, 0x06, 0x8a, 0x2e, 0xc3, 0x36, 0xc7, 0xa6, 0x6b, 0x51,
	0xbb, 0xea, 0x30, 0xea, 0x52, 0x94, 0xc5, 0x8e, 0x55, 0xde, 0xe9, 0x53, 0xda, 0x1f, 0x92, 0xc7,
	0xc2, 0xd4, 0x1d, 0x9f, 0x3d, 0xc6, 0xf6, 0x54, 0xfa, 0xb5, 0x5f, 0x14, 0xd8, 0x79, 0x41, 0xdc,
	0x43, 0xcc, 0xdd, 0x93, 0xf9, 0x60, 0x9d, 0x7c, 0x3d, 0x26, 0xdc, 0x45, 0x8f, 0x61, 0x2b, 0x94,
	0xd2, 0xc0, 0xbd, 0x1e, 0x23, 0x9c, 0x97, 0x94, 0x8a, 0xb2, 0xb7, 0xa1, 0xa3, 0x90, 0xab, 0x2e,
	0x3d, 0x68, 0x0f, 0x72, 0xee, 0xd4, 0x21, 0xa5, 0x4c, 0x45, 0xd9, 0xbb, 0x5e, 0xbb, 0x51, 0xc5,
	0x8e, 0x55, 0x0d, 0xe5, 0x3d, 0x99, 0x3a, 0x44, 0x17, 0x11, 0x68, 0x17, 0xd6, 0x5d, 0x6b, 0x44,
	0xb8, 0x8b, 0x47, 0x4e, 0x29, 0x5b, 0x51, 0xf6, 0xb2, 0xfa, 0xdc, 0x80, 0xde, 0x85, 0x22, 0xb7,
	0xfa, 0x36, 0x76, 0xc7, 0x8c, 0x18, 0x4c, 0x56, 0x53, 0xca, 0x89, 0x69, 0xd5, 0x99, 0xc3, 0xaf,
	0x52, 0xfb, 0x41, 0x81, 0x72, 0x52, 0x0f, 0xdc, 0xa1, 0x36, 0x27, 0xe8, 0x03, 0x28, 0x84, 0x2a,
	0x15, 0xc5, 0x17, 0x6a, 0xdb, 0xa2, 0xb4, 0x23, 0xcb, 0x26, 0xbd, 0xf0, 0x98, 0x70, 0x64, 0xb4,
	0xc4, 0x4c, 0xbc, 0xc4, 0xf7, 0x00, 0x85, 0x4b, 0x94, 0x93, 0x89, 0x4e, 0x36, 0xf4, 0x62, 0xa8,
	0x46, 0xe9, 0xd0, 0xbe, 0x55, 0xe0, 0xf6, 0x0b, 0x12, 0x2e, 0xb0, 0xe3, 0x62, 0x77, 0xcc, 0x03,
	0xa8, 0xdf, 0x01, 0x35, 0x0c, 0xf5, 0x00, 0xf3, 0x81, 0x8f, 0xf3, 0x66, 0xc8, 0xfe, 0x12, 0xf3,
	0xc1, 0x25, 0x75, 0x25, 0x42, 0x97, 0x4d, 0x81, 0xee, 0x3b, 0x05, 0x76, 0x93, 0xab, 0xf2, 0xc1,
	0xab, 0xc2, 0x0a, 0x17, 0x16, 0x51, 0xcc, 0xf5, 0xda, 0xcd, 0xf8, 0x92, 0xfa, 0xf1, 0x7e, 0xd4,
	0x72, 0x31, 0xfb, 0x53, 0x81, 0x5b, 0x1d, 0x97, 0x32, 0x92, 0x40, 0xcd, 0x67, 0x50, 0x1c, 0x79,
	0xab, 0x67, 0x5c, 0x79, 0x6d, 0xd5, 0x51, 0xcc, 0xe2, 0xd1, 0x7b, 0x64, 0xd9, 0xd6, 0x68, 0x3c,
	0x32, 0x26, 0x78, 0x68, 0xf5, 0xb0, 0x67, 0xe5, 0xa2, 0xec, 0xbc, 0x8e, 0x7c, 0xd7, 0x67, 0x73,
	0xcf, 0x32, 0x49, 0xdb, 0x87, 0xd2, 0xc5, 0xd6, 0x7c, 0xd0, 0x23, 0xd3, 0x28, 0x57, 0x03, 0x31,
	0x93, 0x06, 0xe2, 0x5f, 0x0a, 0x94, 0x4f, 0xac, 0x11, 0x39, 0xa4, 0xe6, 0x79, 0x02, 0x8e, 0x6f,
	0xc0, 0xbb, 0x12, 0xac, 0x06, 0x0a, 0x20, 0x67, 0x0b, 0x3e, 0xd1, 0x13, 0xb8, 0x39, 0xc2, 0xdc,
	0x25, 0xcc, 0xb0, 0x69, 0x8f, 0x18, 0xce, 0xb8, 0x3b, 0xb4, 0x4c, 0xe3, 0x9c, 0x4c, 0xfd, 0xb5,
	0xdd, 0x92, 0xde, 0x16, 0xed, 0x91, 0x63, 0xe1, 0x6b, 0x92, 0x69, 0xb4, 0xcb, 0xdc, 0x95, 0xc0,
	0xcc, 0xa7, 0x80, 0xf9, 0x15, 0xdc, 0x4e, 0x6c, 0xf1, 0x6d, 0xe0, 0xf9, 0x7d, 0x06, 0x76, 0x1b,
	0x94, 0xb2, 0x9e, 0x65, 0x63, 0x37, 0x89, 0x99, 0xb5, 0x24, 0xbd, 0x51, 0xe3, 0xfb, 0x26, 0x2a,
	0x35, 0x6f, 0xcc, 0xc4, 0x63, 0xd8, 0x21, 0x43, 0x62, 0xba, 0xa4, 0x67, 0x98, 0x41, 0x31, 0x54,
	0xc2, 0xcf, 0x05, 0xe8, 0x05, 0x5f, 0x7d, 0xf7, 0x65, 0x94, 0x07, 0xfd, 0xa1, 0xc5, 0x5d, 0xfd,
	0x96, 0x3f, 0xac, 0x31, 0x1f, 0xe5, 0xf9, 0xf8, 0x32, 0x97, 0x63, 0x08, 0x77, 0x52, 0x10, 0x7a,
	0x1b, 0x0b, 0xf2, 0xb7, 0x02, 0xf7, 0x1a, 0x8c, 0x72, 0xee, 0xe3, 0xb3, 0xac, 0x35, 0x79, 0x06,
	0xc5, 0x30, 0xb4, 0x73, 0x49, 0x0b, 0x14, 0x26, 0x04, 0x61, 0xc7, 0x73, 0xea, 0xaa, 0x19, 0xb3,
	0x2c, 0x53, 0x30, 0x7e, 0x52, 0xa0, 0x92, 0xde, 0xa6, 0x0f, 0xec, 0xfb, 0x00, 0x73, 0xfe, 0xf8,
	0x6d, 0x4a, 0x1e, 0xcc, 0xc9, 0x23, 0x6b, 0x0d, 0xc5, 0x2d, 0x57, 0xb4, 0xbb, 0x70, 0xad, 0x33,
	0xc0, 0x8c, 0xf4, 0x9a, 0x64, 0x7a, 0x8c, 0x2d, 0x86, 0x6a, 0xb0, 0x4d, 0x6c, 0x93, 0x4d, 0x1d,
	0x8f, 0xac, 0x0e, 0xb3, 0x26, 0xd8, 0x25, 0x42, 0x1b, 0xa4, 0xcc, 0x6c, 0xcd, 0x9c, 0xc7, 0xd2,
	0xe7, 0x69, 0xc3, 0x1d, 0x80, 0x90, 0x88, 0xc8, 0xa5, 0x5f, 0x77, 0x02, 0xe9, 0xd0, 0xfe, 0xc8,
	0x40, 0x21, 0x2c, 0xe4, 0x21, 0x65, 0x52, 0xa2, 0xca, 0x74, 0xf5, 0x0b, 0x49, 0x15, 0x72, 0x3d,
	0xec, 0xe2, 0x52, 0xb6, 0x92, 0xdd, 0x2b, 0xd4, 0xca, 0xf1, 0xc8, 0xea, 0x73, 0xec, 0xe2, 0x7d,
	0xdb, 0x65, 0x53, 0x5d, 0xc4, 0x5d, 0xb2, 0x5f, 0xa2, 0x0d, 0xe4, 0x63, 0x0d, 0x78, 0x83, 0x67,
	0xc8, 0x95, 0x56, 0xa4, 0x77, 0x66, 0xf0, 0x34, 0x99, 0x32, 0xab, 0x6f, 0xd9, 0xc6, 0x3c, 0x68,
	0x55, 0x6a, 0xb2, 0xb4, 0x77, 0x02, 0x73, 0xf9, 0x08, 0xd6, 0x67, 0x85, 0x21, 0x15, 0xb2, 0x01,
	0xae, 0xeb, 0xba, 0xf7, 0x17, 0x3d, 0x82, 0xfc, 0x04, 0x0f, 0xc7, 0xc4, 0xe7, 0xed, 0x8d, 0xaa,
	0xbc, 0x09, 0x56, 0x83, 0x9b, 0x60, 0xb5, 0x6e, 0x4f, 0x75, 0x19, 0xf2, 0x34, 0xf3, 0xa1, 0xa2,
	0xfd, 0x9e, 0x05, 0x35, 0x4e, 0x6b, 0xf4, 0x14, 0x76, 0x1c, 0x46, 0x26, 0x16, 0x1d, 0x73, 0xc3,
	0xf4, 0x18, 0x18, 0x68, 0x14, 0x65, 0x1e, 0xde, 0xd9, 0xbd, 0x0d, 0xfd, 0x56, 0x10, 0x10, 0x66,
	0x28, 0x65, 0x1c, 0x69, 0x70, 0xcd, 0x61, 0x94, 0x9e, 0x19, 0xf4, 0xcc, 0xf8, 0x86, 0xb2, 0x73,
	0x7f, 0x2d, 0x0b, 0xc2, 0xd8, 0x3e, 0x7b, 0x45, 0xd9, 0x39, 0xfa, 0x04, 0xd4, 0x39, 0x19, 0x8d,
	0xf9, 0x5e, 0x49, 0xa3, 0xee, 0xe6, 0x24, 0x6a, 0x48, 0x3c, 0xc3, 0x72, 0xc9, 0x67, 0xd8, 0x42,
	0xdd, 0xcc, 0xff, 0x1b, 0xdd, 0x7c, 0x0d, 0x77, 0x67, 0x19, 0xc3, 0xe0, 0x78, 0x95, 0xc8, 0xb4,
	0x2b, 0x0b, 0xd2, 0xde, 0x0e, 0xd2, 0x86, 0x70, 0xb3, 0xa8, 0x2d, 0x53, 0xbf, 0x84, 0xed, 0x20,
	0x35, 0x77, 0x29, 0xc3, 0x7d, 0xe2, 0x67, 0x5c, 0x5d, 0x90, 0x71, 0xcb, 0x1f, 0xd2, 0x91, 0x23,
	0x44, 0x26, 0x6d, 0x02, 0x9b, 0xb1, 0xb8, 0x18, 0x43, 0x95, 0x38, 0x43, 0xff, 0x0f, 0x79, 0x39,
	0x57, 0x46, 0xec, 0x07, 0x35, 0x3e, 0x97, 0x2e, 0xdd, 0x51, 0x26, 0x67, 0x63, 0x4c, 0xd6, 0x7e,
	0x54, 0xa0, 0x10, 0x1a, 0x74, 0xd9, 0xa4, 0x0f, 0xe0, 0x9a, 0xc5, 0x4f, 0x6d, 0x46, 0xb0, 0x39,
	0xc0, 0xdd, 0xa1, 0xa4, 0xed, 0x9a, 0x1e, 0x35, 0xa2, 0x32, 0xac, 0x59, 0xfc, 0x48, 0xdc, 0x28,
	0xc4, 0x8c, 0x6b, 0xfa, 0xec, 0x1b, 0x55, 0xa0, 0xe0, 0x60, 0xd7, 0x1c, 0xb4, 0xc6, 0xa3, 0x2e,
	0x61, 0x82, 0x05, 0x79, 0x3d, 0x6c, 0x42, 0x08, 0x72, 0x16, 0x6f, 0x37, 0xc5, 0x62, 0xaf, 0xe9,
	0xe2, 0xbf, 0xf6, 0x9b, 0x02, 0x9b, 0x31, 0x96, 0x5d, 0x56, 0xea, 0x47, 0xb3, 0x8b, 0xb1, 0x94,
	0x96, 0x87, 0x49, 0x54, 0x8d, 0x7e, 0xa7, 0xde, 0x93, 0x2f, 0x1c, 0x0c, 0x11, 0x50, 0x73, 0x71,
	0x50, 0x35, 0x50, 0xe3, 0x79, 0xd1, 0x0a, 0x64, 0x5a, 0x6d, 0xf5, 0x7f, 0xde, 0x6f, 0xbb, 0xa9,
	0x2a, 0xda, 0xaf, 0x0a, 0xa8, 0xf1, 0x1b, 0xf0, 0x7f, 0x76, 0x0a, 0xd6, 0xa1, 0x18, 0xdf, 0x1a,
	0xdc, 0xd7, 0xd9, 0xe4, 0x1d, 0xae, 0x9a, 0xd1, 0xed, 0xc0, 0x1f, 0x7d, 0x0c, 0x9b, 0x31, 0xd9,
	0x46, 0x1b, 0xb0, 0xd6, 0xdc, 0x7f, 0xdd, 0x78, 0x59, 0x3f, 0x68, 0xc9, 0xc6, 0x0f, 0x9e, 0xab,
	0x0a, 0xda, 0x86, 0x62, 0xa3, 0xdd, 0x3a, 0xd1, 0xeb, 0x8d, 0x13, 0xa3, 0xa1, 0xef, 0xd7, 0x4f,
	0x0e, 0xda, 0x2d, 0x35, 0xf3, 0xa8, 0x09, 0xc5, 0x0b, 0x8f, 0x16, 0x54, 0x80, 0xd5, 0xd3, 0x56,
	0xb3, 0xd5, 0x7e, 0xe5, 0x25, 0xd8, 0x84, 0xc2, 0x41, 0xcb, 0x38, 0xd6, 0xdb, 0x2f, 0xf4, 0xfd,
	0x4e, 0x47, 0x55, 0x3c, 0x6f, 0xe7, 0xb4, 0xd1, 0xf0, 0x3e, 0x32, 0xde, 0xc7, 0xa7, 0xf5, 0x83,
	0xc3, 0x53, 0x7d, 0x5f, 0xcd, 0xd6, 0x7e, 0xce, 0x01, 0x0a, 0x67, 0x23, 0x6c, 0x62, 0x99, 0x04,
	0x9d, 0x02, 0xba, 0xf8, 0x0c, 0x45, 0x77, 0x45, 0x87, 0xa9, 0x6f, 0xec, 0xf2, 0xbd, 0x54, 0xbf,
	0x7f, 0xa6, 0x7f, 0x01, 0x37, 0x92, 0x9e, 0x68, 0xa8, 0x12, 0x0c, 0x4c, 0x7b, 0x53, 0x96, 0xef,
	0x2f, 0x88, 0xf0, 0x93, 0xb7, 0x41, 0x8d, 0x3f, 0x43, 0xd0, 0xae, 0x18, 0x96, 0xf2, 0xf0, 0x2a,
	0xdf, 0x49, 0xf1, 0xfa, 0x09, 0x3f, 0x87, 0xad, 0x84, 0xab, 0x38, 0x92, 0x5d, 0xa6, 0xbf, 0x43,
	0xca, 0x95, 0xf4, 0x00, 0x3f, 0xf3, 0x97, 0xb0, 0x9d, 0x78, 0xab, 0x44, 0xf7, 0xa3, 0x3c, 0x4c,
	0x2a, 0x5a, 0x5b, 0x14, 0xe2, 0xe7, 0xef, 0x43, 0x29, 0xed, 0x7e, 0x85, 0x1e, 0xc8, 0xf1, 0x8b,
	0x6f, 0x99, 0xe5, 0x87, 0x97, 0x44, 0xc9, 0x89, 0xba, 0x2b, 0xe2, 0xf4, 0x7d, 0xf2, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x0f, 0xc0, 0x4b, 0xaf, 0x11, 0x00, 0x00,
}
