// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_KEYCHAIN          TransactionType = 0
	TransactionType_ID                TransactionType = 1
	TransactionType_CONTRACT_CREATION TransactionType = 2
)

var TransactionType_name = map[int32]string{
	0: "KEYCHAIN",
	1: "ID",
	2: "CONTRACT_CREATION",
}
var TransactionType_value = map[string]int32{
	"KEYCHAIN":          0,
	"ID":                1,
	"CONTRACT_CREATION": 2,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{0}
}

type TransactionStatus int32

const (
	TransactionStatus_UNKNOWN     TransactionStatus = 0
	TransactionStatus_IN_PROGRESS TransactionStatus = 1
	TransactionStatus_SUCCESS     TransactionStatus = 2
	TransactionStatus_FAILURE     TransactionStatus = 3
)

var TransactionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "IN_PROGRESS",
	2: "SUCCESS",
	3: "FAILURE",
}
var TransactionStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"IN_PROGRESS": 1,
	"SUCCESS":     2,
	"FAILURE":     3,
}

func (x TransactionStatus) String() string {
	return proto.EnumName(TransactionStatus_name, int32(x))
}
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{1}
}

type Validation_ValidationStatus int32

const (
	Validation_NO Validation_ValidationStatus = 0
	Validation_OK Validation_ValidationStatus = 1
)

var Validation_ValidationStatus_name = map[int32]string{
	0: "NO",
	1: "OK",
}
var Validation_ValidationStatus_value = map[string]int32{
	"NO": 0,
	"OK": 1,
}

func (x Validation_ValidationStatus) String() string {
	return proto.EnumName(Validation_ValidationStatus_name, int32(x))
}
func (Validation_ValidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{16, 0}
}

type GetLastTransactionRequest struct {
	TransactionAddress   []byte          `protobuf:"bytes,1,opt,name=transaction_address,json=transactionAddress,proto3" json:"transaction_address,omitempty"`
	Type                 TransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=api.TransactionType" json:"type,omitempty"`
	Timestamp            int64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte          `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetLastTransactionRequest) Reset()         { *m = GetLastTransactionRequest{} }
func (m *GetLastTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionRequest) ProtoMessage()    {}
func (*GetLastTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{0}
}
func (m *GetLastTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionRequest.Unmarshal(m, b)
}
func (m *GetLastTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionRequest.Merge(dst, src)
}
func (m *GetLastTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionRequest.Size(m)
}
func (m *GetLastTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionRequest proto.InternalMessageInfo

func (m *GetLastTransactionRequest) GetTransactionAddress() []byte {
	if m != nil {
		return m.TransactionAddress
	}
	return nil
}

func (m *GetLastTransactionRequest) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_KEYCHAIN
}

func (m *GetLastTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetLastTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type GetLastTransactionResponse struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp            int64        `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte       `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetLastTransactionResponse) Reset()         { *m = GetLastTransactionResponse{} }
func (m *GetLastTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionResponse) ProtoMessage()    {}
func (*GetLastTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{1}
}
func (m *GetLastTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionResponse.Unmarshal(m, b)
}
func (m *GetLastTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionResponse.Merge(dst, src)
}
func (m *GetLastTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionResponse.Size(m)
}
func (m *GetLastTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionResponse proto.InternalMessageInfo

func (m *GetLastTransactionResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *GetLastTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetLastTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type GetTransactionStatusRequest struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte   `protobuf:"bytes,3,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionStatusRequest) Reset()         { *m = GetTransactionStatusRequest{} }
func (m *GetTransactionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusRequest) ProtoMessage()    {}
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{2}
}
func (m *GetTransactionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusRequest.Unmarshal(m, b)
}
func (m *GetTransactionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusRequest.Merge(dst, src)
}
func (m *GetTransactionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusRequest.Size(m)
}
func (m *GetTransactionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusRequest proto.InternalMessageInfo

func (m *GetTransactionStatusRequest) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *GetTransactionStatusRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTransactionStatusRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type GetTransactionStatusResponse struct {
	Status               TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.TransactionStatus" json:"status,omitempty"`
	Timestamp            int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte            `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetTransactionStatusResponse) Reset()         { *m = GetTransactionStatusResponse{} }
func (m *GetTransactionStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusResponse) ProtoMessage()    {}
func (*GetTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{3}
}
func (m *GetTransactionStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusResponse.Unmarshal(m, b)
}
func (m *GetTransactionStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetTransactionStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusResponse.Merge(dst, src)
}
func (m *GetTransactionStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusResponse.Size(m)
}
func (m *GetTransactionStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusResponse proto.InternalMessageInfo

func (m *GetTransactionStatusResponse) GetStatus() TransactionStatus {
	if m != nil {
		return m.Status
	}
	return TransactionStatus_UNKNOWN
}

func (m *GetTransactionStatusResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTransactionStatusResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type StoreTransactionRequest struct {
	MinedTransaction     *MinedTransaction `protobuf:"bytes,1,opt,name=mined_transaction,json=minedTransaction,proto3" json:"mined_transaction,omitempty"`
	MinimumValidations   int32             `protobuf:"varint,2,opt,name=minimum_validations,json=minimumValidations,proto3" json:"minimum_validations,omitempty"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte            `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StoreTransactionRequest) Reset()         { *m = StoreTransactionRequest{} }
func (m *StoreTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*StoreTransactionRequest) ProtoMessage()    {}
func (*StoreTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{4}
}
func (m *StoreTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreTransactionRequest.Unmarshal(m, b)
}
func (m *StoreTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *StoreTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreTransactionRequest.Merge(dst, src)
}
func (m *StoreTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_StoreTransactionRequest.Size(m)
}
func (m *StoreTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreTransactionRequest proto.InternalMessageInfo

func (m *StoreTransactionRequest) GetMinedTransaction() *MinedTransaction {
	if m != nil {
		return m.MinedTransaction
	}
	return nil
}

func (m *StoreTransactionRequest) GetMinimumValidations() int32 {
	if m != nil {
		return m.MinimumValidations
	}
	return 0
}

func (m *StoreTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StoreTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type StoreTransactionResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreTransactionResponse) Reset()         { *m = StoreTransactionResponse{} }
func (m *StoreTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*StoreTransactionResponse) ProtoMessage()    {}
func (*StoreTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{5}
}
func (m *StoreTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreTransactionResponse.Unmarshal(m, b)
}
func (m *StoreTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *StoreTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreTransactionResponse.Merge(dst, src)
}
func (m *StoreTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_StoreTransactionResponse.Size(m)
}
func (m *StoreTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreTransactionResponse proto.InternalMessageInfo

func (m *StoreTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StoreTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type TimeLockTransactionRequest struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MasterNodePublicKey  []byte   `protobuf:"bytes,3,opt,name=master_node_public_key,json=masterNodePublicKey,proto3" json:"master_node_public_key,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte   `protobuf:"bytes,5,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeLockTransactionRequest) Reset()         { *m = TimeLockTransactionRequest{} }
func (m *TimeLockTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TimeLockTransactionRequest) ProtoMessage()    {}
func (*TimeLockTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{6}
}
func (m *TimeLockTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeLockTransactionRequest.Unmarshal(m, b)
}
func (m *TimeLockTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeLockTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *TimeLockTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeLockTransactionRequest.Merge(dst, src)
}
func (m *TimeLockTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TimeLockTransactionRequest.Size(m)
}
func (m *TimeLockTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeLockTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeLockTransactionRequest proto.InternalMessageInfo

func (m *TimeLockTransactionRequest) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TimeLockTransactionRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *TimeLockTransactionRequest) GetMasterNodePublicKey() []byte {
	if m != nil {
		return m.MasterNodePublicKey
	}
	return nil
}

func (m *TimeLockTransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TimeLockTransactionRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type TimeLockTransactionResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeLockTransactionResponse) Reset()         { *m = TimeLockTransactionResponse{} }
func (m *TimeLockTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TimeLockTransactionResponse) ProtoMessage()    {}
func (*TimeLockTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{7}
}
func (m *TimeLockTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeLockTransactionResponse.Unmarshal(m, b)
}
func (m *TimeLockTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeLockTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *TimeLockTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeLockTransactionResponse.Merge(dst, src)
}
func (m *TimeLockTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TimeLockTransactionResponse.Size(m)
}
func (m *TimeLockTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeLockTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeLockTransactionResponse proto.InternalMessageInfo

func (m *TimeLockTransactionResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TimeLockTransactionResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type LeadTransactionMiningRequest struct {
	Transaction          *Transaction  `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MinimumValidations   int32         `protobuf:"varint,2,opt,name=minimum_validations,json=minimumValidations,proto3" json:"minimum_validations,omitempty"`
	WelcomeHeaders       []*NodeHeader `protobuf:"bytes,3,rep,name=welcome_headers,json=welcomeHeaders,proto3" json:"welcome_headers,omitempty"`
	Timestamp            int64         `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte        `protobuf:"bytes,5,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LeadTransactionMiningRequest) Reset()         { *m = LeadTransactionMiningRequest{} }
func (m *LeadTransactionMiningRequest) String() string { return proto.CompactTextString(m) }
func (*LeadTransactionMiningRequest) ProtoMessage()    {}
func (*LeadTransactionMiningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{8}
}
func (m *LeadTransactionMiningRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadTransactionMiningRequest.Unmarshal(m, b)
}
func (m *LeadTransactionMiningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadTransactionMiningRequest.Marshal(b, m, deterministic)
}
func (dst *LeadTransactionMiningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadTransactionMiningRequest.Merge(dst, src)
}
func (m *LeadTransactionMiningRequest) XXX_Size() int {
	return xxx_messageInfo_LeadTransactionMiningRequest.Size(m)
}
func (m *LeadTransactionMiningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadTransactionMiningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeadTransactionMiningRequest proto.InternalMessageInfo

func (m *LeadTransactionMiningRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *LeadTransactionMiningRequest) GetMinimumValidations() int32 {
	if m != nil {
		return m.MinimumValidations
	}
	return 0
}

func (m *LeadTransactionMiningRequest) GetWelcomeHeaders() []*NodeHeader {
	if m != nil {
		return m.WelcomeHeaders
	}
	return nil
}

func (m *LeadTransactionMiningRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LeadTransactionMiningRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type LeadTransactionMiningResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte   `protobuf:"bytes,2,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeadTransactionMiningResponse) Reset()         { *m = LeadTransactionMiningResponse{} }
func (m *LeadTransactionMiningResponse) String() string { return proto.CompactTextString(m) }
func (*LeadTransactionMiningResponse) ProtoMessage()    {}
func (*LeadTransactionMiningResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{9}
}
func (m *LeadTransactionMiningResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeadTransactionMiningResponse.Unmarshal(m, b)
}
func (m *LeadTransactionMiningResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeadTransactionMiningResponse.Marshal(b, m, deterministic)
}
func (dst *LeadTransactionMiningResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeadTransactionMiningResponse.Merge(dst, src)
}
func (m *LeadTransactionMiningResponse) XXX_Size() int {
	return xxx_messageInfo_LeadTransactionMiningResponse.Size(m)
}
func (m *LeadTransactionMiningResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeadTransactionMiningResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeadTransactionMiningResponse proto.InternalMessageInfo

func (m *LeadTransactionMiningResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LeadTransactionMiningResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type ConfirmTransactionValidationRequest struct {
	Transaction          *Transaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MasterValidation     *MasterValidation `protobuf:"bytes,2,opt,name=master_validation,json=masterValidation,proto3" json:"master_validation,omitempty"`
	Timestamp            int64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureRequest     []byte            `protobuf:"bytes,4,opt,name=signature_request,json=signatureRequest,proto3" json:"signature_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfirmTransactionValidationRequest) Reset()         { *m = ConfirmTransactionValidationRequest{} }
func (m *ConfirmTransactionValidationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmTransactionValidationRequest) ProtoMessage()    {}
func (*ConfirmTransactionValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{10}
}
func (m *ConfirmTransactionValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmTransactionValidationRequest.Unmarshal(m, b)
}
func (m *ConfirmTransactionValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmTransactionValidationRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmTransactionValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmTransactionValidationRequest.Merge(dst, src)
}
func (m *ConfirmTransactionValidationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmTransactionValidationRequest.Size(m)
}
func (m *ConfirmTransactionValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmTransactionValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmTransactionValidationRequest proto.InternalMessageInfo

func (m *ConfirmTransactionValidationRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ConfirmTransactionValidationRequest) GetMasterValidation() *MasterValidation {
	if m != nil {
		return m.MasterValidation
	}
	return nil
}

func (m *ConfirmTransactionValidationRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConfirmTransactionValidationRequest) GetSignatureRequest() []byte {
	if m != nil {
		return m.SignatureRequest
	}
	return nil
}

type ConfirmTransactionValidationResponse struct {
	Validation           *Validation `protobuf:"bytes,1,opt,name=validation,proto3" json:"validation,omitempty"`
	Timestamp            int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SignatureResponse    []byte      `protobuf:"bytes,3,opt,name=signature_response,json=signatureResponse,proto3" json:"signature_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfirmTransactionValidationResponse) Reset()         { *m = ConfirmTransactionValidationResponse{} }
func (m *ConfirmTransactionValidationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmTransactionValidationResponse) ProtoMessage()    {}
func (*ConfirmTransactionValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{11}
}
func (m *ConfirmTransactionValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmTransactionValidationResponse.Unmarshal(m, b)
}
func (m *ConfirmTransactionValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmTransactionValidationResponse.Marshal(b, m, deterministic)
}
func (dst *ConfirmTransactionValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmTransactionValidationResponse.Merge(dst, src)
}
func (m *ConfirmTransactionValidationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmTransactionValidationResponse.Size(m)
}
func (m *ConfirmTransactionValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmTransactionValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmTransactionValidationResponse proto.InternalMessageInfo

func (m *ConfirmTransactionValidationResponse) GetValidation() *Validation {
	if m != nil {
		return m.Validation
	}
	return nil
}

func (m *ConfirmTransactionValidationResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConfirmTransactionValidationResponse) GetSignatureResponse() []byte {
	if m != nil {
		return m.SignatureResponse
	}
	return nil
}

type SharedKeyPair struct {
	EncryptedPrivateKey  []byte   `protobuf:"bytes,1,opt,name=encrypted_private_key,json=encryptedPrivateKey,proto3" json:"encrypted_private_key,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedKeyPair) Reset()         { *m = SharedKeyPair{} }
func (m *SharedKeyPair) String() string { return proto.CompactTextString(m) }
func (*SharedKeyPair) ProtoMessage()    {}
func (*SharedKeyPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{12}
}
func (m *SharedKeyPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedKeyPair.Unmarshal(m, b)
}
func (m *SharedKeyPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedKeyPair.Marshal(b, m, deterministic)
}
func (dst *SharedKeyPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedKeyPair.Merge(dst, src)
}
func (m *SharedKeyPair) XXX_Size() int {
	return xxx_messageInfo_SharedKeyPair.Size(m)
}
func (m *SharedKeyPair) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedKeyPair.DiscardUnknown(m)
}

var xxx_messageInfo_SharedKeyPair proto.InternalMessageInfo

func (m *SharedKeyPair) GetEncryptedPrivateKey() []byte {
	if m != nil {
		return m.EncryptedPrivateKey
	}
	return nil
}

func (m *SharedKeyPair) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type Transaction struct {
	Address                   []byte            `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Type                      TransactionType   `protobuf:"varint,2,opt,name=type,proto3,enum=api.TransactionType" json:"type,omitempty"`
	Data                      map[string][]byte `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp                 int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PublicKey                 []byte            `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature                 []byte            `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	EmitterSignature          []byte            `protobuf:"bytes,7,opt,name=emitter_signature,json=emitterSignature,proto3" json:"emitter_signature,omitempty"`
	SharedKeysEmitterProposal *SharedKeyPair    `protobuf:"bytes,8,opt,name=shared_keys_emitter_proposal,json=sharedKeysEmitterProposal,proto3" json:"shared_keys_emitter_proposal,omitempty"`
	TransactionHash           []byte            `protobuf:"bytes,9,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}          `json:"-"`
	XXX_unrecognized          []byte            `json:"-"`
	XXX_sizecache             int32             `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{13}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_KEYCHAIN
}

func (m *Transaction) GetData() map[string][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetEmitterSignature() []byte {
	if m != nil {
		return m.EmitterSignature
	}
	return nil
}

func (m *Transaction) GetSharedKeysEmitterProposal() *SharedKeyPair {
	if m != nil {
		return m.SharedKeysEmitterProposal
	}
	return nil
}

func (m *Transaction) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

type MasterValidation struct {
	PreviousValidationNodes [][]byte      `protobuf:"bytes,1,rep,name=previous_validation_nodes,json=previousValidationNodes,proto3" json:"previous_validation_nodes,omitempty"`
	ProofOfWork             []byte        `protobuf:"bytes,2,opt,name=proof_of_work,json=proofOfWork,proto3" json:"proof_of_work,omitempty"`
	PreValidation           *Validation   `protobuf:"bytes,3,opt,name=pre_validation,json=preValidation,proto3" json:"pre_validation,omitempty"`
	WelcomeHeaders          []*NodeHeader `protobuf:"bytes,4,rep,name=welcome_headers,json=welcomeHeaders,proto3" json:"welcome_headers,omitempty"`
	ValidationHeaders       []*NodeHeader `protobuf:"bytes,5,rep,name=validation_headers,json=validationHeaders,proto3" json:"validation_headers,omitempty"`
	StorageHeaders          []*NodeHeader `protobuf:"bytes,6,rep,name=storage_headers,json=storageHeaders,proto3" json:"storage_headers,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *MasterValidation) Reset()         { *m = MasterValidation{} }
func (m *MasterValidation) String() string { return proto.CompactTextString(m) }
func (*MasterValidation) ProtoMessage()    {}
func (*MasterValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{14}
}
func (m *MasterValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterValidation.Unmarshal(m, b)
}
func (m *MasterValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterValidation.Marshal(b, m, deterministic)
}
func (dst *MasterValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterValidation.Merge(dst, src)
}
func (m *MasterValidation) XXX_Size() int {
	return xxx_messageInfo_MasterValidation.Size(m)
}
func (m *MasterValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterValidation.DiscardUnknown(m)
}

var xxx_messageInfo_MasterValidation proto.InternalMessageInfo

func (m *MasterValidation) GetPreviousValidationNodes() [][]byte {
	if m != nil {
		return m.PreviousValidationNodes
	}
	return nil
}

func (m *MasterValidation) GetProofOfWork() []byte {
	if m != nil {
		return m.ProofOfWork
	}
	return nil
}

func (m *MasterValidation) GetPreValidation() *Validation {
	if m != nil {
		return m.PreValidation
	}
	return nil
}

func (m *MasterValidation) GetWelcomeHeaders() []*NodeHeader {
	if m != nil {
		return m.WelcomeHeaders
	}
	return nil
}

func (m *MasterValidation) GetValidationHeaders() []*NodeHeader {
	if m != nil {
		return m.ValidationHeaders
	}
	return nil
}

func (m *MasterValidation) GetStorageHeaders() []*NodeHeader {
	if m != nil {
		return m.StorageHeaders
	}
	return nil
}

type NodeHeader struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	IsUnreachable        bool     `protobuf:"varint,2,opt,name=isUnreachable,proto3" json:"isUnreachable,omitempty"`
	IsMaster             bool     `protobuf:"varint,3,opt,name=isMaster,proto3" json:"isMaster,omitempty"`
	PatchNumber          int32    `protobuf:"varint,4,opt,name=patchNumber,proto3" json:"patchNumber,omitempty"`
	IsOK                 bool     `protobuf:"varint,5,opt,name=isOK,proto3" json:"isOK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeHeader) Reset()         { *m = NodeHeader{} }
func (m *NodeHeader) String() string { return proto.CompactTextString(m) }
func (*NodeHeader) ProtoMessage()    {}
func (*NodeHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{15}
}
func (m *NodeHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeHeader.Unmarshal(m, b)
}
func (m *NodeHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeHeader.Marshal(b, m, deterministic)
}
func (dst *NodeHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeHeader.Merge(dst, src)
}
func (m *NodeHeader) XXX_Size() int {
	return xxx_messageInfo_NodeHeader.Size(m)
}
func (m *NodeHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeHeader.DiscardUnknown(m)
}

var xxx_messageInfo_NodeHeader proto.InternalMessageInfo

func (m *NodeHeader) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *NodeHeader) GetIsUnreachable() bool {
	if m != nil {
		return m.IsUnreachable
	}
	return false
}

func (m *NodeHeader) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *NodeHeader) GetPatchNumber() int32 {
	if m != nil {
		return m.PatchNumber
	}
	return 0
}

func (m *NodeHeader) GetIsOK() bool {
	if m != nil {
		return m.IsOK
	}
	return false
}

type Validation struct {
	PublicKey            []byte                      `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               Validation_ValidationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.Validation_ValidationStatus" json:"status,omitempty"`
	Timestamp            int64                       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            []byte                      `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Validation) Reset()         { *m = Validation{} }
func (m *Validation) String() string { return proto.CompactTextString(m) }
func (*Validation) ProtoMessage()    {}
func (*Validation) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{16}
}
func (m *Validation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validation.Unmarshal(m, b)
}
func (m *Validation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validation.Marshal(b, m, deterministic)
}
func (dst *Validation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validation.Merge(dst, src)
}
func (m *Validation) XXX_Size() int {
	return xxx_messageInfo_Validation.Size(m)
}
func (m *Validation) XXX_DiscardUnknown() {
	xxx_messageInfo_Validation.DiscardUnknown(m)
}

var xxx_messageInfo_Validation proto.InternalMessageInfo

func (m *Validation) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Validation) GetStatus() Validation_ValidationStatus {
	if m != nil {
		return m.Status
	}
	return Validation_NO
}

func (m *Validation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Validation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MinedTransaction struct {
	Transaction          *Transaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MasterValidation     *MasterValidation `protobuf:"bytes,2,opt,name=master_validation,json=masterValidation,proto3" json:"master_validation,omitempty"`
	ConfirmValidations   []*Validation     `protobuf:"bytes,3,rep,name=confirm_validations,json=confirmValidations,proto3" json:"confirm_validations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MinedTransaction) Reset()         { *m = MinedTransaction{} }
func (m *MinedTransaction) String() string { return proto.CompactTextString(m) }
func (*MinedTransaction) ProtoMessage()    {}
func (*MinedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b15a2b3033c4b1c, []int{17}
}
func (m *MinedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedTransaction.Unmarshal(m, b)
}
func (m *MinedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedTransaction.Marshal(b, m, deterministic)
}
func (dst *MinedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedTransaction.Merge(dst, src)
}
func (m *MinedTransaction) XXX_Size() int {
	return xxx_messageInfo_MinedTransaction.Size(m)
}
func (m *MinedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MinedTransaction proto.InternalMessageInfo

func (m *MinedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *MinedTransaction) GetMasterValidation() *MasterValidation {
	if m != nil {
		return m.MasterValidation
	}
	return nil
}

func (m *MinedTransaction) GetConfirmValidations() []*Validation {
	if m != nil {
		return m.ConfirmValidations
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLastTransactionRequest)(nil), "api.GetLastTransactionRequest")
	proto.RegisterType((*GetLastTransactionResponse)(nil), "api.GetLastTransactionResponse")
	proto.RegisterType((*GetTransactionStatusRequest)(nil), "api.GetTransactionStatusRequest")
	proto.RegisterType((*GetTransactionStatusResponse)(nil), "api.GetTransactionStatusResponse")
	proto.RegisterType((*StoreTransactionRequest)(nil), "api.StoreTransactionRequest")
	proto.RegisterType((*StoreTransactionResponse)(nil), "api.StoreTransactionResponse")
	proto.RegisterType((*TimeLockTransactionRequest)(nil), "api.TimeLockTransactionRequest")
	proto.RegisterType((*TimeLockTransactionResponse)(nil), "api.TimeLockTransactionResponse")
	proto.RegisterType((*LeadTransactionMiningRequest)(nil), "api.LeadTransactionMiningRequest")
	proto.RegisterType((*LeadTransactionMiningResponse)(nil), "api.LeadTransactionMiningResponse")
	proto.RegisterType((*ConfirmTransactionValidationRequest)(nil), "api.ConfirmTransactionValidationRequest")
	proto.RegisterType((*ConfirmTransactionValidationResponse)(nil), "api.ConfirmTransactionValidationResponse")
	proto.RegisterType((*SharedKeyPair)(nil), "api.SharedKeyPair")
	proto.RegisterType((*Transaction)(nil), "api.Transaction")
	proto.RegisterMapType((map[string][]byte)(nil), "api.Transaction.DataEntry")
	proto.RegisterType((*MasterValidation)(nil), "api.MasterValidation")
	proto.RegisterType((*NodeHeader)(nil), "api.NodeHeader")
	proto.RegisterType((*Validation)(nil), "api.Validation")
	proto.RegisterType((*MinedTransaction)(nil), "api.MinedTransaction")
	proto.RegisterEnum("api.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterEnum("api.TransactionStatus", TransactionStatus_name, TransactionStatus_value)
	proto.RegisterEnum("api.Validation_ValidationStatus", Validation_ValidationStatus_name, Validation_ValidationStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResponse, error)
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error)
	StoreTransaction(ctx context.Context, in *StoreTransactionRequest, opts ...grpc.CallOption) (*StoreTransactionResponse, error)
	TimeLockTransaction(ctx context.Context, in *TimeLockTransactionRequest, opts ...grpc.CallOption) (*TimeLockTransactionResponse, error)
	LeadTransactionMining(ctx context.Context, in *LeadTransactionMiningRequest, opts ...grpc.CallOption) (*LeadTransactionMiningResponse, error)
	ConfirmTransactionValidation(ctx context.Context, in *ConfirmTransactionValidationRequest, opts ...grpc.CallOption) (*ConfirmTransactionValidationResponse, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResponse, error) {
	out := new(GetLastTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/GetLastTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error) {
	out := new(GetTransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/GetTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) StoreTransaction(ctx context.Context, in *StoreTransactionRequest, opts ...grpc.CallOption) (*StoreTransactionResponse, error) {
	out := new(StoreTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/StoreTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) TimeLockTransaction(ctx context.Context, in *TimeLockTransactionRequest, opts ...grpc.CallOption) (*TimeLockTransactionResponse, error) {
	out := new(TimeLockTransactionResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/TimeLockTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) LeadTransactionMining(ctx context.Context, in *LeadTransactionMiningRequest, opts ...grpc.CallOption) (*LeadTransactionMiningResponse, error) {
	out := new(LeadTransactionMiningResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/LeadTransactionMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ConfirmTransactionValidation(ctx context.Context, in *ConfirmTransactionValidationRequest, opts ...grpc.CallOption) (*ConfirmTransactionValidationResponse, error) {
	out := new(ConfirmTransactionValidationResponse)
	err := c.cc.Invoke(ctx, "/api.TransactionService/ConfirmTransactionValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	GetLastTransaction(context.Context, *GetLastTransactionRequest) (*GetLastTransactionResponse, error)
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*GetTransactionStatusResponse, error)
	StoreTransaction(context.Context, *StoreTransactionRequest) (*StoreTransactionResponse, error)
	TimeLockTransaction(context.Context, *TimeLockTransactionRequest) (*TimeLockTransactionResponse, error)
	LeadTransactionMining(context.Context, *LeadTransactionMiningRequest) (*LeadTransactionMiningResponse, error)
	ConfirmTransactionValidation(context.Context, *ConfirmTransactionValidationRequest) (*ConfirmTransactionValidationResponse, error)
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_GetLastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetLastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/GetLastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetLastTransaction(ctx, req.(*GetLastTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/GetTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_StoreTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).StoreTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/StoreTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).StoreTransaction(ctx, req.(*StoreTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_TimeLockTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeLockTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).TimeLockTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/TimeLockTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).TimeLockTransaction(ctx, req.(*TimeLockTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_LeadTransactionMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeadTransactionMiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).LeadTransactionMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/LeadTransactionMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).LeadTransactionMining(ctx, req.(*LeadTransactionMiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ConfirmTransactionValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransactionValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ConfirmTransactionValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionService/ConfirmTransactionValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ConfirmTransactionValidation(ctx, req.(*ConfirmTransactionValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastTransaction",
			Handler:    _TransactionService_GetLastTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _TransactionService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "StoreTransaction",
			Handler:    _TransactionService_StoreTransaction_Handler,
		},
		{
			MethodName: "TimeLockTransaction",
			Handler:    _TransactionService_TimeLockTransaction_Handler,
		},
		{
			MethodName: "LeadTransactionMining",
			Handler:    _TransactionService_LeadTransactionMining_Handler,
		},
		{
			MethodName: "ConfirmTransactionValidation",
			Handler:    _TransactionService_ConfirmTransactionValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_1b15a2b3033c4b1c) }

var fileDescriptor_transaction_1b15a2b3033c4b1c = []byte{
	// 1264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0x67, 0xfd, 0x27, 0x75, 0x9e, 0x93, 0x78, 0x3d, 0x49, 0x5a, 0xc7, 0x75, 0xc0, 0x2c, 0x3d,
	0xb8, 0x45, 0xb8, 0x92, 0x2b, 0x41, 0xd4, 0x43, 0x45, 0x70, 0x4d, 0x12, 0x39, 0xb5, 0xa3, 0xb5,
	0x43, 0x41, 0x48, 0xac, 0x26, 0xf6, 0x24, 0x5e, 0xe2, 0xfd, 0xc3, 0xcc, 0x3a, 0x95, 0xbf, 0x01,
	0x77, 0x8e, 0x88, 0x13, 0x7c, 0x11, 0x90, 0x90, 0x38, 0xf0, 0x05, 0xb8, 0x20, 0x71, 0xe3, 0x63,
	0xa0, 0x9d, 0xd9, 0xb5, 0xc7, 0x9b, 0xb5, 0xe3, 0x42, 0x2a, 0x4e, 0xde, 0x79, 0x7f, 0xe6, 0xbd,
	0xf7, 0x9b, 0xf7, 0xde, 0xbc, 0x31, 0xe4, 0x3d, 0x8a, 0x6d, 0x86, 0x7b, 0x9e, 0xe9, 0xd8, 0x55,
	0x97, 0x3a, 0x9e, 0x83, 0x92, 0xd8, 0x35, 0xb5, 0x9f, 0x15, 0xd8, 0x39, 0x20, 0xde, 0x31, 0x66,
	0x5e, 0x77, 0x2a, 0xa1, 0x93, 0x6f, 0x46, 0x84, 0x79, 0xe8, 0x31, 0x6c, 0x4a, 0x7a, 0x06, 0xee,
	0xf7, 0x29, 0x61, 0xac, 0xa0, 0x94, 0x95, 0xca, 0x9a, 0x8e, 0x24, 0xd6, 0xbe, 0xe0, 0xa0, 0x0a,
	0xa4, 0xbc, 0xb1, 0x4b, 0x0a, 0x89, 0xb2, 0x52, 0xd9, 0xa8, 0x6d, 0x55, 0xb1, 0x6b, 0x56, 0xa5,
	0x7d, 0xbb, 0x63, 0x97, 0xe8, 0x5c, 0x02, 0x95, 0x60, 0xd5, 0x33, 0x2d, 0xc2, 0x3c, 0x6c, 0xb9,
	0x85, 0x64, 0x59, 0xa9, 0x24, 0xf5, 0x29, 0x01, 0xbd, 0x0f, 0x79, 0x66, 0x5e, 0xd8, 0xd8, 0x1b,
	0x51, 0x62, 0x50, 0xe1, 0x4d, 0x21, 0xc5, 0xcd, 0xaa, 0x13, 0x46, 0xe0, 0xa5, 0xf6, 0x83, 0x02,
	0xc5, 0xb8, 0x18, 0x98, 0xeb, 0xd8, 0x8c, 0xa0, 0x1a, 0x64, 0x25, 0x4f, 0xb9, 0xf3, 0xd9, 0x9a,
	0x1a, 0x75, 0x4d, 0x97, 0x85, 0x66, 0xbd, 0x4b, 0x44, 0xbd, 0xfb, 0x00, 0x90, 0xec, 0x9d, 0xb0,
	0xc3, 0x83, 0x58, 0xd3, 0xf3, 0x92, 0x7b, 0x82, 0xa1, 0x7d, 0xa7, 0xc0, 0xfd, 0x03, 0x22, 0xfb,
	0xd6, 0xf1, 0xb0, 0x37, 0x62, 0x21, 0xca, 0x0f, 0x41, 0x95, 0x51, 0x1e, 0x60, 0x36, 0x08, 0x20,
	0xce, 0x49, 0xf4, 0x43, 0xcc, 0x06, 0x37, 0xf8, 0x15, 0x8b, 0x5a, 0x72, 0x0e, 0x6a, 0xdf, 0x2b,
	0x50, 0x8a, 0xf7, 0x2a, 0xc0, 0xad, 0x0a, 0x2b, 0x8c, 0x53, 0xb8, 0x33, 0x1b, 0xb5, 0xbb, 0x51,
	0xc8, 0x02, 0xf9, 0x40, 0xea, 0x76, 0x31, 0xfb, 0x43, 0x81, 0x7b, 0x1d, 0xcf, 0xa1, 0x24, 0x26,
	0x2b, 0x3f, 0x81, 0xbc, 0x65, 0xda, 0xa4, 0x6f, 0x5c, 0x3f, 0xd6, 0x6d, 0xee, 0xe3, 0x0b, 0x9f,
	0x2b, 0x2b, 0xaa, 0x56, 0x84, 0xe2, 0x67, 0xb6, 0x65, 0xda, 0xa6, 0x35, 0xb2, 0x8c, 0x2b, 0x3c,
	0x34, 0xfb, 0xd8, 0xa7, 0x32, 0xee, 0x76, 0x5a, 0x47, 0x01, 0xeb, 0xb3, 0x29, 0xe7, 0x36, 0xf3,
	0xf5, 0x02, 0x0a, 0xd7, 0x43, 0x0b, 0x40, 0x9f, 0x31, 0xa3, 0x2c, 0x07, 0x62, 0x62, 0x1e, 0x88,
	0x7f, 0x29, 0x50, 0xec, 0x9a, 0x16, 0x39, 0x76, 0x7a, 0x97, 0x31, 0x38, 0xbe, 0x46, 0xde, 0x15,
	0xe0, 0x4e, 0x58, 0xfc, 0xc2, 0x5a, 0xb8, 0x44, 0x4f, 0xe0, 0xae, 0x85, 0x99, 0x47, 0xa8, 0x61,
	0x3b, 0x7d, 0x62, 0xb8, 0xa3, 0xb3, 0xa1, 0xd9, 0x33, 0x2e, 0xc9, 0x38, 0x38, 0xdb, 0x4d, 0xc1,
	0x6d, 0x39, 0x7d, 0x72, 0xc2, 0x79, 0x4d, 0x32, 0x9e, 0x8d, 0x32, 0xb5, 0x14, 0x98, 0xe9, 0x39,
	0x60, 0x7e, 0x0d, 0xf7, 0x63, 0x43, 0x7c, 0x13, 0x78, 0x7e, 0x9b, 0x80, 0xd2, 0x31, 0xc1, 0x72,
	0x22, 0xbd, 0x30, 0x6d, 0xd3, 0xbe, 0x08, 0x11, 0xfd, 0x37, 0xad, 0xe6, 0xb5, 0x33, 0x71, 0x0f,
	0x72, 0xaf, 0xc8, 0xb0, 0xe7, 0x58, 0xc4, 0x18, 0x10, 0xdc, 0x27, 0x94, 0x15, 0x92, 0xe5, 0x64,
	0x25, 0x5b, 0xcb, 0x71, 0x43, 0x3e, 0xd2, 0x87, 0x9c, 0xae, 0x6f, 0x04, 0x72, 0x62, 0xc9, 0x6e,
	0x13, 0xf6, 0x21, 0xec, 0xce, 0x41, 0xe2, 0x4d, 0x00, 0xff, 0xb7, 0x02, 0xef, 0xd5, 0x1d, 0xfb,
	0xdc, 0xa4, 0x96, 0x64, 0x71, 0x0a, 0xca, 0x7f, 0xc1, 0xdf, 0xef, 0x26, 0x22, 0x81, 0xa7, 0xf0,
	0x73, 0x4f, 0x26, 0xdd, 0x84, 0x73, 0x25, 0x63, 0xaa, 0x15, 0xa1, 0xdc, 0x66, 0x73, 0xf8, 0x49,
	0x81, 0x07, 0x8b, 0x43, 0x0d, 0x00, 0x7e, 0x0c, 0x20, 0x39, 0x2c, 0x42, 0x15, 0x19, 0x20, 0x09,
	0x4b, 0x22, 0xb7, 0xdb, 0x9f, 0xcf, 0x60, 0xbd, 0x33, 0xc0, 0x94, 0xf4, 0x9b, 0x64, 0x7c, 0x82,
	0x4d, 0x8a, 0x6a, 0xb0, 0x4d, 0xec, 0x1e, 0x1d, 0xbb, 0x1e, 0xe9, 0x1b, 0x2e, 0x35, 0xaf, 0xb0,
	0x47, 0x78, 0x1b, 0x10, 0x1d, 0x65, 0x73, 0xc2, 0x3c, 0x11, 0x3c, 0xbf, 0x0d, 0xec, 0x02, 0x48,
	0xfd, 0x42, 0x9c, 0xfe, 0xaa, 0x1b, 0x76, 0x09, 0xed, 0x97, 0x24, 0x64, 0xe5, 0x9e, 0x2d, 0x35,
	0x21, 0x65, 0xb6, 0x09, 0x2d, 0x3f, 0x76, 0x54, 0x21, 0xd5, 0xc7, 0x1e, 0x0e, 0x2a, 0xa6, 0x18,
	0x95, 0xac, 0x3e, 0xc7, 0x1e, 0x6e, 0xd8, 0x1e, 0x1d, 0xeb, 0x5c, 0xee, 0x86, 0x92, 0x99, 0x0d,
	0x20, 0x1d, 0x09, 0xc0, 0x57, 0x9e, 0x20, 0x57, 0x58, 0x11, 0xdc, 0x09, 0xc1, 0x4f, 0x0b, 0x62,
	0x99, 0x9e, 0x9f, 0x79, 0x53, 0xa9, 0x3b, 0x22, 0x2d, 0x02, 0x46, 0x67, 0x22, 0xdc, 0x81, 0x12,
	0xe3, 0x78, 0xfb, 0x96, 0x98, 0x11, 0x2a, 0xba, 0xd4, 0x71, 0x1d, 0x86, 0x87, 0x85, 0x0c, 0x3f,
	0x7f, 0xc4, 0xe3, 0x99, 0x39, 0x18, 0x7d, 0x87, 0x85, 0x4b, 0xd6, 0x10, 0x5a, 0x27, 0x81, 0x52,
	0xec, 0x05, 0xb0, 0x1a, 0x7b, 0x01, 0x14, 0x3f, 0x82, 0xd5, 0x09, 0x34, 0x48, 0x85, 0x64, 0x78,
	0xb2, 0xab, 0xba, 0xff, 0x89, 0xb6, 0x20, 0x7d, 0x85, 0x87, 0xa3, 0xb0, 0x84, 0xc5, 0xe2, 0x69,
	0x62, 0x4f, 0xd1, 0xfe, 0x4c, 0x80, 0x1a, 0xad, 0x20, 0xf4, 0x14, 0x76, 0x5c, 0x4a, 0xae, 0x4c,
	0x67, 0xc4, 0xa4, 0xaa, 0xe3, 0x37, 0x88, 0x7f, 0xb6, 0xc9, 0xca, 0x9a, 0x7e, 0x2f, 0x14, 0x98,
	0xaa, 0xf9, 0x9d, 0x8d, 0x21, 0x0d, 0xd6, 0x5d, 0xea, 0x38, 0xe7, 0x86, 0x73, 0x6e, 0xbc, 0x72,
	0xe8, 0x65, 0x60, 0x32, 0xcb, 0x89, 0xed, 0xf3, 0x97, 0x0e, 0xbd, 0x44, 0x1f, 0xc2, 0x86, 0x4b,
	0x89, 0x5c, 0xd0, 0xc9, 0xf8, 0xfa, 0x58, 0x77, 0x29, 0x91, 0xfc, 0x8a, 0x69, 0xad, 0xa9, 0xe5,
	0x5a, 0xeb, 0x33, 0x40, 0x52, 0x20, 0xa1, 0x72, 0x3a, 0x5e, 0x39, 0x3f, 0x15, 0x0d, 0xf5, 0xf7,
	0x20, 0xc7, 0x3c, 0x87, 0xe2, 0x8b, 0xa9, 0xe5, 0x95, 0x39, 0x96, 0x03, 0xb9, 0x40, 0x53, 0xfb,
	0x51, 0x01, 0x98, 0xb2, 0x23, 0x29, 0xa9, 0x44, 0x53, 0xf2, 0x01, 0xac, 0x9b, 0xec, 0xd4, 0xa6,
	0x04, 0xf7, 0x06, 0xf8, 0x6c, 0x28, 0x0e, 0x2c, 0xa3, 0xcf, 0x12, 0x51, 0x11, 0x32, 0x26, 0x13,
	0xa7, 0xc6, 0x91, 0xcb, 0xe8, 0x93, 0x35, 0x2a, 0x43, 0xd6, 0xc5, 0x5e, 0x6f, 0xd0, 0x1a, 0x59,
	0x67, 0x84, 0xf2, 0x9a, 0x48, 0xeb, 0x32, 0x09, 0x21, 0x48, 0x99, 0xac, 0xdd, 0xe4, 0xf5, 0x90,
	0xd1, 0xf9, 0xb7, 0xf6, 0xab, 0x02, 0x20, 0x01, 0x7d, 0x83, 0x97, 0x7b, 0x93, 0xd1, 0x53, 0x54,
	0x74, 0x39, 0x72, 0x6e, 0xd2, 0xe7, 0xa2, 0x21, 0xf4, 0x5a, 0x27, 0x9e, 0x29, 0xc8, 0x54, 0xa4,
	0x20, 0x35, 0x0d, 0xd4, 0xe8, 0xbe, 0x68, 0x05, 0x12, 0xad, 0xb6, 0xfa, 0x96, 0xff, 0xdb, 0x6e,
	0xaa, 0x8a, 0xf6, 0xbb, 0x02, 0x6a, 0x74, 0xbc, 0xfc, 0xdf, 0xae, 0x9d, 0x8f, 0x61, 0xb3, 0x27,
	0xae, 0x8a, 0x99, 0xd1, 0x41, 0x9e, 0x06, 0x24, 0x7d, 0x14, 0xc8, 0x4a, 0xb3, 0xc4, 0xa3, 0x67,
	0x90, 0x8b, 0xf4, 0x49, 0xb4, 0x06, 0x99, 0x66, 0xe3, 0x8b, 0xfa, 0xe1, 0xfe, 0x51, 0x4b, 0xc4,
	0x7d, 0xf4, 0x5c, 0x55, 0xd0, 0x36, 0xe4, 0xeb, 0xed, 0x56, 0x57, 0xdf, 0xaf, 0x77, 0x8d, 0xba,
	0xde, 0xd8, 0xef, 0x1e, 0xb5, 0x5b, 0x6a, 0xe2, 0x51, 0x13, 0xf2, 0xd7, 0x1e, 0x04, 0x28, 0x0b,
	0x77, 0x4e, 0x5b, 0xcd, 0x56, 0xfb, 0xa5, 0xbf, 0x41, 0x0e, 0xb2, 0x47, 0x2d, 0xe3, 0x44, 0x6f,
	0x1f, 0xe8, 0x8d, 0x4e, 0x47, 0x55, 0x7c, 0x6e, 0xe7, 0xb4, 0x5e, 0xf7, 0x17, 0x09, 0x7f, 0xf1,
	0xe9, 0xfe, 0xd1, 0xf1, 0xa9, 0xde, 0x50, 0x93, 0xb5, 0xdf, 0x52, 0x80, 0xe4, 0xdd, 0x08, 0xbd,
	0x32, 0x7b, 0x04, 0x9d, 0x02, 0xba, 0xfe, 0xba, 0x43, 0x6f, 0xf3, 0xf0, 0xe6, 0x3e, 0x5d, 0x8b,
	0xef, 0xcc, 0xe5, 0x07, 0xf7, 0xe7, 0x97, 0xb0, 0x15, 0xf7, 0xfc, 0x41, 0xe5, 0x50, 0x71, 0xde,
	0x7b, 0xad, 0xf8, 0xee, 0x02, 0x89, 0x60, 0xf3, 0x36, 0xa8, 0xd1, 0x11, 0x1f, 0x95, 0x44, 0x73,
	0x8e, 0x7f, 0xd4, 0x14, 0x77, 0xe7, 0x70, 0x83, 0x0d, 0x3f, 0x87, 0xcd, 0x98, 0x31, 0x17, 0x89,
	0x28, 0xe7, 0xcf, 0xf8, 0xc5, 0xf2, 0x7c, 0x81, 0x60, 0xe7, 0xaf, 0x60, 0x3b, 0x76, 0x92, 0x43,
	0x22, 0xcc, 0x45, 0xf3, 0x6e, 0x51, 0x5b, 0x24, 0x12, 0xec, 0xcf, 0xa0, 0xb4, 0x68, 0x9e, 0x41,
	0x15, 0xbe, 0xc7, 0x12, 0xd3, 0x5d, 0xf1, 0xe1, 0x12, 0x92, 0xc2, 0xe8, 0xd9, 0x0a, 0xff, 0x8b,
	0xe3, 0xc9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xe7, 0x38, 0x39, 0xf7, 0x10, 0x00, 0x00,
}
