// Code generated by protoc-gen-go. DO NOT EDIT.
// source: external.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Validation_ValidationStatus int32

const (
	Validation_OK Validation_ValidationStatus = 0
	Validation_KO Validation_ValidationStatus = 1
)

var Validation_ValidationStatus_name = map[int32]string{
	0: "OK",
	1: "KO",
}
var Validation_ValidationStatus_value = map[string]int32{
	"OK": 0,
	"KO": 1,
}

func (x Validation_ValidationStatus) String() string {
	return proto.EnumName(Validation_ValidationStatus_name, int32(x))
}
func (Validation_ValidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{14, 0}
}

type LockAck struct {
	Signature            string   `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	LockHash             string   `protobuf:"bytes,2,opt,name=LockHash,proto3" json:"LockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockAck) Reset()         { *m = LockAck{} }
func (m *LockAck) String() string { return proto.CompactTextString(m) }
func (*LockAck) ProtoMessage()    {}
func (*LockAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{0}
}
func (m *LockAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockAck.Unmarshal(m, b)
}
func (m *LockAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockAck.Marshal(b, m, deterministic)
}
func (dst *LockAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockAck.Merge(dst, src)
}
func (m *LockAck) XXX_Size() int {
	return xxx_messageInfo_LockAck.Size(m)
}
func (m *LockAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LockAck.DiscardUnknown(m)
}

var xxx_messageInfo_LockAck proto.InternalMessageInfo

func (m *LockAck) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *LockAck) GetLockHash() string {
	if m != nil {
		return m.LockHash
	}
	return ""
}

type StorageAck struct {
	Signature            string   `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	StorageHash          string   `protobuf:"bytes,2,opt,name=StorageHash,proto3" json:"StorageHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageAck) Reset()         { *m = StorageAck{} }
func (m *StorageAck) String() string { return proto.CompactTextString(m) }
func (*StorageAck) ProtoMessage()    {}
func (*StorageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{1}
}
func (m *StorageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageAck.Unmarshal(m, b)
}
func (m *StorageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageAck.Marshal(b, m, deterministic)
}
func (dst *StorageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageAck.Merge(dst, src)
}
func (m *StorageAck) XXX_Size() int {
	return xxx_messageInfo_StorageAck.Size(m)
}
func (m *StorageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageAck.DiscardUnknown(m)
}

var xxx_messageInfo_StorageAck proto.InternalMessageInfo

func (m *StorageAck) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *StorageAck) GetStorageHash() string {
	if m != nil {
		return m.StorageHash
	}
	return ""
}

type KeychainLeadRequest struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	ValidatorPeerIPs     []string `protobuf:"bytes,2,rep,name=ValidatorPeerIPs,proto3" json:"ValidatorPeerIPs,omitempty"`
	EncryptedKeychain    string   `protobuf:"bytes,3,opt,name=EncryptedKeychain,proto3" json:"EncryptedKeychain,omitempty"`
	SignatureRequest     string   `protobuf:"bytes,5,opt,name=SignatureRequest,proto3" json:"SignatureRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeychainLeadRequest) Reset()         { *m = KeychainLeadRequest{} }
func (m *KeychainLeadRequest) String() string { return proto.CompactTextString(m) }
func (*KeychainLeadRequest) ProtoMessage()    {}
func (*KeychainLeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{2}
}
func (m *KeychainLeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainLeadRequest.Unmarshal(m, b)
}
func (m *KeychainLeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainLeadRequest.Marshal(b, m, deterministic)
}
func (dst *KeychainLeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainLeadRequest.Merge(dst, src)
}
func (m *KeychainLeadRequest) XXX_Size() int {
	return xxx_messageInfo_KeychainLeadRequest.Size(m)
}
func (m *KeychainLeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainLeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainLeadRequest proto.InternalMessageInfo

func (m *KeychainLeadRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *KeychainLeadRequest) GetValidatorPeerIPs() []string {
	if m != nil {
		return m.ValidatorPeerIPs
	}
	return nil
}

func (m *KeychainLeadRequest) GetEncryptedKeychain() string {
	if m != nil {
		return m.EncryptedKeychain
	}
	return ""
}

func (m *KeychainLeadRequest) GetSignatureRequest() string {
	if m != nil {
		return m.SignatureRequest
	}
	return ""
}

type IDLeadRequest struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	ValidatorPeerIPs     []string `protobuf:"bytes,2,rep,name=ValidatorPeerIPs,proto3" json:"ValidatorPeerIPs,omitempty"`
	EncryptedID          string   `protobuf:"bytes,3,opt,name=EncryptedID,proto3" json:"EncryptedID,omitempty"`
	SignatureRequest     string   `protobuf:"bytes,5,opt,name=SignatureRequest,proto3" json:"SignatureRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDLeadRequest) Reset()         { *m = IDLeadRequest{} }
func (m *IDLeadRequest) String() string { return proto.CompactTextString(m) }
func (*IDLeadRequest) ProtoMessage()    {}
func (*IDLeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{3}
}
func (m *IDLeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDLeadRequest.Unmarshal(m, b)
}
func (m *IDLeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDLeadRequest.Marshal(b, m, deterministic)
}
func (dst *IDLeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDLeadRequest.Merge(dst, src)
}
func (m *IDLeadRequest) XXX_Size() int {
	return xxx_messageInfo_IDLeadRequest.Size(m)
}
func (m *IDLeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDLeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDLeadRequest proto.InternalMessageInfo

func (m *IDLeadRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *IDLeadRequest) GetValidatorPeerIPs() []string {
	if m != nil {
		return m.ValidatorPeerIPs
	}
	return nil
}

func (m *IDLeadRequest) GetEncryptedID() string {
	if m != nil {
		return m.EncryptedID
	}
	return ""
}

func (m *IDLeadRequest) GetSignatureRequest() string {
	if m != nil {
		return m.SignatureRequest
	}
	return ""
}

type KeychainValidationRequest struct {
	TransactionHash      string    `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	Data                 *Keychain `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature            string    `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KeychainValidationRequest) Reset()         { *m = KeychainValidationRequest{} }
func (m *KeychainValidationRequest) String() string { return proto.CompactTextString(m) }
func (*KeychainValidationRequest) ProtoMessage()    {}
func (*KeychainValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{4}
}
func (m *KeychainValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainValidationRequest.Unmarshal(m, b)
}
func (m *KeychainValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainValidationRequest.Marshal(b, m, deterministic)
}
func (dst *KeychainValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainValidationRequest.Merge(dst, src)
}
func (m *KeychainValidationRequest) XXX_Size() int {
	return xxx_messageInfo_KeychainValidationRequest.Size(m)
}
func (m *KeychainValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainValidationRequest proto.InternalMessageInfo

func (m *KeychainValidationRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *KeychainValidationRequest) GetData() *Keychain {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KeychainValidationRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type IDValidationRequest struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	Data                 *ID      `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDValidationRequest) Reset()         { *m = IDValidationRequest{} }
func (m *IDValidationRequest) String() string { return proto.CompactTextString(m) }
func (*IDValidationRequest) ProtoMessage()    {}
func (*IDValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{5}
}
func (m *IDValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDValidationRequest.Unmarshal(m, b)
}
func (m *IDValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDValidationRequest.Marshal(b, m, deterministic)
}
func (dst *IDValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDValidationRequest.Merge(dst, src)
}
func (m *IDValidationRequest) XXX_Size() int {
	return xxx_messageInfo_IDValidationRequest.Size(m)
}
func (m *IDValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDValidationRequest proto.InternalMessageInfo

func (m *IDValidationRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *IDValidationRequest) GetData() *ID {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IDValidationRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type KeychainStorageRequest struct {
	Data                 *Keychain    `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Endorsement          *Endorsement `protobuf:"bytes,2,opt,name=Endorsement,proto3" json:"Endorsement,omitempty"`
	Signature            string       `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *KeychainStorageRequest) Reset()         { *m = KeychainStorageRequest{} }
func (m *KeychainStorageRequest) String() string { return proto.CompactTextString(m) }
func (*KeychainStorageRequest) ProtoMessage()    {}
func (*KeychainStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{6}
}
func (m *KeychainStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainStorageRequest.Unmarshal(m, b)
}
func (m *KeychainStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainStorageRequest.Marshal(b, m, deterministic)
}
func (dst *KeychainStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainStorageRequest.Merge(dst, src)
}
func (m *KeychainStorageRequest) XXX_Size() int {
	return xxx_messageInfo_KeychainStorageRequest.Size(m)
}
func (m *KeychainStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainStorageRequest proto.InternalMessageInfo

func (m *KeychainStorageRequest) GetData() *Keychain {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KeychainStorageRequest) GetEndorsement() *Endorsement {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

func (m *KeychainStorageRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type IDStorageRequest struct {
	Data                 *ID          `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Endorsement          *Endorsement `protobuf:"bytes,2,opt,name=Endorsement,proto3" json:"Endorsement,omitempty"`
	Signature            string       `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IDStorageRequest) Reset()         { *m = IDStorageRequest{} }
func (m *IDStorageRequest) String() string { return proto.CompactTextString(m) }
func (*IDStorageRequest) ProtoMessage()    {}
func (*IDStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{7}
}
func (m *IDStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDStorageRequest.Unmarshal(m, b)
}
func (m *IDStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDStorageRequest.Marshal(b, m, deterministic)
}
func (dst *IDStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDStorageRequest.Merge(dst, src)
}
func (m *IDStorageRequest) XXX_Size() int {
	return xxx_messageInfo_IDStorageRequest.Size(m)
}
func (m *IDStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDStorageRequest proto.InternalMessageInfo

func (m *IDStorageRequest) GetData() *ID {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IDStorageRequest) GetEndorsement() *Endorsement {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

func (m *IDStorageRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type LockRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	TransactionHash      string   `protobuf:"bytes,2,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	MasterRobotKey       string   `protobuf:"bytes,3,opt,name=MasterRobotKey,proto3" json:"MasterRobotKey,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{8}
}
func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (dst *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(dst, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LockRequest) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *LockRequest) GetMasterRobotKey() string {
	if m != nil {
		return m.MasterRobotKey
	}
	return ""
}

func (m *LockRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Keychain struct {
	EncryptedAddrByRobot string    `protobuf:"bytes,1,opt,name=EncryptedAddrByRobot,proto3" json:"EncryptedAddrByRobot,omitempty"`
	EncryptedWallet      string    `protobuf:"bytes,2,opt,name=EncryptedWallet,proto3" json:"EncryptedWallet,omitempty"`
	IDPublicKey          string    `protobuf:"bytes,3,opt,name=IDPublicKey,proto3" json:"IDPublicKey,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,6,opt,name=Proposal,proto3" json:"Proposal,omitempty"`
	IDSignature          string    `protobuf:"bytes,4,opt,name=IDSignature,proto3" json:"IDSignature,omitempty"`
	EmitterSignature     string    `protobuf:"bytes,5,opt,name=EmitterSignature,proto3" json:"EmitterSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Keychain) Reset()         { *m = Keychain{} }
func (m *Keychain) String() string { return proto.CompactTextString(m) }
func (*Keychain) ProtoMessage()    {}
func (*Keychain) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{9}
}
func (m *Keychain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keychain.Unmarshal(m, b)
}
func (m *Keychain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keychain.Marshal(b, m, deterministic)
}
func (dst *Keychain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keychain.Merge(dst, src)
}
func (m *Keychain) XXX_Size() int {
	return xxx_messageInfo_Keychain.Size(m)
}
func (m *Keychain) XXX_DiscardUnknown() {
	xxx_messageInfo_Keychain.DiscardUnknown(m)
}

var xxx_messageInfo_Keychain proto.InternalMessageInfo

func (m *Keychain) GetEncryptedAddrByRobot() string {
	if m != nil {
		return m.EncryptedAddrByRobot
	}
	return ""
}

func (m *Keychain) GetEncryptedWallet() string {
	if m != nil {
		return m.EncryptedWallet
	}
	return ""
}

func (m *Keychain) GetIDPublicKey() string {
	if m != nil {
		return m.IDPublicKey
	}
	return ""
}

func (m *Keychain) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *Keychain) GetIDSignature() string {
	if m != nil {
		return m.IDSignature
	}
	return ""
}

func (m *Keychain) GetEmitterSignature() string {
	if m != nil {
		return m.EmitterSignature
	}
	return ""
}

type ID struct {
	Hash                 string    `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	EncryptedAddrByRobot string    `protobuf:"bytes,2,opt,name=EncryptedAddrByRobot,proto3" json:"EncryptedAddrByRobot,omitempty"`
	EncryptedAddrByID    string    `protobuf:"bytes,3,opt,name=EncryptedAddrByID,proto3" json:"EncryptedAddrByID,omitempty"`
	EncryptedAESKey      string    `protobuf:"bytes,4,opt,name=EncryptedAESKey,proto3" json:"EncryptedAESKey,omitempty"`
	PublicKey            string    `protobuf:"bytes,5,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,8,opt,name=Proposal,proto3" json:"Proposal,omitempty"`
	IDSignature          string    `protobuf:"bytes,6,opt,name=IDSignature,proto3" json:"IDSignature,omitempty"`
	EmitterSignature     string    `protobuf:"bytes,7,opt,name=EmitterSignature,proto3" json:"EmitterSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{10}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ID) GetEncryptedAddrByRobot() string {
	if m != nil {
		return m.EncryptedAddrByRobot
	}
	return ""
}

func (m *ID) GetEncryptedAddrByID() string {
	if m != nil {
		return m.EncryptedAddrByID
	}
	return ""
}

func (m *ID) GetEncryptedAESKey() string {
	if m != nil {
		return m.EncryptedAESKey
	}
	return ""
}

func (m *ID) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *ID) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *ID) GetIDSignature() string {
	if m != nil {
		return m.IDSignature
	}
	return ""
}

func (m *ID) GetEmitterSignature() string {
	if m != nil {
		return m.EmitterSignature
	}
	return ""
}

type Endorsement struct {
	LastTransactionHash  string            `protobuf:"bytes,1,opt,name=LastTransactionHash,proto3" json:"LastTransactionHash,omitempty"`
	TransactionHash      string            `protobuf:"bytes,2,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	MasterValidation     *MasterValidation `protobuf:"bytes,3,opt,name=MasterValidation,proto3" json:"MasterValidation,omitempty"`
	Validations          []*Validation     `protobuf:"bytes,4,rep,name=Validations,proto3" json:"Validations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Endorsement) Reset()         { *m = Endorsement{} }
func (m *Endorsement) String() string { return proto.CompactTextString(m) }
func (*Endorsement) ProtoMessage()    {}
func (*Endorsement) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{11}
}
func (m *Endorsement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endorsement.Unmarshal(m, b)
}
func (m *Endorsement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endorsement.Marshal(b, m, deterministic)
}
func (dst *Endorsement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorsement.Merge(dst, src)
}
func (m *Endorsement) XXX_Size() int {
	return xxx_messageInfo_Endorsement.Size(m)
}
func (m *Endorsement) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorsement.DiscardUnknown(m)
}

var xxx_messageInfo_Endorsement proto.InternalMessageInfo

func (m *Endorsement) GetLastTransactionHash() string {
	if m != nil {
		return m.LastTransactionHash
	}
	return ""
}

func (m *Endorsement) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Endorsement) GetMasterValidation() *MasterValidation {
	if m != nil {
		return m.MasterValidation
	}
	return nil
}

func (m *Endorsement) GetValidations() []*Validation {
	if m != nil {
		return m.Validations
	}
	return nil
}

type MasterValidation struct {
	ProofOfWorkKey        string      `protobuf:"bytes,1,opt,name=ProofOfWorkKey,proto3" json:"ProofOfWorkKey,omitempty"`
	ProofOfWorkValidation *Validation `protobuf:"bytes,2,opt,name=ProofOfWorkValidation,proto3" json:"ProofOfWorkValidation,omitempty"`
	LastTransactionMiners []string    `protobuf:"bytes,3,rep,name=LastTransactionMiners,proto3" json:"LastTransactionMiners,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}    `json:"-"`
	XXX_unrecognized      []byte      `json:"-"`
	XXX_sizecache         int32       `json:"-"`
}

func (m *MasterValidation) Reset()         { *m = MasterValidation{} }
func (m *MasterValidation) String() string { return proto.CompactTextString(m) }
func (*MasterValidation) ProtoMessage()    {}
func (*MasterValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{12}
}
func (m *MasterValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterValidation.Unmarshal(m, b)
}
func (m *MasterValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterValidation.Marshal(b, m, deterministic)
}
func (dst *MasterValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterValidation.Merge(dst, src)
}
func (m *MasterValidation) XXX_Size() int {
	return xxx_messageInfo_MasterValidation.Size(m)
}
func (m *MasterValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterValidation.DiscardUnknown(m)
}

var xxx_messageInfo_MasterValidation proto.InternalMessageInfo

func (m *MasterValidation) GetProofOfWorkKey() string {
	if m != nil {
		return m.ProofOfWorkKey
	}
	return ""
}

func (m *MasterValidation) GetProofOfWorkValidation() *Validation {
	if m != nil {
		return m.ProofOfWorkValidation
	}
	return nil
}

func (m *MasterValidation) GetLastTransactionMiners() []string {
	if m != nil {
		return m.LastTransactionMiners
	}
	return nil
}

type ValidationResponse struct {
	Validation           *Validation `protobuf:"bytes,1,opt,name=Validation,proto3" json:"Validation,omitempty"`
	Signature            string      `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ValidationResponse) Reset()         { *m = ValidationResponse{} }
func (m *ValidationResponse) String() string { return proto.CompactTextString(m) }
func (*ValidationResponse) ProtoMessage()    {}
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{13}
}
func (m *ValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResponse.Unmarshal(m, b)
}
func (m *ValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResponse.Marshal(b, m, deterministic)
}
func (dst *ValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResponse.Merge(dst, src)
}
func (m *ValidationResponse) XXX_Size() int {
	return xxx_messageInfo_ValidationResponse.Size(m)
}
func (m *ValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResponse proto.InternalMessageInfo

func (m *ValidationResponse) GetValidation() *Validation {
	if m != nil {
		return m.Validation
	}
	return nil
}

func (m *ValidationResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Validation struct {
	Status               Validation_ValidationStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=api.Validation_ValidationStatus" json:"Status,omitempty"`
	Timestamp            int64                       `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	PublicKey            string                      `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Signature            string                      `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Validation) Reset()         { *m = Validation{} }
func (m *Validation) String() string { return proto.CompactTextString(m) }
func (*Validation) ProtoMessage()    {}
func (*Validation) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{14}
}
func (m *Validation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validation.Unmarshal(m, b)
}
func (m *Validation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validation.Marshal(b, m, deterministic)
}
func (dst *Validation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validation.Merge(dst, src)
}
func (m *Validation) XXX_Size() int {
	return xxx_messageInfo_Validation.Size(m)
}
func (m *Validation) XXX_DiscardUnknown() {
	xxx_messageInfo_Validation.DiscardUnknown(m)
}

var xxx_messageInfo_Validation proto.InternalMessageInfo

func (m *Validation) GetStatus() Validation_ValidationStatus {
	if m != nil {
		return m.Status
	}
	return Validation_OK
}

func (m *Validation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Validation) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Validation) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type IDRequest struct {
	EncryptedIDHash      string   `protobuf:"bytes,1,opt,name=EncryptedIDHash,proto3" json:"EncryptedIDHash,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{15}
}
func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (dst *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(dst, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetEncryptedIDHash() string {
	if m != nil {
		return m.EncryptedIDHash
	}
	return ""
}

func (m *IDRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type KeychainRequest struct {
	EncryptedAddress     string   `protobuf:"bytes,1,opt,name=EncryptedAddress,proto3" json:"EncryptedAddress,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeychainRequest) Reset()         { *m = KeychainRequest{} }
func (m *KeychainRequest) String() string { return proto.CompactTextString(m) }
func (*KeychainRequest) ProtoMessage()    {}
func (*KeychainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{16}
}
func (m *KeychainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainRequest.Unmarshal(m, b)
}
func (m *KeychainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainRequest.Marshal(b, m, deterministic)
}
func (dst *KeychainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainRequest.Merge(dst, src)
}
func (m *KeychainRequest) XXX_Size() int {
	return xxx_messageInfo_KeychainRequest.Size(m)
}
func (m *KeychainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainRequest proto.InternalMessageInfo

func (m *KeychainRequest) GetEncryptedAddress() string {
	if m != nil {
		return m.EncryptedAddress
	}
	return ""
}

func (m *KeychainRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type IDResponse struct {
	Data                 *ID          `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Endorsement          *Endorsement `protobuf:"bytes,2,opt,name=Endorsement,proto3" json:"Endorsement,omitempty"`
	Signature            string       `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IDResponse) Reset()         { *m = IDResponse{} }
func (m *IDResponse) String() string { return proto.CompactTextString(m) }
func (*IDResponse) ProtoMessage()    {}
func (*IDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{17}
}
func (m *IDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDResponse.Unmarshal(m, b)
}
func (m *IDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDResponse.Marshal(b, m, deterministic)
}
func (dst *IDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDResponse.Merge(dst, src)
}
func (m *IDResponse) XXX_Size() int {
	return xxx_messageInfo_IDResponse.Size(m)
}
func (m *IDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IDResponse proto.InternalMessageInfo

func (m *IDResponse) GetData() *ID {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IDResponse) GetEndorsement() *Endorsement {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

func (m *IDResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type KeychainResponse struct {
	Data                 *Keychain    `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Endorsement          *Endorsement `protobuf:"bytes,2,opt,name=Endorsement,proto3" json:"Endorsement,omitempty"`
	Signature            string       `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *KeychainResponse) Reset()         { *m = KeychainResponse{} }
func (m *KeychainResponse) String() string { return proto.CompactTextString(m) }
func (*KeychainResponse) ProtoMessage()    {}
func (*KeychainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{18}
}
func (m *KeychainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainResponse.Unmarshal(m, b)
}
func (m *KeychainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainResponse.Marshal(b, m, deterministic)
}
func (dst *KeychainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainResponse.Merge(dst, src)
}
func (m *KeychainResponse) XXX_Size() int {
	return xxx_messageInfo_KeychainResponse.Size(m)
}
func (m *KeychainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainResponse proto.InternalMessageInfo

func (m *KeychainResponse) GetData() *Keychain {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KeychainResponse) GetEndorsement() *Endorsement {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

func (m *KeychainResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Proposal struct {
	SharedEmitterKeyPair *KeyPairProposal `protobuf:"bytes,1,opt,name=SharedEmitterKeyPair,proto3" json:"SharedEmitterKeyPair,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{19}
}
func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (dst *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(dst, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetSharedEmitterKeyPair() *KeyPairProposal {
	if m != nil {
		return m.SharedEmitterKeyPair
	}
	return nil
}

type KeyPairProposal struct {
	EncryptedPrivateKey  string   `protobuf:"bytes,1,opt,name=EncryptedPrivateKey,proto3" json:"EncryptedPrivateKey,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPairProposal) Reset()         { *m = KeyPairProposal{} }
func (m *KeyPairProposal) String() string { return proto.CompactTextString(m) }
func (*KeyPairProposal) ProtoMessage()    {}
func (*KeyPairProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_external_b06d5938b4d4e467, []int{20}
}
func (m *KeyPairProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPairProposal.Unmarshal(m, b)
}
func (m *KeyPairProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPairProposal.Marshal(b, m, deterministic)
}
func (dst *KeyPairProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPairProposal.Merge(dst, src)
}
func (m *KeyPairProposal) XXX_Size() int {
	return xxx_messageInfo_KeyPairProposal.Size(m)
}
func (m *KeyPairProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPairProposal.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPairProposal proto.InternalMessageInfo

func (m *KeyPairProposal) GetEncryptedPrivateKey() string {
	if m != nil {
		return m.EncryptedPrivateKey
	}
	return ""
}

func (m *KeyPairProposal) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func init() {
	proto.RegisterType((*LockAck)(nil), "api.LockAck")
	proto.RegisterType((*StorageAck)(nil), "api.StorageAck")
	proto.RegisterType((*KeychainLeadRequest)(nil), "api.KeychainLeadRequest")
	proto.RegisterType((*IDLeadRequest)(nil), "api.IDLeadRequest")
	proto.RegisterType((*KeychainValidationRequest)(nil), "api.KeychainValidationRequest")
	proto.RegisterType((*IDValidationRequest)(nil), "api.IDValidationRequest")
	proto.RegisterType((*KeychainStorageRequest)(nil), "api.KeychainStorageRequest")
	proto.RegisterType((*IDStorageRequest)(nil), "api.IDStorageRequest")
	proto.RegisterType((*LockRequest)(nil), "api.LockRequest")
	proto.RegisterType((*Keychain)(nil), "api.Keychain")
	proto.RegisterType((*ID)(nil), "api.ID")
	proto.RegisterType((*Endorsement)(nil), "api.Endorsement")
	proto.RegisterType((*MasterValidation)(nil), "api.MasterValidation")
	proto.RegisterType((*ValidationResponse)(nil), "api.ValidationResponse")
	proto.RegisterType((*Validation)(nil), "api.Validation")
	proto.RegisterType((*IDRequest)(nil), "api.IDRequest")
	proto.RegisterType((*KeychainRequest)(nil), "api.KeychainRequest")
	proto.RegisterType((*IDResponse)(nil), "api.IDResponse")
	proto.RegisterType((*KeychainResponse)(nil), "api.KeychainResponse")
	proto.RegisterType((*Proposal)(nil), "api.Proposal")
	proto.RegisterType((*KeyPairProposal)(nil), "api.KeyPairProposal")
	proto.RegisterEnum("api.Validation_ValidationStatus", Validation_ValidationStatus_name, Validation_ValidationStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExternalClient is the client API for External service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExternalClient interface {
	GetID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDResponse, error)
	GetKeychain(ctx context.Context, in *KeychainRequest, opts ...grpc.CallOption) (*KeychainResponse, error)
	LockTransaction(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockAck, error)
	UnlockTransaction(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockAck, error)
	LeadKeychainMining(ctx context.Context, in *KeychainLeadRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	LeadIDMining(ctx context.Context, in *IDLeadRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ValidateKeychain(ctx context.Context, in *KeychainValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
	ValidateID(ctx context.Context, in *IDValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
	StoreKeychain(ctx context.Context, in *KeychainStorageRequest, opts ...grpc.CallOption) (*StorageAck, error)
	StoreID(ctx context.Context, in *IDStorageRequest, opts ...grpc.CallOption) (*StorageAck, error)
}

type externalClient struct {
	cc *grpc.ClientConn
}

func NewExternalClient(cc *grpc.ClientConn) ExternalClient {
	return &externalClient{cc}
}

func (c *externalClient) GetID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, "/api.External/GetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) GetKeychain(ctx context.Context, in *KeychainRequest, opts ...grpc.CallOption) (*KeychainResponse, error) {
	out := new(KeychainResponse)
	err := c.cc.Invoke(ctx, "/api.External/GetKeychain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) LockTransaction(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockAck, error) {
	out := new(LockAck)
	err := c.cc.Invoke(ctx, "/api.External/LockTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) UnlockTransaction(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockAck, error) {
	out := new(LockAck)
	err := c.cc.Invoke(ctx, "/api.External/UnlockTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) LeadKeychainMining(ctx context.Context, in *KeychainLeadRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.External/LeadKeychainMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) LeadIDMining(ctx context.Context, in *IDLeadRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.External/LeadIDMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) ValidateKeychain(ctx context.Context, in *KeychainValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, "/api.External/ValidateKeychain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) ValidateID(ctx context.Context, in *IDValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, "/api.External/ValidateID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) StoreKeychain(ctx context.Context, in *KeychainStorageRequest, opts ...grpc.CallOption) (*StorageAck, error) {
	out := new(StorageAck)
	err := c.cc.Invoke(ctx, "/api.External/StoreKeychain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) StoreID(ctx context.Context, in *IDStorageRequest, opts ...grpc.CallOption) (*StorageAck, error) {
	out := new(StorageAck)
	err := c.cc.Invoke(ctx, "/api.External/StoreID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServer is the server API for External service.
type ExternalServer interface {
	GetID(context.Context, *IDRequest) (*IDResponse, error)
	GetKeychain(context.Context, *KeychainRequest) (*KeychainResponse, error)
	LockTransaction(context.Context, *LockRequest) (*LockAck, error)
	UnlockTransaction(context.Context, *LockRequest) (*LockAck, error)
	LeadKeychainMining(context.Context, *KeychainLeadRequest) (*empty.Empty, error)
	LeadIDMining(context.Context, *IDLeadRequest) (*empty.Empty, error)
	ValidateKeychain(context.Context, *KeychainValidationRequest) (*ValidationResponse, error)
	ValidateID(context.Context, *IDValidationRequest) (*ValidationResponse, error)
	StoreKeychain(context.Context, *KeychainStorageRequest) (*StorageAck, error)
	StoreID(context.Context, *IDStorageRequest) (*StorageAck, error)
}

func RegisterExternalServer(s *grpc.Server, srv ExternalServer) {
	s.RegisterService(&_External_serviceDesc, srv)
}

func _External_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).GetID(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_GetKeychain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).GetKeychain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/GetKeychain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).GetKeychain(ctx, req.(*KeychainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_LockTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).LockTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/LockTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).LockTransaction(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_UnlockTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).UnlockTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/UnlockTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).UnlockTransaction(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_LeadKeychainMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).LeadKeychainMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/LeadKeychainMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).LeadKeychainMining(ctx, req.(*KeychainLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_LeadIDMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).LeadIDMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/LeadIDMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).LeadIDMining(ctx, req.(*IDLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_ValidateKeychain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).ValidateKeychain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/ValidateKeychain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).ValidateKeychain(ctx, req.(*KeychainValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_ValidateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).ValidateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/ValidateID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).ValidateID(ctx, req.(*IDValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_StoreKeychain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).StoreKeychain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/StoreKeychain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).StoreKeychain(ctx, req.(*KeychainStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_StoreID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).StoreID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.External/StoreID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).StoreID(ctx, req.(*IDStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _External_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.External",
	HandlerType: (*ExternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetID",
			Handler:    _External_GetID_Handler,
		},
		{
			MethodName: "GetKeychain",
			Handler:    _External_GetKeychain_Handler,
		},
		{
			MethodName: "LockTransaction",
			Handler:    _External_LockTransaction_Handler,
		},
		{
			MethodName: "UnlockTransaction",
			Handler:    _External_UnlockTransaction_Handler,
		},
		{
			MethodName: "LeadKeychainMining",
			Handler:    _External_LeadKeychainMining_Handler,
		},
		{
			MethodName: "LeadIDMining",
			Handler:    _External_LeadIDMining_Handler,
		},
		{
			MethodName: "ValidateKeychain",
			Handler:    _External_ValidateKeychain_Handler,
		},
		{
			MethodName: "ValidateID",
			Handler:    _External_ValidateID_Handler,
		},
		{
			MethodName: "StoreKeychain",
			Handler:    _External_StoreKeychain_Handler,
		},
		{
			MethodName: "StoreID",
			Handler:    _External_StoreID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "external.proto",
}

func init() { proto.RegisterFile("external.proto", fileDescriptor_external_b06d5938b4d4e467) }

var fileDescriptor_external_b06d5938b4d4e467 = []byte{
	// 1080 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0x9d, 0x6c, 0xdb, 0xbc, 0x6c, 0x9b, 0xec, 0xb4, 0x59, 0x4c, 0x8a, 0x50, 0xf0, 0x01,
	0x95, 0x15, 0x4a, 0x21, 0x0b, 0x12, 0x07, 0x24, 0x14, 0x70, 0xb4, 0xb5, 0xd2, 0xaa, 0x91, 0x53,
	0xd8, 0x03, 0xa7, 0x69, 0x32, 0x4d, 0xad, 0x26, 0x76, 0xb0, 0x27, 0x88, 0xc0, 0x09, 0x21, 0xc1,
	0x89, 0x33, 0x1f, 0x84, 0x03, 0x07, 0xae, 0xf0, 0x39, 0xf8, 0x0a, 0x7c, 0x04, 0x34, 0xe3, 0xf1,
	0x78, 0x3c, 0x71, 0x9b, 0x46, 0xfc, 0x3b, 0x25, 0xfe, 0xcd, 0x9b, 0xf7, 0x7e, 0xef, 0xcf, 0xbc,
	0x79, 0x03, 0xfb, 0xe4, 0x2b, 0x4a, 0xa2, 0x00, 0x4f, 0xdb, 0xf3, 0x28, 0xa4, 0x21, 0x2a, 0xe1,
	0xb9, 0xdf, 0x3c, 0x9a, 0x84, 0xe1, 0x64, 0x4a, 0x4e, 0x38, 0x74, 0xb5, 0xb8, 0x3e, 0x21, 0xb3,
	0x39, 0x5d, 0x26, 0x12, 0xf6, 0x27, 0xb0, 0x73, 0x16, 0x8e, 0x6e, 0xbb, 0xa3, 0x5b, 0xf4, 0x1a,
	0x54, 0x86, 0xfe, 0x24, 0xc0, 0x74, 0x11, 0x11, 0xcb, 0x68, 0x19, 0xc7, 0x15, 0x2f, 0x03, 0x50,
	0x13, 0x76, 0x99, 0xe0, 0x29, 0x8e, 0x6f, 0x2c, 0x93, 0x2f, 0xca, 0x6f, 0xfb, 0x0c, 0x60, 0x48,
	0xc3, 0x08, 0x4f, 0xc8, 0x7a, 0x3d, 0x2d, 0xa8, 0x0a, 0x59, 0x45, 0x95, 0x0a, 0xd9, 0xbf, 0x1b,
	0x70, 0xd0, 0x27, 0xcb, 0xd1, 0x0d, 0xf6, 0x83, 0x33, 0x82, 0xc7, 0x1e, 0xf9, 0x62, 0x41, 0x62,
	0x8a, 0x8e, 0xa1, 0x76, 0x19, 0xe1, 0x20, 0xc6, 0x23, 0xea, 0x87, 0x01, 0xdf, 0x9d, 0x68, 0xd7,
	0x61, 0xf4, 0x0c, 0xea, 0x9f, 0xe1, 0xa9, 0x3f, 0xc6, 0x34, 0x8c, 0x06, 0x84, 0x44, 0xee, 0x20,
	0xb6, 0xcc, 0x56, 0xe9, 0xb8, 0xe2, 0xad, 0xe0, 0xe8, 0x6d, 0x78, 0xd2, 0x0b, 0x46, 0xd1, 0x72,
	0x4e, 0xc9, 0x38, 0xb5, 0x6a, 0x95, 0xb8, 0xde, 0xd5, 0x05, 0xa6, 0x59, 0xba, 0x22, 0x78, 0x59,
	0x8f, 0xb8, 0xf0, 0x0a, 0x6e, 0xff, 0x6c, 0xc0, 0x9e, 0xeb, 0xfc, 0xfb, 0x1e, 0xb4, 0xa0, 0x2a,
	0x89, 0xba, 0x8e, 0xe0, 0xae, 0x42, 0x1b, 0xb1, 0xfe, 0xde, 0x80, 0x57, 0x53, 0x77, 0x85, 0x29,
	0x3f, 0x0c, 0x36, 0xf7, 0xe0, 0x0d, 0x28, 0x3b, 0x98, 0x62, 0x9e, 0xe0, 0x6a, 0x67, 0xaf, 0x8d,
	0xe7, 0x7e, 0x3b, 0xd5, 0xeb, 0xf1, 0xa5, 0x7c, 0xa1, 0x94, 0xb4, 0x42, 0xb1, 0xbf, 0x86, 0x03,
	0xd7, 0xf9, 0x3b, 0x0c, 0x8e, 0x72, 0x0c, 0x76, 0x38, 0x03, 0xd7, 0x79, 0x90, 0xed, 0x1f, 0x0d,
	0x78, 0x9a, 0x92, 0x15, 0xa5, 0x99, 0xda, 0x4f, 0xfd, 0x32, 0xee, 0xf6, 0xab, 0xc3, 0x12, 0x32,
	0x0e, 0xa3, 0x98, 0xcc, 0x48, 0x40, 0x85, 0xfd, 0x3a, 0x97, 0x54, 0x70, 0x4f, 0x15, 0x5a, 0xc3,
	0xe7, 0x5b, 0x03, 0xea, 0xae, 0xa3, 0x31, 0x39, 0xca, 0x31, 0xd1, 0xfc, 0xfb, 0xe7, 0x39, 0xfc,
	0x64, 0x40, 0x95, 0x9d, 0xf8, 0xd4, 0xbc, 0x05, 0x3b, 0xdd, 0xf1, 0x38, 0x22, 0x71, 0x2c, 0x12,
	0x90, 0x7e, 0x16, 0xa5, 0xc8, 0x2c, 0x4e, 0xd1, 0x9b, 0xb0, 0x7f, 0x8e, 0x63, 0x4a, 0x22, 0x2f,
	0xbc, 0x0a, 0x69, 0x9f, 0x2c, 0x85, 0x59, 0x0d, 0xcd, 0x33, 0x2b, 0xeb, 0xcc, 0xbe, 0x33, 0x61,
	0x57, 0x9e, 0xd0, 0x0e, 0x1c, 0xca, 0xd2, 0x67, 0x84, 0x3e, 0x5e, 0x72, 0x2d, 0x82, 0x63, 0xe1,
	0x1a, 0x23, 0x2c, 0xf1, 0x97, 0x78, 0x3a, 0x25, 0x34, 0x25, 0xac, 0xc1, 0xec, 0xac, 0xb9, 0xce,
	0x60, 0x71, 0x35, 0xf5, 0x47, 0x19, 0x5b, 0x15, 0x42, 0x6f, 0xc1, 0xee, 0x20, 0x0a, 0xe7, 0x61,
	0x8c, 0xa7, 0xd6, 0xb6, 0x52, 0x23, 0x29, 0xe8, 0xc9, 0xe5, 0x44, 0x99, 0xee, 0x97, 0x0a, 0xb1,
	0x83, 0xdb, 0x9b, 0xf9, 0x94, 0x92, 0x28, 0x13, 0x13, 0x07, 0x57, 0xc7, 0xed, 0x5f, 0x4d, 0x30,
	0x5d, 0x07, 0x21, 0x28, 0x2b, 0x87, 0x82, 0xff, 0xbf, 0x33, 0x26, 0xe6, 0x3d, 0x31, 0x51, 0xfb,
	0x62, 0x82, 0xcb, 0xde, 0xb2, 0xba, 0x90, 0x8b, 0x60, 0xb7, 0x37, 0x64, 0xb1, 0x29, 0x6b, 0x11,
	0x4c, 0x60, 0x96, 0xca, 0x2c, 0x7e, 0x89, 0x2f, 0x95, 0xe2, 0xe8, 0xed, 0x6e, 0x14, 0xbd, 0xed,
	0x87, 0x45, 0x6f, 0xe7, 0x8e, 0xe8, 0xfd, 0x61, 0xe4, 0x0e, 0x0c, 0x7a, 0x07, 0x0e, 0xce, 0x70,
	0x4c, 0x8b, 0x5b, 0x4d, 0xd1, 0xd2, 0x06, 0x55, 0xdf, 0x85, 0x7a, 0x52, 0xdf, 0x59, 0x77, 0xe3,
	0x91, 0xad, 0x76, 0x1a, 0xdc, 0x59, 0x7d, 0xd1, 0x5b, 0x11, 0x47, 0xef, 0x42, 0x35, 0xfb, 0x8a,
	0xad, 0x72, 0xab, 0x74, 0x5c, 0xed, 0xd4, 0xf8, 0x6e, 0x65, 0x9f, 0x2a, 0x63, 0xff, 0x62, 0xac,
	0x9a, 0x65, 0x07, 0x70, 0x10, 0x85, 0xe1, 0xf5, 0xc5, 0xf5, 0xcb, 0x30, 0xba, 0x65, 0x29, 0x49,
	0x3c, 0xd4, 0x50, 0xd4, 0x83, 0x86, 0x82, 0x28, 0xbc, 0x93, 0xc6, 0xb2, 0x62, 0xb9, 0x58, 0x1a,
	0xbd, 0x07, 0x0d, 0x2d, 0x74, 0xe7, 0x7e, 0x40, 0xa2, 0xd8, 0x2a, 0xf1, 0xbb, 0xad, 0x78, 0xd1,
	0x1e, 0x01, 0x52, 0xef, 0x81, 0x78, 0x1e, 0x06, 0x31, 0x41, 0x27, 0x00, 0x0a, 0x0f, 0xa3, 0x98,
	0x87, 0x22, 0x92, 0x6f, 0x22, 0xa6, 0xde, 0x44, 0x7e, 0x33, 0x54, 0x7d, 0xe8, 0x03, 0xd8, 0x1e,
	0x52, 0x4c, 0x17, 0x49, 0x73, 0xdb, 0xef, 0xb4, 0x34, 0xcd, 0xca, 0xdf, 0x44, 0xce, 0x13, 0xf2,
	0xcc, 0xcc, 0xa5, 0x3f, 0x23, 0x31, 0xc5, 0xb3, 0x39, 0x37, 0x53, 0xf2, 0x32, 0x20, 0x5f, 0xfe,
	0x25, 0xbd, 0xfc, 0xef, 0xef, 0x73, 0xb6, 0x1c, 0x0a, 0xa4, 0x55, 0xb4, 0x0d, 0xe6, 0x45, 0xbf,
	0xbe, 0xc5, 0x7e, 0xfb, 0x17, 0x75, 0xc3, 0x1e, 0x42, 0xc5, 0x75, 0x94, 0xbb, 0x52, 0x19, 0x03,
	0xd4, 0xbb, 0x52, 0x83, 0xd7, 0xc4, 0xe6, 0x73, 0xa8, 0xc9, 0x2b, 0x4e, 0xa8, 0x66, 0x67, 0x4b,
	0xed, 0x02, 0xd9, 0x35, 0xb0, 0x82, 0xaf, 0x51, 0xfe, 0x0d, 0x00, 0x63, 0x2c, 0xb2, 0xfa, 0x1f,
	0x5f, 0x6a, 0x3f, 0x18, 0x50, 0xcf, 0x5c, 0x13, 0x1c, 0xfe, 0x97, 0x2b, 0xfe, 0x32, 0xeb, 0x7c,
	0xe8, 0x14, 0x0e, 0x87, 0x37, 0x38, 0x22, 0x63, 0xd1, 0xa6, 0xfa, 0x64, 0x39, 0xc0, 0x7e, 0x24,
	0x08, 0x1d, 0xa6, 0x84, 0x18, 0x26, 0x1b, 0x63, 0xe1, 0x0e, 0x1b, 0xf3, 0xcc, 0xa9, 0x82, 0xac,
	0xb3, 0xc9, 0x0c, 0x0d, 0x22, 0xff, 0x4b, 0x4c, 0x49, 0x76, 0xee, 0x8b, 0x96, 0xf2, 0x35, 0x6b,
	0x6a, 0x35, 0xdb, 0xf9, 0xb3, 0x0c, 0xbb, 0x3d, 0xf1, 0xec, 0x40, 0xcf, 0xe0, 0xd1, 0x0b, 0x42,
	0x5d, 0x07, 0xed, 0xa7, 0x99, 0x4b, 0xea, 0xa5, 0x59, 0x93, 0xdf, 0x49, 0x90, 0xed, 0x2d, 0xf4,
	0x21, 0x54, 0x5f, 0x10, 0x2a, 0x2f, 0xee, 0xc3, 0x7c, 0x9c, 0xc5, 0xbe, 0x86, 0x86, 0xca, 0xdd,
	0xcf, 0xa1, 0xc6, 0xa6, 0x11, 0xa5, 0x5b, 0xa0, 0x24, 0xfe, 0xca, 0x8c, 0xd2, 0x7c, 0x2c, 0x91,
	0xee, 0xe8, 0xd6, 0xde, 0x42, 0xef, 0xc3, 0x93, 0x4f, 0x83, 0xe9, 0xc6, 0xdb, 0x4e, 0x01, 0xb1,
	0x31, 0x3e, 0x65, 0x71, 0xee, 0x07, 0x7e, 0x30, 0x41, 0x56, 0x8e, 0x9a, 0x32, 0xe7, 0x37, 0x9f,
	0xb6, 0x93, 0x27, 0x57, 0x3b, 0x7d, 0x72, 0xb5, 0x7b, 0xec, 0xc9, 0xc5, 0x7d, 0x7e, 0xcc, 0x04,
	0x5d, 0x47, 0xe8, 0x40, 0x22, 0x2c, 0x0f, 0xdb, 0x7d, 0x2e, 0x1b, 0x00, 0x91, 0x61, 0x7b, 0x3d,
	0xc7, 0x62, 0x65, 0x5e, 0x6e, 0xbe, 0xa2, 0xb7, 0xc4, 0x2c, 0x84, 0x5d, 0xd9, 0xf1, 0x88, 0xeb,
	0x08, 0x77, 0x0a, 0x46, 0xee, 0xfb, 0x54, 0x7c, 0x04, 0x7b, 0x6c, 0x2a, 0xcd, 0xe8, 0x1c, 0xe5,
	0xe8, 0xe4, 0x27, 0x56, 0x51, 0x04, 0xd9, 0x53, 0x91, 0xa7, 0x71, 0x87, 0x2b, 0x70, 0x1d, 0xd4,
	0x10, 0x04, 0xd6, 0x6e, 0xba, 0xda, 0xe6, 0x91, 0x79, 0xfe, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x23, 0x84, 0x7c, 0x3e, 0xef, 0x0e, 0x00, 0x00,
}
