// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountSearchRequest struct {
	EncryptedHashPerson  string   `protobuf:"bytes,1,opt,name=EncryptedHashPerson,proto3" json:"EncryptedHashPerson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSearchRequest) Reset()         { *m = AccountSearchRequest{} }
func (m *AccountSearchRequest) String() string { return proto.CompactTextString(m) }
func (*AccountSearchRequest) ProtoMessage()    {}
func (*AccountSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_a8365b84bbc69315, []int{0}
}
func (m *AccountSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSearchRequest.Unmarshal(m, b)
}
func (m *AccountSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSearchRequest.Marshal(b, m, deterministic)
}
func (dst *AccountSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSearchRequest.Merge(dst, src)
}
func (m *AccountSearchRequest) XXX_Size() int {
	return xxx_messageInfo_AccountSearchRequest.Size(m)
}
func (m *AccountSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSearchRequest proto.InternalMessageInfo

func (m *AccountSearchRequest) GetEncryptedHashPerson() string {
	if m != nil {
		return m.EncryptedHashPerson
	}
	return ""
}

type AccountSearchResult struct {
	EncryptedWallet      string   `protobuf:"bytes,1,opt,name=EncryptedWallet,proto3" json:"EncryptedWallet,omitempty"`
	EncryptedAESkey      string   `protobuf:"bytes,2,opt,name=EncryptedAESkey,proto3" json:"EncryptedAESkey,omitempty"`
	EncryptedAddress     string   `protobuf:"bytes,3,opt,name=EncryptedAddress,proto3" json:"EncryptedAddress,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSearchResult) Reset()         { *m = AccountSearchResult{} }
func (m *AccountSearchResult) String() string { return proto.CompactTextString(m) }
func (*AccountSearchResult) ProtoMessage()    {}
func (*AccountSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_a8365b84bbc69315, []int{1}
}
func (m *AccountSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSearchResult.Unmarshal(m, b)
}
func (m *AccountSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSearchResult.Marshal(b, m, deterministic)
}
func (dst *AccountSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSearchResult.Merge(dst, src)
}
func (m *AccountSearchResult) XXX_Size() int {
	return xxx_messageInfo_AccountSearchResult.Size(m)
}
func (m *AccountSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSearchResult proto.InternalMessageInfo

func (m *AccountSearchResult) GetEncryptedWallet() string {
	if m != nil {
		return m.EncryptedWallet
	}
	return ""
}

func (m *AccountSearchResult) GetEncryptedAESkey() string {
	if m != nil {
		return m.EncryptedAESkey
	}
	return ""
}

func (m *AccountSearchResult) GetEncryptedAddress() string {
	if m != nil {
		return m.EncryptedAddress
	}
	return ""
}

func (m *AccountSearchResult) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type KeychainCreationRequest struct {
	EncryptedKeychainData string     `protobuf:"bytes,1,opt,name=EncryptedKeychainData,proto3" json:"EncryptedKeychainData,omitempty"`
	SignatureKeychainData *Signature `protobuf:"bytes,2,opt,name=SignatureKeychainData,proto3" json:"SignatureKeychainData,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *KeychainCreationRequest) Reset()         { *m = KeychainCreationRequest{} }
func (m *KeychainCreationRequest) String() string { return proto.CompactTextString(m) }
func (*KeychainCreationRequest) ProtoMessage()    {}
func (*KeychainCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_a8365b84bbc69315, []int{2}
}
func (m *KeychainCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainCreationRequest.Unmarshal(m, b)
}
func (m *KeychainCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainCreationRequest.Marshal(b, m, deterministic)
}
func (dst *KeychainCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainCreationRequest.Merge(dst, src)
}
func (m *KeychainCreationRequest) XXX_Size() int {
	return xxx_messageInfo_KeychainCreationRequest.Size(m)
}
func (m *KeychainCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainCreationRequest proto.InternalMessageInfo

func (m *KeychainCreationRequest) GetEncryptedKeychainData() string {
	if m != nil {
		return m.EncryptedKeychainData
	}
	return ""
}

func (m *KeychainCreationRequest) GetSignatureKeychainData() *Signature {
	if m != nil {
		return m.SignatureKeychainData
	}
	return nil
}

type BiometricCreationRequest struct {
	EncryptedBiometricData string     `protobuf:"bytes,1,opt,name=EncryptedBiometricData,proto3" json:"EncryptedBiometricData,omitempty"`
	SignatureBiometricData *Signature `protobuf:"bytes,2,opt,name=SignatureBiometricData,proto3" json:"SignatureBiometricData,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}   `json:"-"`
	XXX_unrecognized       []byte     `json:"-"`
	XXX_sizecache          int32      `json:"-"`
}

func (m *BiometricCreationRequest) Reset()         { *m = BiometricCreationRequest{} }
func (m *BiometricCreationRequest) String() string { return proto.CompactTextString(m) }
func (*BiometricCreationRequest) ProtoMessage()    {}
func (*BiometricCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_a8365b84bbc69315, []int{3}
}
func (m *BiometricCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiometricCreationRequest.Unmarshal(m, b)
}
func (m *BiometricCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiometricCreationRequest.Marshal(b, m, deterministic)
}
func (dst *BiometricCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiometricCreationRequest.Merge(dst, src)
}
func (m *BiometricCreationRequest) XXX_Size() int {
	return xxx_messageInfo_BiometricCreationRequest.Size(m)
}
func (m *BiometricCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiometricCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiometricCreationRequest proto.InternalMessageInfo

func (m *BiometricCreationRequest) GetEncryptedBiometricData() string {
	if m != nil {
		return m.EncryptedBiometricData
	}
	return ""
}

func (m *BiometricCreationRequest) GetSignatureBiometricData() *Signature {
	if m != nil {
		return m.SignatureBiometricData
	}
	return nil
}

type CreationResult struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	MasterPeerIP         string   `protobuf:"bytes,2,opt,name=MasterPeerIP,proto3" json:"MasterPeerIP,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreationResult) Reset()         { *m = CreationResult{} }
func (m *CreationResult) String() string { return proto.CompactTextString(m) }
func (*CreationResult) ProtoMessage()    {}
func (*CreationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_a8365b84bbc69315, []int{4}
}
func (m *CreationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationResult.Unmarshal(m, b)
}
func (m *CreationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationResult.Marshal(b, m, deterministic)
}
func (dst *CreationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationResult.Merge(dst, src)
}
func (m *CreationResult) XXX_Size() int {
	return xxx_messageInfo_CreationResult.Size(m)
}
func (m *CreationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreationResult proto.InternalMessageInfo

func (m *CreationResult) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *CreationResult) GetMasterPeerIP() string {
	if m != nil {
		return m.MasterPeerIP
	}
	return ""
}

func (m *CreationResult) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountSearchRequest)(nil), "api.AccountSearchRequest")
	proto.RegisterType((*AccountSearchResult)(nil), "api.AccountSearchResult")
	proto.RegisterType((*KeychainCreationRequest)(nil), "api.KeychainCreationRequest")
	proto.RegisterType((*BiometricCreationRequest)(nil), "api.BiometricCreationRequest")
	proto.RegisterType((*CreationResult)(nil), "api.CreationResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalClient interface {
	GetAccount(ctx context.Context, in *AccountSearchRequest, opts ...grpc.CallOption) (*AccountSearchResult, error)
	CreateKeychain(ctx context.Context, in *KeychainCreationRequest, opts ...grpc.CallOption) (*CreationResult, error)
	CreateBiometric(ctx context.Context, in *BiometricCreationRequest, opts ...grpc.CallOption) (*CreationResult, error)
}

type internalClient struct {
	cc *grpc.ClientConn
}

func NewInternalClient(cc *grpc.ClientConn) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) GetAccount(ctx context.Context, in *AccountSearchRequest, opts ...grpc.CallOption) (*AccountSearchResult, error) {
	out := new(AccountSearchResult)
	err := c.cc.Invoke(ctx, "/api.Internal/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) CreateKeychain(ctx context.Context, in *KeychainCreationRequest, opts ...grpc.CallOption) (*CreationResult, error) {
	out := new(CreationResult)
	err := c.cc.Invoke(ctx, "/api.Internal/CreateKeychain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) CreateBiometric(ctx context.Context, in *BiometricCreationRequest, opts ...grpc.CallOption) (*CreationResult, error) {
	out := new(CreationResult)
	err := c.cc.Invoke(ctx, "/api.Internal/CreateBiometric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServer is the server API for Internal service.
type InternalServer interface {
	GetAccount(context.Context, *AccountSearchRequest) (*AccountSearchResult, error)
	CreateKeychain(context.Context, *KeychainCreationRequest) (*CreationResult, error)
	CreateBiometric(context.Context, *BiometricCreationRequest) (*CreationResult, error)
}

func RegisterInternalServer(s *grpc.Server, srv InternalServer) {
	s.RegisterService(&_Internal_serviceDesc, srv)
}

func _Internal_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Internal/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).GetAccount(ctx, req.(*AccountSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_CreateKeychain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).CreateKeychain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Internal/CreateKeychain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).CreateKeychain(ctx, req.(*KeychainCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_CreateBiometric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiometricCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).CreateBiometric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Internal/CreateBiometric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).CreateBiometric(ctx, req.(*BiometricCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Internal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Internal_GetAccount_Handler,
		},
		{
			MethodName: "CreateKeychain",
			Handler:    _Internal_CreateKeychain_Handler,
		},
		{
			MethodName: "CreateBiometric",
			Handler:    _Internal_CreateBiometric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_internal_a8365b84bbc69315) }

var fileDescriptor_internal_a8365b84bbc69315 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0xc9, 0x98, 0xa6, 0x71, 0x86, 0x60, 0x32, 0x83, 0x65, 0x88, 0x49, 0x93, 0xaf, 0xd0,
	0x2e, 0xd0, 0xc4, 0xa6, 0xdd, 0x33, 0x60, 0x80, 0xa6, 0x49, 0x08, 0x2a, 0xf5, 0xda, 0x35, 0x47,
	0xc5, 0x6a, 0xb0, 0x53, 0xdb, 0xb9, 0x40, 0xea, 0x6b, 0xf4, 0xa6, 0xaf, 0xd1, 0x07, 0xea, 0xab,
	0x54, 0x09, 0x89, 0x69, 0xd2, 0xe4, 0xf6, 0x3f, 0x5f, 0x7e, 0xff, 0xf6, 0x7f, 0x02, 0x2d, 0x21,
	0x2d, 0x6a, 0xc9, 0x82, 0x51, 0xa8, 0x95, 0x55, 0xa4, 0xce, 0x42, 0xd1, 0x6f, 0x72, 0x75, 0x38,
	0x28, 0x79, 0x92, 0xe8, 0x12, 0x3e, 0x4d, 0x38, 0x57, 0x91, 0xb4, 0x5b, 0x64, 0x9a, 0xef, 0x37,
	0x78, 0x1b, 0xa1, 0xb1, 0xe4, 0x07, 0x74, 0xe6, 0x92, 0xeb, 0x63, 0x68, 0x71, 0xb7, 0x64, 0x66,
	0xbf, 0x46, 0x6d, 0x94, 0xf4, 0xbd, 0x6f, 0xde, 0xb0, 0xb1, 0x29, 0x1b, 0xd1, 0x47, 0x0f, 0x3a,
	0x05, 0x2b, 0x13, 0x05, 0x96, 0x0c, 0xa1, 0xed, 0xf0, 0x4b, 0x16, 0x04, 0x68, 0x53, 0x97, 0xa2,
	0x9c, 0x23, 0x27, 0xf3, 0xed, 0x0d, 0x1e, 0xfd, 0x37, 0x05, 0xf2, 0x24, 0x93, 0xef, 0xf0, 0xf1,
	0x2c, 0xed, 0x76, 0x1a, 0x8d, 0xf1, 0xeb, 0x09, 0xfa, 0x4a, 0x27, 0x03, 0x68, 0x6c, 0xc5, 0xb5,
	0x64, 0x36, 0xd2, 0xe8, 0xbf, 0x4d, 0xa0, 0xb3, 0x40, 0xef, 0x3d, 0xf8, 0xfc, 0x0f, 0x8f, 0x7c,
	0xcf, 0x84, 0x9c, 0x6a, 0x64, 0x56, 0x28, 0x99, 0xbd, 0xc1, 0x2f, 0xe8, 0x3a, 0xb7, 0x8c, 0x99,
	0x31, 0xcb, 0xd2, 0xfc, 0xe5, 0x43, 0x32, 0x83, 0xae, 0xb3, 0xcf, 0x7d, 0x15, 0xdf, 0xe5, 0xc3,
	0xb8, 0x35, 0x62, 0xa1, 0x18, 0x39, 0x62, 0x53, 0x0e, 0xd3, 0x07, 0x0f, 0xfc, 0x3f, 0x42, 0x1d,
	0xd0, 0x6a, 0xc1, 0x8b, 0xc1, 0x7e, 0x43, 0xcf, 0x9d, 0xed, 0xa0, 0x17, 0xc9, 0x2a, 0xa6, 0xe4,
	0x2f, 0xf4, 0xdc, 0x69, 0xf9, 0xef, 0xca, 0xb3, 0x55, 0xd0, 0xf4, 0x0e, 0x5a, 0xe7, 0x48, 0x59,
	0xc9, 0x17, 0x9a, 0x49, 0xc3, 0x78, 0x2c, 0xc6, 0x5b, 0x91, 0x95, 0x5c, 0x90, 0x09, 0x85, 0xe6,
	0x7f, 0x66, 0x2c, 0xea, 0x35, 0xa2, 0x5e, 0xad, 0xd3, 0x86, 0x73, 0x5a, 0xbe, 0xb2, 0x7a, 0xa1,
	0xb2, 0xf1, 0x93, 0x07, 0xef, 0x57, 0xe9, 0x62, 0x93, 0x29, 0xc0, 0x02, 0x6d, 0xba, 0x77, 0xe4,
	0x4b, 0x72, 0x81, 0xb2, 0x85, 0xee, 0xfb, 0x65, 0xa3, 0x38, 0x3b, 0xad, 0x91, 0x79, 0x7a, 0x1f,
	0x57, 0x01, 0x19, 0x24, 0x74, 0xc5, 0x62, 0xf4, 0x3b, 0xc9, 0x34, 0xff, 0x04, 0xb4, 0x46, 0x16,
	0xd0, 0x3e, 0xd9, 0xb8, 0xd7, 0x22, 0x5f, 0x13, 0xb2, 0xaa, 0xc8, 0x0a, 0xa3, 0xab, 0x77, 0xc9,
	0xbf, 0xf9, 0xf3, 0x39, 0x00, 0x00, 0xff, 0xff, 0x54, 0x84, 0x23, 0x14, 0xc0, 0x03, 0x00, 0x00,
}
