// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerAppState_PeerStatus int32

const (
	PeerAppState_Bootstraping PeerAppState_PeerStatus = 0
	PeerAppState_Ok           PeerAppState_PeerStatus = 1
	PeerAppState_Faulty       PeerAppState_PeerStatus = 2
	PeerAppState_StorageOnly  PeerAppState_PeerStatus = 3
)

var PeerAppState_PeerStatus_name = map[int32]string{
	0: "Bootstraping",
	1: "Ok",
	2: "Faulty",
	3: "StorageOnly",
}
var PeerAppState_PeerStatus_value = map[string]int32{
	"Bootstraping": 0,
	"Ok":           1,
	"Faulty":       2,
	"StorageOnly":  3,
}

func (x PeerAppState_PeerStatus) String() string {
	return proto.EnumName(PeerAppState_PeerStatus_name, int32(x))
}
func (PeerAppState_PeerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{7, 0}
}

type SynRequest struct {
	Initiator            *PeerDigest   `protobuf:"bytes,1,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Target               *PeerDigest   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	KnownPeers           []*PeerDigest `protobuf:"bytes,3,rep,name=KnownPeers,proto3" json:"KnownPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SynRequest) Reset()         { *m = SynRequest{} }
func (m *SynRequest) String() string { return proto.CompactTextString(m) }
func (*SynRequest) ProtoMessage()    {}
func (*SynRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{0}
}
func (m *SynRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynRequest.Unmarshal(m, b)
}
func (m *SynRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynRequest.Marshal(b, m, deterministic)
}
func (dst *SynRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynRequest.Merge(dst, src)
}
func (m *SynRequest) XXX_Size() int {
	return xxx_messageInfo_SynRequest.Size(m)
}
func (m *SynRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SynRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SynRequest proto.InternalMessageInfo

func (m *SynRequest) GetInitiator() *PeerDigest {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *SynRequest) GetTarget() *PeerDigest {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SynRequest) GetKnownPeers() []*PeerDigest {
	if m != nil {
		return m.KnownPeers
	}
	return nil
}

type AckRequest struct {
	Initiator            *PeerDigest       `protobuf:"bytes,1,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Target               *PeerDigest       `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	RequestedPeers       []*PeerDiscovered `protobuf:"bytes,3,rep,name=RequestedPeers,proto3" json:"RequestedPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AckRequest) Reset()         { *m = AckRequest{} }
func (m *AckRequest) String() string { return proto.CompactTextString(m) }
func (*AckRequest) ProtoMessage()    {}
func (*AckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{1}
}
func (m *AckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRequest.Unmarshal(m, b)
}
func (m *AckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRequest.Marshal(b, m, deterministic)
}
func (dst *AckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRequest.Merge(dst, src)
}
func (m *AckRequest) XXX_Size() int {
	return xxx_messageInfo_AckRequest.Size(m)
}
func (m *AckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckRequest proto.InternalMessageInfo

func (m *AckRequest) GetInitiator() *PeerDigest {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *AckRequest) GetTarget() *PeerDigest {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AckRequest) GetRequestedPeers() []*PeerDiscovered {
	if m != nil {
		return m.RequestedPeers
	}
	return nil
}

type SynAck struct {
	Initiator            *PeerDigest       `protobuf:"bytes,1,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Target               *PeerDigest       `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	NewPeers             []*PeerDiscovered `protobuf:"bytes,3,rep,name=NewPeers,proto3" json:"NewPeers,omitempty"`
	UnknownPeers         []*PeerDigest     `protobuf:"bytes,4,rep,name=UnknownPeers,proto3" json:"UnknownPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SynAck) Reset()         { *m = SynAck{} }
func (m *SynAck) String() string { return proto.CompactTextString(m) }
func (*SynAck) ProtoMessage()    {}
func (*SynAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{2}
}
func (m *SynAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynAck.Unmarshal(m, b)
}
func (m *SynAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynAck.Marshal(b, m, deterministic)
}
func (dst *SynAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynAck.Merge(dst, src)
}
func (m *SynAck) XXX_Size() int {
	return xxx_messageInfo_SynAck.Size(m)
}
func (m *SynAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SynAck.DiscardUnknown(m)
}

var xxx_messageInfo_SynAck proto.InternalMessageInfo

func (m *SynAck) GetInitiator() *PeerDigest {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *SynAck) GetTarget() *PeerDigest {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SynAck) GetNewPeers() []*PeerDiscovered {
	if m != nil {
		return m.NewPeers
	}
	return nil
}

func (m *SynAck) GetUnknownPeers() []*PeerDigest {
	if m != nil {
		return m.UnknownPeers
	}
	return nil
}

type PeerDigest struct {
	Identity             *PeerIdentity       `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	HeartbeatState       *PeerHeartbeatState `protobuf:"bytes,2,opt,name=HeartbeatState,proto3" json:"HeartbeatState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PeerDigest) Reset()         { *m = PeerDigest{} }
func (m *PeerDigest) String() string { return proto.CompactTextString(m) }
func (*PeerDigest) ProtoMessage()    {}
func (*PeerDigest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{3}
}
func (m *PeerDigest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDigest.Unmarshal(m, b)
}
func (m *PeerDigest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDigest.Marshal(b, m, deterministic)
}
func (dst *PeerDigest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDigest.Merge(dst, src)
}
func (m *PeerDigest) XXX_Size() int {
	return xxx_messageInfo_PeerDigest.Size(m)
}
func (m *PeerDigest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDigest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDigest proto.InternalMessageInfo

func (m *PeerDigest) GetIdentity() *PeerIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *PeerDigest) GetHeartbeatState() *PeerHeartbeatState {
	if m != nil {
		return m.HeartbeatState
	}
	return nil
}

type PeerDiscovered struct {
	Identity             *PeerIdentity       `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	HeartbeatState       *PeerHeartbeatState `protobuf:"bytes,2,opt,name=HeartbeatState,proto3" json:"HeartbeatState,omitempty"`
	AppState             *PeerAppState       `protobuf:"bytes,3,opt,name=AppState,proto3" json:"AppState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PeerDiscovered) Reset()         { *m = PeerDiscovered{} }
func (m *PeerDiscovered) String() string { return proto.CompactTextString(m) }
func (*PeerDiscovered) ProtoMessage()    {}
func (*PeerDiscovered) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{4}
}
func (m *PeerDiscovered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDiscovered.Unmarshal(m, b)
}
func (m *PeerDiscovered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDiscovered.Marshal(b, m, deterministic)
}
func (dst *PeerDiscovered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDiscovered.Merge(dst, src)
}
func (m *PeerDiscovered) XXX_Size() int {
	return xxx_messageInfo_PeerDiscovered.Size(m)
}
func (m *PeerDiscovered) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDiscovered.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDiscovered proto.InternalMessageInfo

func (m *PeerDiscovered) GetIdentity() *PeerIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *PeerDiscovered) GetHeartbeatState() *PeerHeartbeatState {
	if m != nil {
		return m.HeartbeatState
	}
	return nil
}

func (m *PeerDiscovered) GetAppState() *PeerAppState {
	if m != nil {
		return m.AppState
	}
	return nil
}

type PeerIdentity struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerIdentity) Reset()         { *m = PeerIdentity{} }
func (m *PeerIdentity) String() string { return proto.CompactTextString(m) }
func (*PeerIdentity) ProtoMessage()    {}
func (*PeerIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{5}
}
func (m *PeerIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerIdentity.Unmarshal(m, b)
}
func (m *PeerIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerIdentity.Marshal(b, m, deterministic)
}
func (dst *PeerIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerIdentity.Merge(dst, src)
}
func (m *PeerIdentity) XXX_Size() int {
	return xxx_messageInfo_PeerIdentity.Size(m)
}
func (m *PeerIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_PeerIdentity proto.InternalMessageInfo

func (m *PeerIdentity) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeerIdentity) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *PeerIdentity) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PeerHeartbeatState struct {
	GenerationTime       int64    `protobuf:"varint,1,opt,name=GenerationTime,proto3" json:"GenerationTime,omitempty"`
	ElapsedHeartbeats    int64    `protobuf:"varint,2,opt,name=ElapsedHeartbeats,proto3" json:"ElapsedHeartbeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerHeartbeatState) Reset()         { *m = PeerHeartbeatState{} }
func (m *PeerHeartbeatState) String() string { return proto.CompactTextString(m) }
func (*PeerHeartbeatState) ProtoMessage()    {}
func (*PeerHeartbeatState) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{6}
}
func (m *PeerHeartbeatState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerHeartbeatState.Unmarshal(m, b)
}
func (m *PeerHeartbeatState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerHeartbeatState.Marshal(b, m, deterministic)
}
func (dst *PeerHeartbeatState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerHeartbeatState.Merge(dst, src)
}
func (m *PeerHeartbeatState) XXX_Size() int {
	return xxx_messageInfo_PeerHeartbeatState.Size(m)
}
func (m *PeerHeartbeatState) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerHeartbeatState.DiscardUnknown(m)
}

var xxx_messageInfo_PeerHeartbeatState proto.InternalMessageInfo

func (m *PeerHeartbeatState) GetGenerationTime() int64 {
	if m != nil {
		return m.GenerationTime
	}
	return 0
}

func (m *PeerHeartbeatState) GetElapsedHeartbeats() int64 {
	if m != nil {
		return m.ElapsedHeartbeats
	}
	return 0
}

type PeerAppState struct {
	Status                PeerAppState_PeerStatus      `protobuf:"varint,4,opt,name=Status,proto3,enum=api.PeerAppState_PeerStatus" json:"Status,omitempty"`
	CPULoad               string                       `protobuf:"bytes,5,opt,name=CPULoad,proto3" json:"CPULoad,omitempty"`
	FreeDiskSpace         float32                      `protobuf:"fixed32,6,opt,name=FreeDiskSpace,proto3" json:"FreeDiskSpace,omitempty"`
	Version               string                       `protobuf:"bytes,7,opt,name=Version,proto3" json:"Version,omitempty"`
	GeoPosition           *PeerAppState_GeoCoordinates `protobuf:"bytes,8,opt,name=GeoPosition,proto3" json:"GeoPosition,omitempty"`
	P2PFactor             int32                        `protobuf:"varint,9,opt,name=P2PFactor,proto3" json:"P2PFactor,omitempty"`
	DiscoveredPeersNumber int32                        `protobuf:"varint,10,opt,name=DiscoveredPeersNumber,proto3" json:"DiscoveredPeersNumber,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                     `json:"-"`
	XXX_unrecognized      []byte                       `json:"-"`
	XXX_sizecache         int32                        `json:"-"`
}

func (m *PeerAppState) Reset()         { *m = PeerAppState{} }
func (m *PeerAppState) String() string { return proto.CompactTextString(m) }
func (*PeerAppState) ProtoMessage()    {}
func (*PeerAppState) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{7}
}
func (m *PeerAppState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAppState.Unmarshal(m, b)
}
func (m *PeerAppState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAppState.Marshal(b, m, deterministic)
}
func (dst *PeerAppState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAppState.Merge(dst, src)
}
func (m *PeerAppState) XXX_Size() int {
	return xxx_messageInfo_PeerAppState.Size(m)
}
func (m *PeerAppState) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAppState.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAppState proto.InternalMessageInfo

func (m *PeerAppState) GetStatus() PeerAppState_PeerStatus {
	if m != nil {
		return m.Status
	}
	return PeerAppState_Bootstraping
}

func (m *PeerAppState) GetCPULoad() string {
	if m != nil {
		return m.CPULoad
	}
	return ""
}

func (m *PeerAppState) GetFreeDiskSpace() float32 {
	if m != nil {
		return m.FreeDiskSpace
	}
	return 0
}

func (m *PeerAppState) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PeerAppState) GetGeoPosition() *PeerAppState_GeoCoordinates {
	if m != nil {
		return m.GeoPosition
	}
	return nil
}

func (m *PeerAppState) GetP2PFactor() int32 {
	if m != nil {
		return m.P2PFactor
	}
	return 0
}

func (m *PeerAppState) GetDiscoveredPeersNumber() int32 {
	if m != nil {
		return m.DiscoveredPeersNumber
	}
	return 0
}

type PeerAppState_GeoCoordinates struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=Lon,proto3" json:"Lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAppState_GeoCoordinates) Reset()         { *m = PeerAppState_GeoCoordinates{} }
func (m *PeerAppState_GeoCoordinates) String() string { return proto.CompactTextString(m) }
func (*PeerAppState_GeoCoordinates) ProtoMessage()    {}
func (*PeerAppState_GeoCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_72aec4044b06f202, []int{7, 0}
}
func (m *PeerAppState_GeoCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAppState_GeoCoordinates.Unmarshal(m, b)
}
func (m *PeerAppState_GeoCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAppState_GeoCoordinates.Marshal(b, m, deterministic)
}
func (dst *PeerAppState_GeoCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAppState_GeoCoordinates.Merge(dst, src)
}
func (m *PeerAppState_GeoCoordinates) XXX_Size() int {
	return xxx_messageInfo_PeerAppState_GeoCoordinates.Size(m)
}
func (m *PeerAppState_GeoCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAppState_GeoCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAppState_GeoCoordinates proto.InternalMessageInfo

func (m *PeerAppState_GeoCoordinates) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *PeerAppState_GeoCoordinates) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterType((*SynRequest)(nil), "api.SynRequest")
	proto.RegisterType((*AckRequest)(nil), "api.AckRequest")
	proto.RegisterType((*SynAck)(nil), "api.SynAck")
	proto.RegisterType((*PeerDigest)(nil), "api.PeerDigest")
	proto.RegisterType((*PeerDiscovered)(nil), "api.PeerDiscovered")
	proto.RegisterType((*PeerIdentity)(nil), "api.PeerIdentity")
	proto.RegisterType((*PeerHeartbeatState)(nil), "api.PeerHeartbeatState")
	proto.RegisterType((*PeerAppState)(nil), "api.PeerAppState")
	proto.RegisterType((*PeerAppState_GeoCoordinates)(nil), "api.PeerAppState.GeoCoordinates")
	proto.RegisterEnum("api.PeerAppState_PeerStatus", PeerAppState_PeerStatus_name, PeerAppState_PeerStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoveryClient interface {
	Synchronize(ctx context.Context, in *SynRequest, opts ...grpc.CallOption) (*SynAck, error)
	Acknowledge(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type discoveryClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryClient(cc *grpc.ClientConn) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) Synchronize(ctx context.Context, in *SynRequest, opts ...grpc.CallOption) (*SynAck, error) {
	out := new(SynAck)
	err := c.cc.Invoke(ctx, "/api.Discovery/Synchronize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) Acknowledge(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.Discovery/Acknowledge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServer is the server API for Discovery service.
type DiscoveryServer interface {
	Synchronize(context.Context, *SynRequest) (*SynAck, error)
	Acknowledge(context.Context, *AckRequest) (*empty.Empty, error)
}

func RegisterDiscoveryServer(s *grpc.Server, srv DiscoveryServer) {
	s.RegisterService(&_Discovery_serviceDesc, srv)
}

func _Discovery_Synchronize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).Synchronize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/Synchronize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).Synchronize(ctx, req.(*SynRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/Acknowledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).Acknowledge(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Synchronize",
			Handler:    _Discovery_Synchronize_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _Discovery_Acknowledge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor_discovery_72aec4044b06f202) }

var fileDescriptor_discovery_72aec4044b06f202 = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x8d, 0xac, 0xc4, 0x89, 0xc7, 0xbe, 0x8e, 0xc3, 0x8b, 0x7b, 0x2b, 0xb8, 0x59, 0x18, 0x42,
	0xd1, 0x66, 0xd1, 0x38, 0x80, 0x93, 0x45, 0x81, 0x2e, 0x0a, 0xe7, 0x59, 0x23, 0x41, 0x22, 0xd0,
	0x49, 0xf7, 0xb4, 0x34, 0x75, 0x59, 0x3b, 0xa4, 0x4a, 0xd1, 0x0d, 0x54, 0xf4, 0x37, 0xfa, 0x01,
	0xfd, 0x82, 0xa2, 0x3f, 0xd1, 0xef, 0x2a, 0x44, 0x49, 0x96, 0x5f, 0x40, 0x57, 0xe9, 0x8e, 0x3c,
	0xe7, 0x8c, 0xe6, 0xcc, 0x50, 0x43, 0xc2, 0x76, 0xc0, 0x23, 0x5f, 0x7e, 0x46, 0x15, 0xb7, 0x43,
	0x25, 0xb5, 0x24, 0x36, 0x0b, 0x79, 0xf3, 0xe9, 0x50, 0xca, 0xe1, 0x18, 0x0f, 0x0c, 0x34, 0x98,
	0xbc, 0x3f, 0xc0, 0xfb, 0x50, 0x67, 0x0a, 0xf7, 0x9b, 0x05, 0xd0, 0x8f, 0x05, 0xc5, 0x4f, 0x13,
	0x8c, 0x34, 0xd9, 0x87, 0x4a, 0x4f, 0x70, 0xcd, 0x99, 0x96, 0xca, 0xb1, 0x5a, 0xd6, 0x5e, 0xb5,
	0xb3, 0xdd, 0x66, 0x21, 0x6f, 0x7b, 0x88, 0xea, 0x94, 0x0f, 0x31, 0xd2, 0xb4, 0x50, 0x90, 0x17,
	0x50, 0xbe, 0x65, 0x6a, 0x88, 0xda, 0x29, 0xad, 0xd6, 0x66, 0x34, 0x39, 0x00, 0xb8, 0x14, 0xf2,
	0x41, 0x24, 0x54, 0xe4, 0xd8, 0x2d, 0x7b, 0x95, 0x78, 0x46, 0xe2, 0x7e, 0xb7, 0x00, 0xba, 0xfe,
	0xe8, 0xb1, 0x7d, 0xbd, 0x86, 0x7a, 0x96, 0x02, 0x83, 0x59, 0x6f, 0xff, 0xce, 0x04, 0xa4, 0x2d,
	0xc5, 0x80, 0x2e, 0x48, 0xdd, 0x5f, 0x16, 0x94, 0xfb, 0xb1, 0xe8, 0xfa, 0xa3, 0x47, 0xec, 0xdb,
	0xd6, 0x35, 0x3e, 0xfc, 0xd1, 0xd9, 0x54, 0x44, 0x0e, 0xa1, 0x76, 0x27, 0x46, 0x45, 0xab, 0xd7,
	0x57, 0xb7, 0x7a, 0x4e, 0xe4, 0x7e, 0x05, 0x28, 0x38, 0xb2, 0x0f, 0x5b, 0xbd, 0x00, 0x85, 0xe6,
	0x3a, 0xce, 0x4a, 0xd9, 0x99, 0x86, 0xe7, 0x04, 0x9d, 0x4a, 0xc8, 0x1b, 0xa8, 0xbf, 0x45, 0xa6,
	0xf4, 0x00, 0x99, 0xee, 0x6b, 0xa6, 0x31, 0xab, 0xe9, 0xc9, 0x34, 0x68, 0x9e, 0xa6, 0x0b, 0x72,
	0xf7, 0x87, 0x05, 0xf5, 0xf9, 0x7a, 0xfe, 0xb6, 0x85, 0x24, 0x5f, 0x37, 0x0c, 0xd3, 0x50, 0x7b,
	0x21, 0x5f, 0x4e, 0xd0, 0xa9, 0xc4, 0xf5, 0xa0, 0x36, 0xeb, 0x84, 0xec, 0x42, 0xc5, 0x9b, 0x0c,
	0xc6, 0xdc, 0xbf, 0xc4, 0xd4, 0x6f, 0x8d, 0x16, 0x00, 0xa9, 0x43, 0xa9, 0xe7, 0x19, 0x47, 0x15,
	0x5a, 0xea, 0x79, 0x84, 0xc0, 0xba, 0x27, 0x95, 0x36, 0x89, 0x36, 0xa8, 0x59, 0xbb, 0x1f, 0x81,
	0x2c, 0xdb, 0x24, 0xcf, 0xa1, 0x7e, 0x81, 0x02, 0x15, 0xd3, 0x5c, 0x8a, 0x5b, 0x7e, 0x8f, 0xe6,
	0xe3, 0x36, 0x5d, 0x40, 0xc9, 0x4b, 0xd8, 0x39, 0x1b, 0xb3, 0x30, 0xc2, 0x60, 0xfa, 0x81, 0xc8,
	0x24, 0xb4, 0xe9, 0x32, 0xe1, 0xfe, 0xb4, 0x53, 0xfb, 0x79, 0x39, 0xe4, 0x08, 0xca, 0xc9, 0x62,
	0x92, 0xfc, 0x2d, 0xd6, 0x5e, 0xbd, 0xb3, 0xbb, 0x54, 0xbb, 0xd9, 0xa4, 0x1a, 0x9a, 0x69, 0x89,
	0x03, 0x9b, 0x27, 0xde, 0xdd, 0x95, 0x64, 0x81, 0xb3, 0x61, 0x6a, 0xcb, 0xb7, 0xe4, 0x19, 0xfc,
	0x73, 0xae, 0x10, 0x4f, 0x79, 0x34, 0xea, 0x87, 0xcc, 0x47, 0xa7, 0xdc, 0xb2, 0xf6, 0x4a, 0x74,
	0x1e, 0x4c, 0xe2, 0xdf, 0xa1, 0x8a, 0xb8, 0x14, 0xce, 0x66, 0x1a, 0x9f, 0x6d, 0xc9, 0x31, 0x54,
	0x2f, 0x50, 0x7a, 0x32, 0xe2, 0x49, 0x85, 0xce, 0x96, 0x39, 0x90, 0xd6, 0xb2, 0xa9, 0x0b, 0x94,
	0x27, 0x52, 0xaa, 0x80, 0x0b, 0xa6, 0x31, 0xa2, 0xb3, 0x41, 0xe6, 0x48, 0x3a, 0xde, 0x39, 0xf3,
	0x93, 0x81, 0xac, 0x98, 0x4e, 0x17, 0x00, 0x39, 0x82, 0xff, 0x8a, 0xbf, 0xcd, 0xcc, 0xc0, 0xf5,
	0xe4, 0x7e, 0x80, 0xca, 0x01, 0xa3, 0x5c, 0x4d, 0x36, 0x8f, 0x92, 0xe3, 0x98, 0x4d, 0x49, 0x1a,
	0x60, 0x5f, 0x31, 0x6d, 0x4e, 0xa5, 0x44, 0x93, 0xa5, 0x41, 0xa4, 0x30, 0xcd, 0x4f, 0x10, 0x29,
	0xdc, 0x93, 0x74, 0xb8, 0xb2, 0xae, 0x35, 0xa0, 0x76, 0x2c, 0xa5, 0x8e, 0xb4, 0x62, 0x21, 0x17,
	0xc3, 0xc6, 0x1a, 0x29, 0x43, 0xe9, 0x66, 0xd4, 0xb0, 0x08, 0x40, 0xf9, 0x9c, 0x4d, 0xc6, 0x3a,
	0x6e, 0x94, 0xc8, 0x36, 0x54, 0xfb, 0x5a, 0x2a, 0x36, 0xc4, 0x1b, 0x31, 0x8e, 0x1b, 0x76, 0x47,
	0x43, 0x25, 0xf7, 0x14, 0x93, 0x7d, 0xa8, 0xf6, 0x63, 0xe1, 0x7f, 0x50, 0x52, 0xf0, 0x2f, 0x48,
	0xd2, 0xe1, 0x2e, 0x2e, 0xf1, 0x66, 0x35, 0x07, 0xba, 0xfe, 0xc8, 0x5d, 0x23, 0xaf, 0xa0, 0xda,
	0xf5, 0x93, 0x69, 0x1f, 0x63, 0x30, 0xcc, 0xe5, 0xc5, 0xdd, 0xda, 0xfc, 0xbf, 0x9d, 0x3e, 0x10,
	0xed, 0xfc, 0x81, 0x68, 0x9f, 0x25, 0x0f, 0x84, 0xbb, 0x36, 0x28, 0x1b, 0xe4, 0xf0, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x68, 0xff, 0x5a, 0x33, 0x58, 0x06, 0x00, 0x00,
}
