// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerDetailed_PeerState_PeerStatus int32

const (
	PeerDetailed_PeerState_Fault        PeerDetailed_PeerState_PeerStatus = 0
	PeerDetailed_PeerState_Bootstraping PeerDetailed_PeerState_PeerStatus = 1
	PeerDetailed_PeerState_Ok           PeerDetailed_PeerState_PeerStatus = 2
	PeerDetailed_PeerState_StorageOnly  PeerDetailed_PeerState_PeerStatus = 3
)

var PeerDetailed_PeerState_PeerStatus_name = map[int32]string{
	0: "Fault",
	1: "Bootstraping",
	2: "Ok",
	3: "StorageOnly",
}
var PeerDetailed_PeerState_PeerStatus_value = map[string]int32{
	"Fault":        0,
	"Bootstraping": 1,
	"Ok":           2,
	"StorageOnly":  3,
}

func (x PeerDetailed_PeerState_PeerStatus) String() string {
	return proto.EnumName(PeerDetailed_PeerState_PeerStatus_name, int32(x))
}
func (PeerDetailed_PeerState_PeerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{4, 0, 0}
}

type SynRequest struct {
	Initiator            *PeerDigest   `protobuf:"bytes,1,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Target               *PeerDigest   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	KnownPeers           []*PeerDigest `protobuf:"bytes,3,rep,name=KnownPeers,proto3" json:"KnownPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SynRequest) Reset()         { *m = SynRequest{} }
func (m *SynRequest) String() string { return proto.CompactTextString(m) }
func (*SynRequest) ProtoMessage()    {}
func (*SynRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{0}
}
func (m *SynRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynRequest.Unmarshal(m, b)
}
func (m *SynRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynRequest.Marshal(b, m, deterministic)
}
func (dst *SynRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynRequest.Merge(dst, src)
}
func (m *SynRequest) XXX_Size() int {
	return xxx_messageInfo_SynRequest.Size(m)
}
func (m *SynRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SynRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SynRequest proto.InternalMessageInfo

func (m *SynRequest) GetInitiator() *PeerDigest {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *SynRequest) GetTarget() *PeerDigest {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SynRequest) GetKnownPeers() []*PeerDigest {
	if m != nil {
		return m.KnownPeers
	}
	return nil
}

type AckRequest struct {
	Initiator            *PeerDigest     `protobuf:"bytes,1,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Target               *PeerDigest     `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	RequestedPeers       []*PeerDetailed `protobuf:"bytes,3,rep,name=RequestedPeers,proto3" json:"RequestedPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AckRequest) Reset()         { *m = AckRequest{} }
func (m *AckRequest) String() string { return proto.CompactTextString(m) }
func (*AckRequest) ProtoMessage()    {}
func (*AckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{1}
}
func (m *AckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRequest.Unmarshal(m, b)
}
func (m *AckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRequest.Marshal(b, m, deterministic)
}
func (dst *AckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRequest.Merge(dst, src)
}
func (m *AckRequest) XXX_Size() int {
	return xxx_messageInfo_AckRequest.Size(m)
}
func (m *AckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckRequest proto.InternalMessageInfo

func (m *AckRequest) GetInitiator() *PeerDigest {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *AckRequest) GetTarget() *PeerDigest {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AckRequest) GetRequestedPeers() []*PeerDetailed {
	if m != nil {
		return m.RequestedPeers
	}
	return nil
}

type SynAck struct {
	Initiator            *PeerDigest     `protobuf:"bytes,1,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Target               *PeerDigest     `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	NewPeers             []*PeerDetailed `protobuf:"bytes,3,rep,name=NewPeers,proto3" json:"NewPeers,omitempty"`
	UnknownPeers         []*PeerDigest   `protobuf:"bytes,4,rep,name=UnknownPeers,proto3" json:"UnknownPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SynAck) Reset()         { *m = SynAck{} }
func (m *SynAck) String() string { return proto.CompactTextString(m) }
func (*SynAck) ProtoMessage()    {}
func (*SynAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{2}
}
func (m *SynAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynAck.Unmarshal(m, b)
}
func (m *SynAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynAck.Marshal(b, m, deterministic)
}
func (dst *SynAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynAck.Merge(dst, src)
}
func (m *SynAck) XXX_Size() int {
	return xxx_messageInfo_SynAck.Size(m)
}
func (m *SynAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SynAck.DiscardUnknown(m)
}

var xxx_messageInfo_SynAck proto.InternalMessageInfo

func (m *SynAck) GetInitiator() *PeerDigest {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *SynAck) GetTarget() *PeerDigest {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SynAck) GetNewPeers() []*PeerDetailed {
	if m != nil {
		return m.NewPeers
	}
	return nil
}

func (m *SynAck) GetUnknownPeers() []*PeerDigest {
	if m != nil {
		return m.UnknownPeers
	}
	return nil
}

type PeerDigest struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerDigest) Reset()         { *m = PeerDigest{} }
func (m *PeerDigest) String() string { return proto.CompactTextString(m) }
func (*PeerDigest) ProtoMessage()    {}
func (*PeerDigest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{3}
}
func (m *PeerDigest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDigest.Unmarshal(m, b)
}
func (m *PeerDigest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDigest.Marshal(b, m, deterministic)
}
func (dst *PeerDigest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDigest.Merge(dst, src)
}
func (m *PeerDigest) XXX_Size() int {
	return xxx_messageInfo_PeerDigest.Size(m)
}
func (m *PeerDigest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDigest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDigest proto.InternalMessageInfo

func (m *PeerDigest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeerDigest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *PeerDigest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PeerDetailed struct {
	PublicKey            []byte                  `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	IP                   string                  `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32                   `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	GenerationTime       int64                   `protobuf:"varint,4,opt,name=GenerationTime,proto3" json:"GenerationTime,omitempty"`
	State                *PeerDetailed_PeerState `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PeerDetailed) Reset()         { *m = PeerDetailed{} }
func (m *PeerDetailed) String() string { return proto.CompactTextString(m) }
func (*PeerDetailed) ProtoMessage()    {}
func (*PeerDetailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{4}
}
func (m *PeerDetailed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDetailed.Unmarshal(m, b)
}
func (m *PeerDetailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDetailed.Marshal(b, m, deterministic)
}
func (dst *PeerDetailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDetailed.Merge(dst, src)
}
func (m *PeerDetailed) XXX_Size() int {
	return xxx_messageInfo_PeerDetailed.Size(m)
}
func (m *PeerDetailed) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDetailed.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDetailed proto.InternalMessageInfo

func (m *PeerDetailed) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeerDetailed) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *PeerDetailed) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PeerDetailed) GetGenerationTime() int64 {
	if m != nil {
		return m.GenerationTime
	}
	return 0
}

func (m *PeerDetailed) GetState() *PeerDetailed_PeerState {
	if m != nil {
		return m.State
	}
	return nil
}

type PeerDetailed_PeerState struct {
	Status               PeerDetailed_PeerState_PeerStatus      `protobuf:"varint,1,opt,name=Status,proto3,enum=api.PeerDetailed_PeerState_PeerStatus" json:"Status,omitempty"`
	CPULoad              string                                 `protobuf:"bytes,2,opt,name=CPULoad,proto3" json:"CPULoad,omitempty"`
	IOWaitRate           float32                                `protobuf:"fixed32,3,opt,name=IOWaitRate,proto3" json:"IOWaitRate,omitempty"`
	FreeDiskSpace        float32                                `protobuf:"fixed32,4,opt,name=FreeDiskSpace,proto3" json:"FreeDiskSpace,omitempty"`
	Version              string                                 `protobuf:"bytes,5,opt,name=Version,proto3" json:"Version,omitempty"`
	GeoPosition          *PeerDetailed_PeerState_GeoCoordinates `protobuf:"bytes,6,opt,name=GeoPosition,proto3" json:"GeoPosition,omitempty"`
	P2PFactor            int32                                  `protobuf:"varint,7,opt,name=P2PFactor,proto3" json:"P2PFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *PeerDetailed_PeerState) Reset()         { *m = PeerDetailed_PeerState{} }
func (m *PeerDetailed_PeerState) String() string { return proto.CompactTextString(m) }
func (*PeerDetailed_PeerState) ProtoMessage()    {}
func (*PeerDetailed_PeerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{4, 0}
}
func (m *PeerDetailed_PeerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDetailed_PeerState.Unmarshal(m, b)
}
func (m *PeerDetailed_PeerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDetailed_PeerState.Marshal(b, m, deterministic)
}
func (dst *PeerDetailed_PeerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDetailed_PeerState.Merge(dst, src)
}
func (m *PeerDetailed_PeerState) XXX_Size() int {
	return xxx_messageInfo_PeerDetailed_PeerState.Size(m)
}
func (m *PeerDetailed_PeerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDetailed_PeerState.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDetailed_PeerState proto.InternalMessageInfo

func (m *PeerDetailed_PeerState) GetStatus() PeerDetailed_PeerState_PeerStatus {
	if m != nil {
		return m.Status
	}
	return PeerDetailed_PeerState_Fault
}

func (m *PeerDetailed_PeerState) GetCPULoad() string {
	if m != nil {
		return m.CPULoad
	}
	return ""
}

func (m *PeerDetailed_PeerState) GetIOWaitRate() float32 {
	if m != nil {
		return m.IOWaitRate
	}
	return 0
}

func (m *PeerDetailed_PeerState) GetFreeDiskSpace() float32 {
	if m != nil {
		return m.FreeDiskSpace
	}
	return 0
}

func (m *PeerDetailed_PeerState) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PeerDetailed_PeerState) GetGeoPosition() *PeerDetailed_PeerState_GeoCoordinates {
	if m != nil {
		return m.GeoPosition
	}
	return nil
}

func (m *PeerDetailed_PeerState) GetP2PFactor() int32 {
	if m != nil {
		return m.P2PFactor
	}
	return 0
}

type PeerDetailed_PeerState_GeoCoordinates struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=Lon,proto3" json:"Lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerDetailed_PeerState_GeoCoordinates) Reset()         { *m = PeerDetailed_PeerState_GeoCoordinates{} }
func (m *PeerDetailed_PeerState_GeoCoordinates) String() string { return proto.CompactTextString(m) }
func (*PeerDetailed_PeerState_GeoCoordinates) ProtoMessage()    {}
func (*PeerDetailed_PeerState_GeoCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_a5b3a568f29dbe0b, []int{4, 0, 0}
}
func (m *PeerDetailed_PeerState_GeoCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDetailed_PeerState_GeoCoordinates.Unmarshal(m, b)
}
func (m *PeerDetailed_PeerState_GeoCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDetailed_PeerState_GeoCoordinates.Marshal(b, m, deterministic)
}
func (dst *PeerDetailed_PeerState_GeoCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDetailed_PeerState_GeoCoordinates.Merge(dst, src)
}
func (m *PeerDetailed_PeerState_GeoCoordinates) XXX_Size() int {
	return xxx_messageInfo_PeerDetailed_PeerState_GeoCoordinates.Size(m)
}
func (m *PeerDetailed_PeerState_GeoCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDetailed_PeerState_GeoCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDetailed_PeerState_GeoCoordinates proto.InternalMessageInfo

func (m *PeerDetailed_PeerState_GeoCoordinates) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *PeerDetailed_PeerState_GeoCoordinates) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterType((*SynRequest)(nil), "api.SynRequest")
	proto.RegisterType((*AckRequest)(nil), "api.AckRequest")
	proto.RegisterType((*SynAck)(nil), "api.SynAck")
	proto.RegisterType((*PeerDigest)(nil), "api.PeerDigest")
	proto.RegisterType((*PeerDetailed)(nil), "api.PeerDetailed")
	proto.RegisterType((*PeerDetailed_PeerState)(nil), "api.PeerDetailed.PeerState")
	proto.RegisterType((*PeerDetailed_PeerState_GeoCoordinates)(nil), "api.PeerDetailed.PeerState.GeoCoordinates")
	proto.RegisterEnum("api.PeerDetailed_PeerState_PeerStatus", PeerDetailed_PeerState_PeerStatus_name, PeerDetailed_PeerState_PeerStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoveryClient interface {
	Synchronize(ctx context.Context, in *SynRequest, opts ...grpc.CallOption) (*SynAck, error)
	Acknowledge(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type discoveryClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryClient(cc *grpc.ClientConn) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) Synchronize(ctx context.Context, in *SynRequest, opts ...grpc.CallOption) (*SynAck, error) {
	out := new(SynAck)
	err := c.cc.Invoke(ctx, "/api.Discovery/Synchronize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) Acknowledge(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.Discovery/Acknowledge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServer is the server API for Discovery service.
type DiscoveryServer interface {
	Synchronize(context.Context, *SynRequest) (*SynAck, error)
	Acknowledge(context.Context, *AckRequest) (*empty.Empty, error)
}

func RegisterDiscoveryServer(s *grpc.Server, srv DiscoveryServer) {
	s.RegisterService(&_Discovery_serviceDesc, srv)
}

func _Discovery_Synchronize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).Synchronize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/Synchronize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).Synchronize(ctx, req.(*SynRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/Acknowledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).Acknowledge(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Synchronize",
			Handler:    _Discovery_Synchronize_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _Discovery_Acknowledge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor_discovery_a5b3a568f29dbe0b) }

var fileDescriptor_discovery_a5b3a568f29dbe0b = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0xed, 0x24, 0xfd, 0x3d, 0xc9, 0x9f, 0x86, 0x3d, 0x20, 0x2b, 0x45, 0x28, 0xb2, 0x50,
	0xa9, 0x90, 0x9a, 0x8a, 0x94, 0x03, 0x5c, 0x90, 0xd2, 0x96, 0x56, 0x51, 0xab, 0xd6, 0xda, 0xb4,
	0x70, 0xde, 0x3a, 0x83, 0x59, 0x25, 0xdd, 0x0d, 0xeb, 0x0d, 0x95, 0x79, 0x0f, 0xce, 0x3c, 0x00,
	0xaf, 0xc1, 0x4b, 0xf0, 0x36, 0x68, 0x37, 0x76, 0xed, 0x96, 0xaa, 0x1c, 0x50, 0x6f, 0xb3, 0xdf,
	0x7e, 0xb3, 0xfb, 0xcd, 0x37, 0xa3, 0x81, 0xb5, 0x09, 0x4f, 0x63, 0xf9, 0x05, 0x55, 0xd6, 0x9f,
	0x2b, 0xa9, 0x25, 0xf1, 0xd8, 0x9c, 0x77, 0xd7, 0x13, 0x29, 0x93, 0x19, 0x6e, 0x5b, 0xe8, 0x62,
	0xf1, 0x71, 0x1b, 0x2f, 0xe7, 0x3a, 0x67, 0x84, 0xdf, 0x1c, 0x80, 0x71, 0x26, 0x28, 0x7e, 0x5e,
	0x60, 0xaa, 0xc9, 0x16, 0xf8, 0x23, 0xc1, 0x35, 0x67, 0x5a, 0xaa, 0xc0, 0xe9, 0x39, 0x9b, 0xcd,
	0xc1, 0x5a, 0x9f, 0xcd, 0x79, 0x3f, 0x42, 0x54, 0xfb, 0x3c, 0xc1, 0x54, 0xd3, 0x92, 0x41, 0x9e,
	0x43, 0xe3, 0x8c, 0xa9, 0x04, 0x75, 0xe0, 0xde, 0xcd, 0xcd, 0xaf, 0xc9, 0x36, 0xc0, 0x91, 0x90,
	0x57, 0xc2, 0x5c, 0xa5, 0x81, 0xd7, 0xf3, 0xee, 0x22, 0x57, 0x28, 0xe1, 0x77, 0x07, 0x60, 0x18,
	0x4f, 0x1f, 0x5a, 0xd7, 0x1b, 0x68, 0xe7, 0x5f, 0xe0, 0xa4, 0xaa, 0xed, 0x51, 0x99, 0x80, 0x9a,
	0xf1, 0x19, 0x4e, 0xe8, 0x2d, 0x62, 0xf8, 0xd3, 0x81, 0xc6, 0x38, 0x13, 0xc3, 0x78, 0xfa, 0x60,
	0xea, 0xb6, 0xe0, 0xbf, 0x13, 0xbc, 0xfa, 0x8b, 0xae, 0x6b, 0x0a, 0xd9, 0x81, 0xd6, 0xb9, 0x98,
	0x96, 0x36, 0xd7, 0xee, 0xb6, 0xf9, 0x06, 0x29, 0x3c, 0x01, 0x28, 0xef, 0xc8, 0x13, 0xf0, 0xa3,
	0xc5, 0xc5, 0x8c, 0xc7, 0x47, 0x98, 0xd9, 0x4a, 0x5a, 0xb4, 0x04, 0x48, 0x1b, 0xdc, 0x51, 0x64,
	0x45, 0xfb, 0xd4, 0x1d, 0x45, 0x84, 0x40, 0x2d, 0x92, 0x4a, 0x07, 0x5e, 0xcf, 0xd9, 0xac, 0x53,
	0x1b, 0x87, 0xbf, 0x6a, 0xd0, 0xaa, 0xea, 0xfb, 0xf7, 0x27, 0xc9, 0x06, 0xb4, 0x0f, 0x51, 0xa0,
	0x62, 0x9a, 0x4b, 0x71, 0xc6, 0x2f, 0x31, 0xa8, 0xf5, 0x9c, 0x4d, 0x8f, 0xde, 0x42, 0xc9, 0x4b,
	0xa8, 0x8f, 0x35, 0xd3, 0x18, 0xd4, 0xad, 0xad, 0xeb, 0x7f, 0x78, 0x65, 0x0f, 0x96, 0x42, 0x97,
	0xcc, 0xee, 0x0f, 0x0f, 0xfc, 0x6b, 0x90, 0xbc, 0x85, 0x86, 0x09, 0x16, 0xa9, 0xd5, 0xd9, 0x1e,
	0x6c, 0xdc, 0xf3, 0xc2, 0x75, 0xb4, 0x48, 0x69, 0x9e, 0x45, 0x02, 0x58, 0xdd, 0x8b, 0xce, 0x8f,
	0x25, 0x9b, 0xe4, 0x15, 0x15, 0x47, 0xf2, 0x14, 0x60, 0x74, 0xfa, 0x81, 0x71, 0x4d, 0x8d, 0x3e,
	0x53, 0x9c, 0x4b, 0x2b, 0x08, 0x79, 0x06, 0xff, 0x1f, 0x28, 0xc4, 0x7d, 0x9e, 0x4e, 0xc7, 0x73,
	0x16, 0x2f, 0x2b, 0x74, 0xe9, 0x4d, 0xd0, 0xbc, 0xff, 0x1e, 0x55, 0xca, 0xa5, 0xb0, 0x25, 0xfa,
	0xb4, 0x38, 0x92, 0x63, 0x68, 0x1e, 0xa2, 0x8c, 0x64, 0xca, 0x8d, 0x1b, 0x41, 0xc3, 0x1a, 0xf0,
	0xe2, 0x3e, 0xf9, 0x87, 0x28, 0xf7, 0xa4, 0x54, 0x13, 0x2e, 0x98, 0xc6, 0x94, 0x56, 0xd3, 0x6d,
	0xcb, 0x06, 0xd1, 0x01, 0x8b, 0xcd, 0x3c, 0xaf, 0xda, 0x4e, 0x94, 0x40, 0xf7, 0x95, 0x69, 0x47,
	0x35, 0x99, 0x74, 0xc0, 0x3b, 0x66, 0xda, 0x9a, 0xe6, 0x52, 0x13, 0x5a, 0x44, 0x0a, 0xeb, 0x82,
	0x41, 0xa4, 0x08, 0x77, 0x97, 0x73, 0x96, 0x3b, 0xe5, 0x43, 0xfd, 0x80, 0x2d, 0x66, 0xba, 0xb3,
	0x42, 0x3a, 0xd0, 0xda, 0x95, 0x52, 0xa7, 0x5a, 0xb1, 0x39, 0x17, 0x49, 0xc7, 0x21, 0x0d, 0x70,
	0x4f, 0xa7, 0x1d, 0x97, 0xac, 0x41, 0x73, 0xac, 0xa5, 0x62, 0x09, 0x9e, 0x8a, 0x59, 0xd6, 0xf1,
	0x06, 0x1a, 0xfc, 0xfd, 0x62, 0xc3, 0x91, 0x2d, 0x68, 0x8e, 0x33, 0x11, 0x7f, 0x52, 0x52, 0xf0,
	0xaf, 0x48, 0x96, 0x63, 0x5e, 0xae, 0xb2, 0x6e, 0xb3, 0x00, 0x86, 0xf1, 0x34, 0x5c, 0x21, 0xaf,
	0xa1, 0x39, 0x8c, 0xcd, 0xdc, 0xcf, 0x70, 0x92, 0x14, 0xf4, 0x72, 0xc3, 0x74, 0x1f, 0xf7, 0x97,
	0x6b, 0xb2, 0x5f, 0xac, 0xc9, 0xfe, 0x3b, 0xb3, 0x26, 0xc3, 0x95, 0x8b, 0x86, 0x45, 0x76, 0x7e,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xd4, 0x11, 0xe3, 0x5e, 0x05, 0x00, 0x00,
}
