version: "3.7"

networks:
  uniris:
  peer1:
  peer2:
  peer3:

services:
  peer1:
    build: 
      dockerfile: build/package/Dockerfile
      context: ..
    environment:
      - UNIRIS_NETWORK_INTERFACE=eth0
      - UNIRIS_DISCOVERY_REDIS_HOST=redis
      - UNIRIS_DISCOVERY_AMQP_HOST=rabbitmq
    networks:
      uniris:
        aliases: 
          - peer1
      peer1:
    depends_on:
      - redis1
      - rabbitmq1

  redis1:
    image: redis
    networks:
      peer1:
        aliases:
          - redis
  rabbitmq1:
    image: rabbitmq
    networks:
      peer1:
        aliases:
          - rabbitmq
    
  peer2:
    build: 
      dockerfile: build/package/Dockerfile
      context: ..
    environment:
      - UNIRIS_PUBLICKEY=MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4cJYIBdi+WjxtbFuNn+QCaD+94SbL3vpBJpXbTcYcMnb2v2IYDX0XhRUchKMnjdvMa6X6nokrTGTlfVY9mmr6Q==
      - UNIRIS_NETWORK_INTERFACE=eth0
      - UNIRIS_DISCOVERY_PORT=3545
      - UNIRIS_DISCOVERY_REDIS_HOST=redis
      - UNIRIS_DISCOVERY_SEEDS=peer1:3545:MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhNngAzz3Ws1cz7veHnzeCwi9cuJhmpcHoi8+q3y75UL1vG5hyfnEMTjDCeeRHiobASUGvawGlcxexJzlZPIVYg==
      - UNIRIS_DISCOVERY_AMQP_HOST=rabbitmq
    depends_on:
      - redis2
      - rabbitmq2
    networks:
      uniris:
        aliases:
          - peer2
      peer2:

  redis2:
    image: redis
    networks:
      peer2:
        aliases:
          - redis
  rabbitmq2:
    image: rabbitmq
    networks:
      peer2:
        aliases:
          - rabbitmq

  peer3:
    build: 
      dockerfile: build/package/Dockerfile
      context: ..
    environment:
      - UNIRIS_PUBLICKEY=MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXjQEnfjxr1gHFetBym2C8zcU9n+DGRz3Ip+dLErOjCtQ8PoKzjQei2S9vle70Ano6MdaZlUHT1TLrFIrqYto1Q==
      - UNIRIS_NETWORK_INTERFACE=eth0
      - UNIRIS_DISCOVERY_PORT=3545
      - UNIRIS_DISCOVERY_REDIS_HOST=redis
      - UNIRIS_DISCOVERY_SEEDS=peer1:3545:MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhNngAzz3Ws1cz7veHnzeCwi9cuJhmpcHoi8+q3y75UL1vG5hyfnEMTjDCeeRHiobASUGvawGlcxexJzlZPIVYg==
      - UNIRIS_DISCOVERY_AMQP_HOST=rabbitmq
    depends_on:
      - redis3
      - rabbitmq3
    networks:
      uniris:
        aliases:
          - peer3
      peer3:

  redis3:
    image: redis
    networks:
      peer3:
        aliases:
          - redis

  rabbitmq3:
    image: rabbitmq
    networks:
      peer3:
        aliases:
          - rabbitmq
