version: "2.0"

services:
  peer:
    build: 
      dockerfile: build/package/Dockerfile
      context: ..
    environment:
      - UNIRIS_NETWORK_INTERFACE=eth0
      - UNIRIS_DISCOVERY_REDIS_HOST=localhost
      - UNIRIS_DISCOVERY_AMQP_HOST=localhost