version: "2.0"

networks:
  uniris:
    external: true

services:
  peer:
    build: 
      dockerfile: build/package/Dockerfile
      context: ..
    environment:
      - UNIRIS_NETWORK_INTERFACE=eth0
    networks:
      uniris:
        ipv4_address: 172.16.0.10