swagger: "2.0"

basePath: /api

info:
  description: |
    This is the endpoints provided by the robot UNIRIS.
    This API is documented in **OpenAPI format**
    You can find out more about the robot code here [http://github.com/uniris/uniris-core](http://github.com/uniris/uniris-core)
  version: 1.0
  title: UNIRIS API
  contact:
    name: UNIRIS Support
    email: dev@uniris.io

produces:
  - application/json

tags:
  - name: Account
    description: Manage and query accounts

paths:
    /account/:hash:
      get:
        tags:
        - Account
        summary: Get account's details
        description: |
          Retrieve account details by requested the data service of the UNIRIS robot.
          All the data are encrypted and need to be decrypted by the client.
        operationId: getAccount
        parameters:
          - name: hash
            in: path
            required: true
            type: string
            description: Encrypted hash of the person's public key
          - name: signature
            in: query
            required: true
            type: string
            description: Signature of the encrypted hash by the shared private key of client devices
        responses:
          "200":
            description: Encrypted account details
            schema:
              $ref: "#/definitions/AccountDetails"
          default:
            description: Unexpected error
            schema:
              $ref: "#/definitions/Error"



definitions:
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  AccountDetails:
    required:
      - encrypted_wallet
      - encrypted_aes_key
      - "@wallet_encrypted_person"
    properties:
      encrypted_wallet:
        type: string
      encrypted_aes_key:
        type: string
      "@wallet_encrypted_person":
        type: string