swagger: "2.0"

basePath: /api

info:
  description: |
    This is the endpoints provided by the UNIRIS robot.
    This API is documented in **OpenAPI format**
    You can find out more about the robot code here [http://github.com/uniris/uniris-core](http://github.com/uniris/uniris-core)
  version: 1.0
  title: UNIRIS API
  contact:
    name: UNIRIS Support
    email: dev@uniris.io

produces:
  - application/json

tags:
  - name: Account
    description: Manage and query accounts

paths:
  /account:
    post:
      tags:
        - Account
      summary: Enroll a new user
      description: Creates a new wallet
      operationId: createAccount
      parameters:
        - name: account
          in: body
          required: true
          schema:
            $ref: "#/definitions/AccountCreationRequest"
          description: Account creation request
      responses:
        "201":  
          description: Account creation response
          schema:
            $ref: "#/definitions/AccountCreationResult"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
          
  /account/{hash}:
      head:
        tags:
          - Account
        summary: Check if an account exist
        operationId: existAccount
        parameters:
          - name: hash
            in: path
            required: true
            type: string
            description: Encrypted hash of the person's public key
          - name: signature
            in: query
            required: true
            type: string
            description: Signature of the encrypted hash by the shared private key of client devices
        responses:
          "200":
            description: Existance of the account
            headers:
              Account-Exist:
                type: boolean
                description: Defines if the ressource exist or not
          default:
            description: Error
            headers:
              Error:
                type: string
                description: Unexpected error
      get:
        tags:
        - Account
        summary: Get account's details
        description: |
          Retrieve account details by requesting the data service of the UNIRIS robot.
          All the data are encrypted and need to be decrypted by the client.
        operationId: getAccount
        parameters:
          - name: hash
            in: path
            required: true
            type: string
            description: Encrypted hash of the person's public key
          - name: signature
            in: query
            required: true
            type: string
            description: Signature of the encrypted hash by the shared private key of client devices
        responses:
          "200":
            description: Encrypted account details
            schema:
              $ref: "#/definitions/AccountDetails"
          default:
            description: Error
            schema:
              $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    required:
      - error_message
      - error_code
    properties:
      error_message:
        type: string
        description: Error message
      error_code:
        type: int
        description: HTTP code error
      error_signature:
        type: string
        description: Signature validating the error
  AccountDetails:
    required:
      - encrypted_wallet
      - encrypted_aes_key
      - encrypted_address
      - signature_request
    properties:
      encrypted_wallet:
        description: Encrypted Wallet details
        type: string
      encrypted_aes_key:
        description: Encrypted key which encrypt the wallet
        type: string
      encrypted_address:
        description: Encryted address with EM key
        type: string
      signature_request:
        description: Request signature
        type: string
  AccountCreationRequest:
    required:
      - encrypted_bio_data
      - encrypted_keychain_data
      - signatures_bio
      - signatures_keychain
      - signature_request
    properties:
      encrypted_bio_data:
        description: Encrypted Biometric data
        type: string
      encrypted_keychain_data:
        descrpition: Encrypted Keychain data
        type: string
      signatures_bio:
        description: Biometric data signatures
        $ref: "#/definitions/Signatures"
      signatures_keychain:
        description: Keychain data signatures
        $ref: "#/definitions/Signatures"
      signature_request:
        description: Request signature
        type: string
  AccountCreationResult:
    required:
      - transactions
      - signature
    properties:
      transactions:
        description: Transactions hash for the wallet creation
        type: object
        properties:
          required:
            - biometric
            - keychain
          biometric:
            $ref: "#/definitions/TransactionResult"
            description: Biometric transaction result
          keychain:
            $ref: "#/definitions/TransactionResult"
            description: Keychain transaction result
      signature:
        description: Signature of the response
        type: string

  Signatures:
    required:
      - biod_sig
      - person_sig
    properties:
      biod_sig:
        description: Signature performed by the biometric device
        type: string
      person_sig:
        description: Signature performed by the person
        type: string


  TransactionResult:
    required:
      - transaction_hash
      - master_peer_ip
    properties:
      transaction_hash:
        type: string
        description: Transaction hash
      master_peer_ip:
        type: string
        description: IP of the master peer which lead the transaction processing
      signature:
        type: string
        description: Signature of the person